
# tool: scribe-data
# All polish (Q809) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?verbs
    ?past
  ?indicative
  ?infinitive
  ?plural
  ?present
  ?thirdPerson
  ?indicative
  ?plural
  ?neuter
  ?passiveParticiple
  ?plural
  ?past
  ?masculinePersonal
  ?thirdPerson
  ?infinitive
  ?singular
  ?imperative
  ?thirdPerson
  ?plural
  ?present
  ?firstPerson
  ?indicative
  ?singular
  ?neuter
  ?past
  ?thirdPerson
  ?singular
  ?past
  ?masculine
  ?secondPerson
  ?plural
  ?imperative
  ?thirdPerson
  ?plural
  ?present
  ?secondPerson
  ?indicative
  ?singular
  ?firstPerson
  ?singular
  ?present
  ?thirdPerson
  ?plural
  ?feminine
  ?activeParticiple
  ?present
  ?conditional
  ?plural
  ?feminine
  ?present
  ?singular
  ?feminine
  ?activeParticiple
  ?plural
  ?present
  ?thirdPerson
  ?singular
  ?masculineInanimate
  ?passiveParticiple
  ?singular
  ?neuter
  ?activeParticiple
  ?future
  ?indicative
  ?singular
  ?past
  ?firstPerson
  ?masculine
  ?singular
  ?past
  ?masculine
  ?thirdPerson
  ?indicative
  ?singular
  ?feminine
  ?past
  ?firstPerson
  ?singular
  ?masculineAnimate
  ?passiveParticiple
  ?plural
  ?neuter
  ?activeParticiple
  ?plural
  ?past
  ?firstPerson
  ?notMasculinePersonal
  ?present
  ?imperative
  ?plural
  ?past
  ?masculinePersonal
  ?secondPerson
  ?plural
  ?masculineInanimate
  ?passiveParticiple
  ?singular
  ?neuter
  ?past
  ?firstPerson
  ?plural
  ?past
  ?thirdPerson
  ?notMasculinePersonal
  ?singular
  ?imperative
  ?secondPerson
  ?infinitive
  ?plural
  ?masculineAnimate
  ?passiveParticiple
  ?singular
  ?neuter
  ?past
  ?secondPerson
  ?plural
  ?imperative
  ?secondPerson
  ?singular
  ?present
  ?firstPerson
  ?singular
  ?feminine
  ?past
  ?thirdPerson
  ?plural
  ?past
  ?secondPerson
  ?notMasculinePersonal
  ?singular
  ?present
  ?secondPerson
  ?singular
  ?firstPerson
  ?imperative
  ?plural
  ?present
  ?firstPerson
  ?singular
  ?past
  ?masculine
  ?thirdPerson
  ?plural
  ?present
  ?secondPerson
  ?plural
  ?past
  ?firstPerson
  ?masculinePersonal
  ?plural
  ?firstPerson
  ?imperative
  ?plural
  ?feminine
  ?passiveParticiple
  ?singular
  ?present
  ?firstPerson
  ?indicative
  ?future
  ?conditional
  ?singular
  ?present
  ?singular
  ?masculineInanimate
  ?activeParticiple
  ?singular
  ?present
  ?thirdPerson
  ?indicative
  ?singular
  ?masculineAnimate
  ?activeParticiple
  ?singular
  ?feminine
  ?passiveParticiple
  ?present
  ?indicative
  ?singular
  ?neuter
  ?passiveParticiple
  ?plural
  ?masculineAnimate
  ?activeParticiple
  ?singular
  ?present
  ?secondPerson
  ?indicative
  ?singular
  ?feminine
  ?past
  ?secondPerson
  WHERE {
    ?lexeme dct:language wd:Q809 ;
        wikibase:lexicalCategory wd:Q24905 ;
        wikibase:lemma ?verbs .
        FILTER(lang(?verbs) = "pl")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculinePersonalForm .
            ?masculinePersonalForm ontolex:representation ?masculinePersonal ;
                wikibase:grammaticalFeature wd:Q27918551 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineInanimateForm .
            ?masculineInanimateForm ontolex:representation ?masculineInanimate ;
                wikibase:grammaticalFeature wd:Q52943434 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?futureForm .
            ?futureForm ontolex:representation ?future ;
                wikibase:grammaticalFeature wd:Q501405 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineAnimateForm .
            ?masculineAnimateForm ontolex:representation ?masculineAnimate ;
                wikibase:grammaticalFeature wd:Q54020116 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?notMasculinePersonalForm .
            ?notMasculinePersonalForm ontolex:representation ?notMasculinePersonal ;
                wikibase:grammaticalFeature wd:Q54152717 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculinePersonalForm .
            ?masculinePersonalForm ontolex:representation ?masculinePersonal ;
                wikibase:grammaticalFeature wd:Q27918551 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineInanimateForm .
            ?masculineInanimateForm ontolex:representation ?masculineInanimate ;
                wikibase:grammaticalFeature wd:Q52943434 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?notMasculinePersonalForm .
            ?notMasculinePersonalForm ontolex:representation ?notMasculinePersonal ;
                wikibase:grammaticalFeature wd:Q54152717 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineAnimateForm .
            ?masculineAnimateForm ontolex:representation ?masculineAnimate ;
                wikibase:grammaticalFeature wd:Q54020116 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?notMasculinePersonalForm .
            ?notMasculinePersonalForm ontolex:representation ?notMasculinePersonal ;
                wikibase:grammaticalFeature wd:Q54152717 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculinePersonalForm .
            ?masculinePersonalForm ontolex:representation ?masculinePersonal ;
                wikibase:grammaticalFeature wd:Q27918551 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?futureForm .
            ?futureForm ontolex:representation ?future ;
                wikibase:grammaticalFeature wd:Q501405 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineInanimateForm .
            ?masculineInanimateForm ontolex:representation ?masculineInanimate ;
                wikibase:grammaticalFeature wd:Q52943434 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineAnimateForm .
            ?masculineAnimateForm ontolex:representation ?masculineAnimate ;
                wikibase:grammaticalFeature wd:Q54020116 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineAnimateForm .
            ?masculineAnimateForm ontolex:representation ?masculineAnimate ;
                wikibase:grammaticalFeature wd:Q54020116 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activeParticipleForm .
            ?activeParticipleForm ontolex:representation ?activeParticiple ;
                wikibase:grammaticalFeature wd:Q72249355 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
}