# tool: scribe-data
# All Polish (Q809) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verbs
  ?conditionalFuture
  ?passiveParticipleMasculineAnimatePlural
  ?passiveParticipleMasculineAnimateSingular
  ?thirdPersonPastNeuterSingular
  ?activeParticipleFeminineSingular
  ?activeParticipleFemininePlural
  ?indicativeFirstPersonPresentPlural
  ?indicativeFirstPersonPresentSingular
  ?secondPersonMasculinePersonalPastPlural
  ?thirdPersonMasculinePastSingular
  ?secondPersonImperativePlural
  ?indicativeThirdPersonMasculinePastSingular
  ?passiveParticipleMasculineInanimateSingular
  ?firstPersonPresentSingular
  ?notMasculinePersonalFirstPersonPastPlural
  ?secondPersonImperativeSingular
  ?indicativeThirdPersonPresentSingular
  ?passiveParticipleMasculineInanimatePlural
  ?indicativeThirdPersonPresentPlural
  ?activeParticipleNeuterSingular
  ?infinitive
  ?firstPersonPresentPlural
  ?secondPersonPresentSingular
  ?imperativePresent
  ?firstPersonPastFeminineSingular
  ?activeParticipleNeuterPlural
  ?notMasculinePersonalThirdPersonPastPlural
  ?activeParticipleMasculineAnimatePlural
  ?secondPersonPresentPlural
  ?thirdPersonImperativePlural
  ?thirdPersonMasculinePersonalPastPlural
  ?indicativePast
  ?activeParticipleMasculineAnimateSingular
  ?presentFemininePlural
  ?masculineFirstPersonPastSingular
  ?secondPersonPastFeminineSingular
  ?thirdPersonImperativeSingular
  ?indicativeSecondPersonPresentPlural
  ?indicativePresent
  ?indicativeSecondPersonPresentSingular
  ?passiveParticipleFeminineSingular
  ?firstPersonPastNeuterSingular
  ?thirdPersonPresentSingular
  ?imperativeFirstPersonSingular
  ?activeParticipleMasculineInanimateSingular
  ?notMasculinePersonalSecondPersonPastPlural
  ?passiveParticipleFemininePlural
  ?presentSingular
  ?imperativeFirstPersonPlural
  ?thirdPersonPresentPlural
  ?secondPersonPastNeuterSingular
  ?conditionalPresent
  ?masculinePersonalFirstPersonPastPlural
  ?thirdPersonPastFeminineSingular
  ?indicativeFuture
  ?passiveParticipleNeuterSingular
  ?secondPersonMasculinePastSingular
  ?firstPersonSingular
  ?passiveParticipleNeuterPlural
  ?singularFirstPersonPresentIndicative
  ?activeParticipleSingularMasculineInanimate
  ?activeParticiplePluralFeminine
  ?activeParticipleSingularFeminine
  ?singularSecondPersonPresentIndicative
  ?passiveParticipleSingularNeuter
  ?passiveParticiplePluralMasculineInanimate
  ?passiveParticiplePluralMasculineAnimate
  ?activeParticiplePluralNeuter
  ?passiveParticipleSingularMasculineAnimate
  ?passiveParticipleSingularMasculineInanimate
  ?passiveParticiplePluralFeminine
  ?pluralThirdPersonPresentIndicative
  ?pluralFirstPersonPresentIndicative
  ?passiveParticipleSingularFeminine
  ?activeParticiplePluralMasculineInanimate
  ?activeParticipleSingularNeuter
  ?activeParticiplePluralMasculineAnimate
  ?pluralSecondPersonPresentIndicative
  ?activeParticipleSingularMasculineAnimate
  ?passiveParticiplePluralNeuter
  ?singularThirdPersonPresentIndicative
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q809 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verbs ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalFutureForm .
    ?conditionalFutureForm ontolex:representation ?conditionalFuture ;
      wikibase:grammaticalFeature wd:Q625581, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleMasculineAnimatePluralForm .
    ?passiveParticipleMasculineAnimatePluralForm ontolex:representation ?passiveParticipleMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleMasculineAnimateSingularForm .
    ?passiveParticipleMasculineAnimateSingularForm ontolex:representation ?passiveParticipleMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPastNeuterSingularForm .
    ?thirdPersonPastNeuterSingularForm ontolex:representation ?thirdPersonPastNeuterSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1994301, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleFeminineSingularForm .
    ?activeParticipleFeminineSingularForm ontolex:representation ?activeParticipleFeminineSingular ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleFemininePluralForm .
    ?activeParticipleFemininePluralForm ontolex:representation ?activeParticipleFemininePlural ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPresentPluralForm .
    ?indicativeFirstPersonPresentPluralForm ontolex:representation ?indicativeFirstPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPresentSingularForm .
    ?indicativeFirstPersonPresentSingularForm ontolex:representation ?indicativeFirstPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePersonalPastPluralForm .
    ?secondPersonMasculinePersonalPastPluralForm ontolex:representation ?secondPersonMasculinePersonalPastPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q27918551, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePastSingularForm .
    ?thirdPersonMasculinePastSingularForm ontolex:representation ?thirdPersonMasculinePastSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativePluralForm .
    ?secondPersonImperativePluralForm ontolex:representation ?secondPersonImperativePlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonMasculinePastSingularForm .
    ?indicativeThirdPersonMasculinePastSingularForm ontolex:representation ?indicativeThirdPersonMasculinePastSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q499327, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleMasculineInanimateSingularForm .
    ?passiveParticipleMasculineInanimateSingularForm ontolex:representation ?passiveParticipleMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPresentSingularForm .
    ?firstPersonPresentSingularForm ontolex:representation ?firstPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?notMasculinePersonalFirstPersonPastPluralForm .
    ?notMasculinePersonalFirstPersonPastPluralForm ontolex:representation ?notMasculinePersonalFirstPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q54152717, wd:Q21714344, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativeSingularForm .
    ?secondPersonImperativeSingularForm ontolex:representation ?secondPersonImperativeSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPresentSingularForm .
    ?indicativeThirdPersonPresentSingularForm ontolex:representation ?indicativeThirdPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleMasculineInanimatePluralForm .
    ?passiveParticipleMasculineInanimatePluralForm ontolex:representation ?passiveParticipleMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPresentPluralForm .
    ?indicativeThirdPersonPresentPluralForm ontolex:representation ?indicativeThirdPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleNeuterSingularForm .
    ?activeParticipleNeuterSingularForm ontolex:representation ?activeParticipleNeuterSingular ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveForm .
    ?infinitiveForm ontolex:representation ?infinitive ;
      wikibase:grammaticalFeature wd:Q179230 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPresentPluralForm .
    ?firstPersonPresentPluralForm ontolex:representation ?firstPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPresentSingularForm .
    ?secondPersonPresentSingularForm ontolex:representation ?secondPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativePresentForm .
    ?imperativePresentForm ontolex:representation ?imperativePresent ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPastFeminineSingularForm .
    ?firstPersonPastFeminineSingularForm ontolex:representation ?firstPersonPastFeminineSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1994301, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleNeuterPluralForm .
    ?activeParticipleNeuterPluralForm ontolex:representation ?activeParticipleNeuterPlural ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?notMasculinePersonalThirdPersonPastPluralForm .
    ?notMasculinePersonalThirdPersonPastPluralForm ontolex:representation ?notMasculinePersonalThirdPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q54152717, wd:Q51929074, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleMasculineAnimatePluralForm .
    ?activeParticipleMasculineAnimatePluralForm ontolex:representation ?activeParticipleMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPresentPluralForm .
    ?secondPersonPresentPluralForm ontolex:representation ?secondPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonImperativePluralForm .
    ?thirdPersonImperativePluralForm ontolex:representation ?thirdPersonImperativePlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q22716, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePersonalPastPluralForm .
    ?thirdPersonMasculinePersonalPastPluralForm ontolex:representation ?thirdPersonMasculinePersonalPastPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q27918551, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastForm .
    ?indicativePastForm ontolex:representation ?indicativePast ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleMasculineAnimateSingularForm .
    ?activeParticipleMasculineAnimateSingularForm ontolex:representation ?activeParticipleMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentFemininePluralForm .
    ?presentFemininePluralForm ontolex:representation ?presentFemininePlural ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFirstPersonPastSingularForm .
    ?masculineFirstPersonPastSingularForm ontolex:representation ?masculineFirstPersonPastSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q21714344, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPastFeminineSingularForm .
    ?secondPersonPastFeminineSingularForm ontolex:representation ?secondPersonPastFeminineSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1994301, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonImperativeSingularForm .
    ?thirdPersonImperativeSingularForm ontolex:representation ?thirdPersonImperativeSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q22716, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPresentPluralForm .
    ?indicativeSecondPersonPresentPluralForm ontolex:representation ?indicativeSecondPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentForm .
    ?indicativePresentForm ontolex:representation ?indicativePresent ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPresentSingularForm .
    ?indicativeSecondPersonPresentSingularForm ontolex:representation ?indicativeSecondPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleFeminineSingularForm .
    ?passiveParticipleFeminineSingularForm ontolex:representation ?passiveParticipleFeminineSingular ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPastNeuterSingularForm .
    ?firstPersonPastNeuterSingularForm ontolex:representation ?firstPersonPastNeuterSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1994301, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPresentSingularForm .
    ?thirdPersonPresentSingularForm ontolex:representation ?thirdPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeFirstPersonSingularForm .
    ?imperativeFirstPersonSingularForm ontolex:representation ?imperativeFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleMasculineInanimateSingularForm .
    ?activeParticipleMasculineInanimateSingularForm ontolex:representation ?activeParticipleMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?notMasculinePersonalSecondPersonPastPluralForm .
    ?notMasculinePersonalSecondPersonPastPluralForm ontolex:representation ?notMasculinePersonalSecondPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q54152717, wd:Q51929049, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleFemininePluralForm .
    ?passiveParticipleFemininePluralForm ontolex:representation ?passiveParticipleFemininePlural ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentSingularForm .
    ?presentSingularForm ontolex:representation ?presentSingular ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeFirstPersonPluralForm .
    ?imperativeFirstPersonPluralForm ontolex:representation ?imperativeFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPresentPluralForm .
    ?thirdPersonPresentPluralForm ontolex:representation ?thirdPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPastNeuterSingularForm .
    ?secondPersonPastNeuterSingularForm ontolex:representation ?secondPersonPastNeuterSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1994301, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentForm .
    ?conditionalPresentForm ontolex:representation ?conditionalPresent ;
      wikibase:grammaticalFeature wd:Q625581, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePersonalFirstPersonPastPluralForm .
    ?masculinePersonalFirstPersonPastPluralForm ontolex:representation ?masculinePersonalFirstPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q27918551, wd:Q21714344, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPastFeminineSingularForm .
    ?thirdPersonPastFeminineSingularForm ontolex:representation ?thirdPersonPastFeminineSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1994301, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFutureForm .
    ?indicativeFutureForm ontolex:representation ?indicativeFuture ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleNeuterSingularForm .
    ?passiveParticipleNeuterSingularForm ontolex:representation ?passiveParticipleNeuterSingular ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePastSingularForm .
    ?secondPersonMasculinePastSingularForm ontolex:representation ?secondPersonMasculinePastSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonSingularForm .
    ?firstPersonSingularForm ontolex:representation ?firstPersonSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleNeuterPluralForm .
    ?passiveParticipleNeuterPluralForm ontolex:representation ?passiveParticipleNeuterPlural ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPresentIndicativeForm .
    ?singularFirstPersonPresentIndicativeForm ontolex:representation ?singularFirstPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleSingularMasculineInanimateForm .
    ?activeParticipleSingularMasculineInanimateForm ontolex:representation ?activeParticipleSingularMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q110786, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticiplePluralFeminineForm .
    ?activeParticiplePluralFeminineForm ontolex:representation ?activeParticiplePluralFeminine ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleSingularFeminineForm .
    ?activeParticipleSingularFeminineForm ontolex:representation ?activeParticipleSingularFeminine ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPresentIndicativeForm .
    ?singularSecondPersonPresentIndicativeForm ontolex:representation ?singularSecondPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleSingularNeuterForm .
    ?passiveParticipleSingularNeuterForm ontolex:representation ?passiveParticipleSingularNeuter ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q110786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticiplePluralMasculineInanimateForm .
    ?passiveParticiplePluralMasculineInanimateForm ontolex:representation ?passiveParticiplePluralMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q146786, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticiplePluralMasculineAnimateForm .
    ?passiveParticiplePluralMasculineAnimateForm ontolex:representation ?passiveParticiplePluralMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q146786, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticiplePluralNeuterForm .
    ?activeParticiplePluralNeuterForm ontolex:representation ?activeParticiplePluralNeuter ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleSingularMasculineAnimateForm .
    ?passiveParticipleSingularMasculineAnimateForm ontolex:representation ?passiveParticipleSingularMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q110786, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleSingularMasculineInanimateForm .
    ?passiveParticipleSingularMasculineInanimateForm ontolex:representation ?passiveParticipleSingularMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q110786, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticiplePluralFeminineForm .
    ?passiveParticiplePluralFeminineForm ontolex:representation ?passiveParticiplePluralFeminine ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPresentIndicativeForm .
    ?pluralThirdPersonPresentIndicativeForm ontolex:representation ?pluralThirdPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPresentIndicativeForm .
    ?pluralFirstPersonPresentIndicativeForm ontolex:representation ?pluralFirstPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleSingularFeminineForm .
    ?passiveParticipleSingularFeminineForm ontolex:representation ?passiveParticipleSingularFeminine ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticiplePluralMasculineInanimateForm .
    ?activeParticiplePluralMasculineInanimateForm ontolex:representation ?activeParticiplePluralMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q146786, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleSingularNeuterForm .
    ?activeParticipleSingularNeuterForm ontolex:representation ?activeParticipleSingularNeuter ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q110786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticiplePluralMasculineAnimateForm .
    ?activeParticiplePluralMasculineAnimateForm ontolex:representation ?activeParticiplePluralMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q146786, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPresentIndicativeForm .
    ?pluralSecondPersonPresentIndicativeForm ontolex:representation ?pluralSecondPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleSingularMasculineAnimateForm .
    ?activeParticipleSingularMasculineAnimateForm ontolex:representation ?activeParticipleSingularMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q72249355, wd:Q110786, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticiplePluralNeuterForm .
    ?passiveParticiplePluralNeuterForm ontolex:representation ?passiveParticiplePluralNeuter ;
      wikibase:grammaticalFeature wd:Q72249544, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPresentIndicativeForm .
    ?singularThirdPersonPresentIndicativeForm ontolex:representation ?singularThirdPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q192613, wd:Q682111 .
  }
}
