
# tool: scribe-data
# All swahili (Q7838) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?nouns
    ?indicative
  WHERE {
    ?lexeme dct:language wd:Q7838 ;
        wikibase:lexicalCategory wd:Q1084 ;
        wikibase:lemma ?nouns .
        FILTER(lang(?nouns) = "sw")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
}