# tool: scribe-data
# All German (Q188) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verbs
  ?indicativePerfectThirdPersonPluralActive
  ?indicativeSecondPersonPresentPluralActive
  ?indicativeSecondPersonPreteritePlural
  ?indicativeFutureFirstPersonPluralActive
  ?pluperfectFirstPersonPlural
  ?presentInfinitive
  ?indicativePerfectSecondPersonSingular
  ?thirdPersonPreteriteSingular
  ?pluperfectFirstPersonSingular
  ?indicativePluperfectThirdPersonPluralActive
  ?secondPersonFutureSingular
  ?indicativeThirdPersonFuturePluralActive
  ?indicativePerfectThirdPersonPlural
  ?secondPersonImperativePresentPluralActive
  ?secondPersonPreteritePlural
  ?indicativePluperfectFirstPersonPlural
  ?thirdPersonImperativePlural
  ?indicativePerfectThirdPersonSingular
  ?imperativePresentPlural
  ?indicativePluperfectThirdPersonActiveSingular
  ?indicativeThirdPersonPresentSingular
  ?perfectSecondPersonSingular
  ?indicativeThirdPersonPreteritePluralActive
  ?secondPersonImperativePresentPluralActiveSingular
  ?secondPersonPresentSingular
  ?indicativePluperfectThirdPersonPlural
  ?secondPersonPreteriteSingular
  ?indicativePerfectFirstPersonPluralActive
  ?perfectThirdPersonPlural
  ?indicativeThirdPersonPreteriteSingular
  ?perfectInfinitiveActive
  ?indicativeThirdPersonPresentActiveSingular
  ?imperativePlural
  ?indicativeThirdPersonFuturePlural
  ?thirdPersonFuturePlural
  ?indicativeThirdPersonFutureSingular
  ?indicativeSecondPersonImperativePresentActiveSingular
  ?indicativePluperfectSecondPersonActiveSingular
  ?indicativeThirdPersonPreteriteActiveSingular
  ?futureFirstPersonPlural
  ?pluperfectThirdPersonSingular
  ?presentInfinitiveActive
  ?indicativePluperfectSecondPersonPlural
  ?indicativeThirdPersonPreteritePlural
  ?indicativeSecondPersonFuturePlural
  ?indicativePreteriteFirstPersonPluralActive
  ?indicativeSecondPersonFutureActiveSingular
  ?indicativeSecondPersonPreteriteSingular
  ?indicativePluperfectSecondPersonSingular
  ?pluperfectSecondPersonPlural
  ?indicativePerfectFirstPersonSingular
  ?futureFirstPersonSingular
  ?imperativeSingular
  ?imperativeFirstPersonPlural
  ?indicativeFirstPersonPresentSingular
  ?indicativeFutureFirstPersonSingular
  ?indicativeSecondPersonPreteriteActiveSingular
  ?pluperfectThirdPerson
  ?indicativeSecondPersonFuturePluralActive
  ?perfectFirstPersonPlural
  ?indicativeFutureFirstPersonActiveSingular
  ?indicativeFirstPersonPresentActiveSingular
  ?indicativeThirdPersonPresentPlural
  ?thirdPersonFuture
  ?indicativePerfectSecondPersonPluralActive
  ?preteriteFirstPersonPlural
  ?perfectFirstPersonSingular
  ?imperativePresentSingular
  ?perfectImperativeSingular
  ?indicativePerfectThirdPersonActiveSingular
  ?perfectThirdPersonSingular
  ?indicativePluperfectFirstPersonActiveSingular
  ?indicativeFirstPersonPresentPluralActive
  ?thirdPersonPresent
  ?indicativePluperfectFirstPersonPluralActive
  ?indicativeThirdPersonPresentPluralActive
  ?firstPersonPresentPlural
  ?thirdPersonPresentPlural
  ?perfectInfinitive
  ?thirdPersonPreteritePlural
  ?indicativePerfectSecondPersonPlural
  ?indicativeThirdPersonFutureActiveSingular
  ?indicativePerfectSecondPersonActiveSingular
  ?perfectThirdPerson
  ?indicativePerfectFirstPersonPlural
  ?secondPersonImperativePresentActiveSingular
  ?indicativeSecondPersonFutureSingular
  ?perfectImperativePlural
  ?indicativePerfectFirstPersonActiveSingular
  ?secondPersonFuturePlural
  ?indicativeFutureFirstPersonPlural
  ?pluperfectThirdPersonPlural
  ?indicativeFirstPersonPresentPlural
  ?firstPersonPresentSingular
  ?thirdPersonPresentSingular
  ?indicativePluperfectThirdPersonSingular
  ?indicativePluperfectFirstPersonSingular
  ?indicativeSecondPersonPresentSingular
  ?secondPersonPresentPlural
  ?indicativeSecondPersonPreteritePluralActive
  ?preteriteFirstPersonSingular
  ?indicativePreteriteFirstPersonActiveSingular
  ?perfectSecondPersonPlural
  ?thirdPersonFutureSingular
  ?thirdPersonPreterite
  ?indicativeSecondPersonPresentActiveSingular
  ?indicativeSecondPersonPresentPlural
  ?indicativePluperfectSecondPersonPluralActive
  ?pluperfectSecondPersonSingular
  ?singularActiveFirstPersonPreteriteIndicative
  ?singularActivePresentThirdPersonIndicative
  ?pluralSecondPersonPluperfect
  ?preteriteThirdPerson
  ?pluralSecondPersonPresentIndicative
  ?indicativePresentThirdPersonSingular
  ?singularFutureSecondPerson
  ?singularPresentThirdPerson
  ?pluralSecondPersonPerfect
  ?singularActiveThirdPersonPluperfectIndicative
  ?singularActiveSecondPersonPerfectIndicative
  ?singularActivePresentSecondPersonIndicative
  ?singularImperative
  ?presentThirdPerson
  ?singularFirstPersonPluperfectIndicative
  ?pluralFirstPersonPresentIndicative
  ?thirdPersonPluperfect
  ?singularActiveFutureThirdPersonIndicative
  ?singularActiveFirstPersonFutureIndicative
  ?singularPresentSecondPerson
  ?singularFutureThirdPerson
  ?pluralFutureSecondPerson
  ?pluralPresentThirdPerson
  ?indicativePresentSecondPersonSingular
  ?singularPreteriteThirdPersonIndicative
  ?indicativePreteriteSecondPersonSingular
  ?singularActiveFirstPersonPerfectIndicative
  ?pluralFirstPersonPluperfectIndicative
  ?singularFirstPersonFuture
  ?singularFirstPersonPresentIndicative
  ?indicativePresentThirdPersonPlural
  ?pluralFirstPersonImperative
  ?singularThirdPersonPluperfect
  ?indicativePreteriteThirdPersonPlural
  ?activePluralPresentThirdPersonIndicative
  ?singularSecondPersonPluperfectIndicative
  ?singularThirdPersonPresentIndicative
  ?pluralPresentSecondPerson
  ?indicativePresentFirstPersonSingular
  ?singularPresentFirstPerson
  ?singularThirdPersonPerfectIndicative
  ?activePluralThirdPersonPluperfectIndicative
  ?pluralFutureThirdPerson
  ?activePluralSecondPersonPerfectIndicative
  ?activePluralPresentSecondPersonIndicative
  ?pluralPreteriteThirdPersonIndicative
  ?activePluralFutureThirdPersonIndicative
  ?pluralFirstPersonFuture
  ?activePluralFirstPersonFutureIndicative
  ?pluralThirdPersonPluperfect
  ?pluralSecondPersonPluperfectIndicative
  ?singularActivePresentFirstPersonIndicative
  ?indicativePreteriteSecondPersonPlural
  ?pluralThirdPersonPresentIndicative
  ?singularPreteriteSecondPerson
  ?singularSecondPersonPreteriteIndicative
  ?pluralPresentFirstPerson
  ?singularPresentThirdPersonIndicative
  ?pluralThirdPersonPerfectIndicative
  ?singularFutureSecondPersonIndicative
  ?activePluralFirstPersonPerfectIndicative
  ?singularFirstPersonPluperfect
  ?singularActivePresentImperativeSecondPersonIndicative
  ?singularActiveSecondPersonPluperfectIndicative
  ?pluralFirstPersonFutureIndicative
  ?singularFutureThirdPersonIndicative
  ?singularFirstPersonPerfectIndicative
  ?pluralPreteriteSecondPerson
  ?infinitivePresent
  ?pluralSecondPersonPreteriteIndicative
  ?pluralPresentThirdPersonIndicative
  ?activeInfinitivePerfect
  ?pluralFutureSecondPersonIndicative
  ?singularPresentSecondPersonIndicative
  ?singularActivePreteriteThirdPersonIndicative
  ?singularPreteriteSecondPersonIndicative
  ?singularPresentImperative
  ?singularActiveThirdPersonPerfectIndicative
  ?indicativePreteriteThirdPersonSingular
  ?activeInfinitivePresent
  ?singularPreteriteThirdPerson
  ?pluralFirstPersonPreteriteIndicative
  ?singularActivePresentImperativeSecondPerson
  ?pluralFirstPersonPerfect
  ?singularActivePluralPresentImperativeSecondPerson
  ?pluralFirstPersonPluperfect
  ?singularActivePreteriteSecondPersonIndicative
  ?activePluralPresentFirstPersonIndicative
  ?indicativePresentFirstPersonPlural
  ?singularPresentFirstPersonIndicative
  ?pluralImperativeThirdPerson
  ?singularFirstPersonFutureIndicative
  ?infinitivePerfect
  ?singularActiveFirstPersonPluperfectIndicative
  ?pluralFirstPersonPerfectIndicative
  ?singularActiveFutureSecondPersonIndicative
  ?pluralFutureThirdPersonIndicative
  ?singularSecondPersonPerfectIndicative
  ?pluralPresentSecondPersonIndicative
  ?pluralPresentImperative
  ?pluralPreteriteSecondPersonIndicative
  ?pluralFirstPersonPreterite
  ?pluralPreteriteThirdPerson
  ?singularFirstPersonPreteriteIndicative
  ?singularFirstPersonPerfect
  ?thirdPersonPerfect
  ?singularImperativePerfect
  ?activePluralSecondPersonPluperfectIndicative
  ?singularThirdPersonPreteriteIndicative
  ?singularThirdPersonPerfect
  ?pluralPresentFirstPersonIndicative
  ?activePluralPreteriteThirdPersonIndicative
  ?futureThirdPerson
  ?activePluralThirdPersonPerfectIndicative
  ?singularThirdPersonPluperfectIndicative
  ?pluralSecondPersonPerfectIndicative
  ?singularFirstPersonPreterite
  ?activePluralPresentImperativeSecondPerson
  ?singularSecondPersonPluperfect
  ?activePluralPreteriteSecondPersonIndicative
  ?pluralImperativePerfect
  ?singularSecondPersonPresentIndicative
  ?indicativePresentSecondPersonPlural
  ?singularSecondPersonPerfect
  ?pluralThirdPersonPreteriteIndicative
  ?activePluralFirstPersonPluperfectIndicative
  ?pluralThirdPersonPerfect
  ?activePluralFutureSecondPersonIndicative
  ?pluralImperative
  ?pluralThirdPersonPluperfectIndicative
  ?activePluralFirstPersonPreteriteIndicative
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q188 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verbs ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectThirdPersonPluralActiveForm .
    ?indicativePerfectThirdPersonPluralActiveForm ontolex:representation ?indicativePerfectThirdPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929074, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPresentPluralActiveForm .
    ?indicativeSecondPersonPresentPluralActiveForm ontolex:representation ?indicativeSecondPersonPresentPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q192613, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPreteritePluralForm .
    ?indicativeSecondPersonPreteritePluralForm ontolex:representation ?indicativeSecondPersonPreteritePlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q442485, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFutureFirstPersonPluralActiveForm .
    ?indicativeFutureFirstPersonPluralActiveForm ontolex:representation ?indicativeFutureFirstPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q501405, wd:Q21714344, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectFirstPersonPluralForm .
    ?pluperfectFirstPersonPluralForm ontolex:representation ?pluperfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentInfinitiveForm .
    ?presentInfinitiveForm ontolex:representation ?presentInfinitive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q179230 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectSecondPersonSingularForm .
    ?indicativePerfectSecondPersonSingularForm ontolex:representation ?indicativePerfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPreteriteSingularForm .
    ?thirdPersonPreteriteSingularForm ontolex:representation ?thirdPersonPreteriteSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q442485, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectFirstPersonSingularForm .
    ?pluperfectFirstPersonSingularForm ontolex:representation ?pluperfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectThirdPersonPluralActiveForm .
    ?indicativePluperfectThirdPersonPluralActiveForm ontolex:representation ?indicativePluperfectThirdPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929074, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFutureSingularForm .
    ?secondPersonFutureSingularForm ontolex:representation ?secondPersonFutureSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q501405, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonFuturePluralActiveForm .
    ?indicativeThirdPersonFuturePluralActiveForm ontolex:representation ?indicativeThirdPersonFuturePluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q501405, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectThirdPersonPluralForm .
    ?indicativePerfectThirdPersonPluralForm ontolex:representation ?indicativePerfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativePresentPluralActiveForm .
    ?secondPersonImperativePresentPluralActiveForm ontolex:representation ?secondPersonImperativePresentPluralActive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q192613, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPreteritePluralForm .
    ?secondPersonPreteritePluralForm ontolex:representation ?secondPersonPreteritePlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q442485, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectFirstPersonPluralForm .
    ?indicativePluperfectFirstPersonPluralForm ontolex:representation ?indicativePluperfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonImperativePluralForm .
    ?thirdPersonImperativePluralForm ontolex:representation ?thirdPersonImperativePlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q22716, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectThirdPersonSingularForm .
    ?indicativePerfectThirdPersonSingularForm ontolex:representation ?indicativePerfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativePresentPluralForm .
    ?imperativePresentPluralForm ontolex:representation ?imperativePresentPlural ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectThirdPersonActiveSingularForm .
    ?indicativePluperfectThirdPersonActiveSingularForm ontolex:representation ?indicativePluperfectThirdPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929074, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPresentSingularForm .
    ?indicativeThirdPersonPresentSingularForm ontolex:representation ?indicativeThirdPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonSingularForm .
    ?perfectSecondPersonSingularForm ontolex:representation ?perfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPreteritePluralActiveForm .
    ?indicativeThirdPersonPreteritePluralActiveForm ontolex:representation ?indicativeThirdPersonPreteritePluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q442485, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativePresentPluralActiveSingularForm .
    ?secondPersonImperativePresentPluralActiveSingularForm ontolex:representation ?secondPersonImperativePresentPluralActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q192613, wd:Q146786, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPresentSingularForm .
    ?secondPersonPresentSingularForm ontolex:representation ?secondPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectThirdPersonPluralForm .
    ?indicativePluperfectThirdPersonPluralForm ontolex:representation ?indicativePluperfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPreteriteSingularForm .
    ?secondPersonPreteriteSingularForm ontolex:representation ?secondPersonPreteriteSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q442485, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectFirstPersonPluralActiveForm .
    ?indicativePerfectFirstPersonPluralActiveForm ontolex:representation ?indicativePerfectFirstPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q21714344, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonPluralForm .
    ?perfectThirdPersonPluralForm ontolex:representation ?perfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPreteriteSingularForm .
    ?indicativeThirdPersonPreteriteSingularForm ontolex:representation ?indicativeThirdPersonPreteriteSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q442485, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectInfinitiveActiveForm .
    ?perfectInfinitiveActiveForm ontolex:representation ?perfectInfinitiveActive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q179230, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPresentActiveSingularForm .
    ?indicativeThirdPersonPresentActiveSingularForm ontolex:representation ?indicativeThirdPersonPresentActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q192613, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativePluralForm .
    ?imperativePluralForm ontolex:representation ?imperativePlural ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonFuturePluralForm .
    ?indicativeThirdPersonFuturePluralForm ontolex:representation ?indicativeThirdPersonFuturePlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q501405, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFuturePluralForm .
    ?thirdPersonFuturePluralForm ontolex:representation ?thirdPersonFuturePlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q501405, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonFutureSingularForm .
    ?indicativeThirdPersonFutureSingularForm ontolex:representation ?indicativeThirdPersonFutureSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q501405, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonImperativePresentActiveSingularForm .
    ?indicativeSecondPersonImperativePresentActiveSingularForm ontolex:representation ?indicativeSecondPersonImperativePresentActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q22716, wd:Q192613, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectSecondPersonActiveSingularForm .
    ?indicativePluperfectSecondPersonActiveSingularForm ontolex:representation ?indicativePluperfectSecondPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929049, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPreteriteActiveSingularForm .
    ?indicativeThirdPersonPreteriteActiveSingularForm ontolex:representation ?indicativeThirdPersonPreteriteActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q442485, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureFirstPersonPluralForm .
    ?futureFirstPersonPluralForm ontolex:representation ?futureFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectThirdPersonSingularForm .
    ?pluperfectThirdPersonSingularForm ontolex:representation ?pluperfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentInfinitiveActiveForm .
    ?presentInfinitiveActiveForm ontolex:representation ?presentInfinitiveActive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q179230, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectSecondPersonPluralForm .
    ?indicativePluperfectSecondPersonPluralForm ontolex:representation ?indicativePluperfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPreteritePluralForm .
    ?indicativeThirdPersonPreteritePluralForm ontolex:representation ?indicativeThirdPersonPreteritePlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q442485, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonFuturePluralForm .
    ?indicativeSecondPersonFuturePluralForm ontolex:representation ?indicativeSecondPersonFuturePlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q501405, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePreteriteFirstPersonPluralActiveForm .
    ?indicativePreteriteFirstPersonPluralActiveForm ontolex:representation ?indicativePreteriteFirstPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q442485, wd:Q21714344, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonFutureActiveSingularForm .
    ?indicativeSecondPersonFutureActiveSingularForm ontolex:representation ?indicativeSecondPersonFutureActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q501405, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPreteriteSingularForm .
    ?indicativeSecondPersonPreteriteSingularForm ontolex:representation ?indicativeSecondPersonPreteriteSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q442485, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectSecondPersonSingularForm .
    ?indicativePluperfectSecondPersonSingularForm ontolex:representation ?indicativePluperfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectSecondPersonPluralForm .
    ?pluperfectSecondPersonPluralForm ontolex:representation ?pluperfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectFirstPersonSingularForm .
    ?indicativePerfectFirstPersonSingularForm ontolex:representation ?indicativePerfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureFirstPersonSingularForm .
    ?futureFirstPersonSingularForm ontolex:representation ?futureFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeSingularForm .
    ?imperativeSingularForm ontolex:representation ?imperativeSingular ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeFirstPersonPluralForm .
    ?imperativeFirstPersonPluralForm ontolex:representation ?imperativeFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPresentSingularForm .
    ?indicativeFirstPersonPresentSingularForm ontolex:representation ?indicativeFirstPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFutureFirstPersonSingularForm .
    ?indicativeFutureFirstPersonSingularForm ontolex:representation ?indicativeFutureFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q501405, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPreteriteActiveSingularForm .
    ?indicativeSecondPersonPreteriteActiveSingularForm ontolex:representation ?indicativeSecondPersonPreteriteActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q442485, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectThirdPersonForm .
    ?pluperfectThirdPersonForm ontolex:representation ?pluperfectThirdPerson ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonFuturePluralActiveForm .
    ?indicativeSecondPersonFuturePluralActiveForm ontolex:representation ?indicativeSecondPersonFuturePluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q501405, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonPluralForm .
    ?perfectFirstPersonPluralForm ontolex:representation ?perfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFutureFirstPersonActiveSingularForm .
    ?indicativeFutureFirstPersonActiveSingularForm ontolex:representation ?indicativeFutureFirstPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q501405, wd:Q21714344, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPresentActiveSingularForm .
    ?indicativeFirstPersonPresentActiveSingularForm ontolex:representation ?indicativeFirstPersonPresentActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q192613, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPresentPluralForm .
    ?indicativeThirdPersonPresentPluralForm ontolex:representation ?indicativeThirdPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFutureForm .
    ?thirdPersonFutureForm ontolex:representation ?thirdPersonFuture ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectSecondPersonPluralActiveForm .
    ?indicativePerfectSecondPersonPluralActiveForm ontolex:representation ?indicativePerfectSecondPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929049, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?preteriteFirstPersonPluralForm .
    ?preteriteFirstPersonPluralForm ontolex:representation ?preteriteFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q442485, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonSingularForm .
    ?perfectFirstPersonSingularForm ontolex:representation ?perfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativePresentSingularForm .
    ?imperativePresentSingularForm ontolex:representation ?imperativePresentSingular ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectImperativeSingularForm .
    ?perfectImperativeSingularForm ontolex:representation ?perfectImperativeSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q22716, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectThirdPersonActiveSingularForm .
    ?indicativePerfectThirdPersonActiveSingularForm ontolex:representation ?indicativePerfectThirdPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929074, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonSingularForm .
    ?perfectThirdPersonSingularForm ontolex:representation ?perfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectFirstPersonActiveSingularForm .
    ?indicativePluperfectFirstPersonActiveSingularForm ontolex:representation ?indicativePluperfectFirstPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q21714344, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPresentPluralActiveForm .
    ?indicativeFirstPersonPresentPluralActiveForm ontolex:representation ?indicativeFirstPersonPresentPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q192613, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPresentForm .
    ?thirdPersonPresentForm ontolex:representation ?thirdPersonPresent ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectFirstPersonPluralActiveForm .
    ?indicativePluperfectFirstPersonPluralActiveForm ontolex:representation ?indicativePluperfectFirstPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q21714344, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPresentPluralActiveForm .
    ?indicativeThirdPersonPresentPluralActiveForm ontolex:representation ?indicativeThirdPersonPresentPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q192613, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPresentPluralForm .
    ?firstPersonPresentPluralForm ontolex:representation ?firstPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPresentPluralForm .
    ?thirdPersonPresentPluralForm ontolex:representation ?thirdPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectInfinitiveForm .
    ?perfectInfinitiveForm ontolex:representation ?perfectInfinitive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q179230 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPreteritePluralForm .
    ?thirdPersonPreteritePluralForm ontolex:representation ?thirdPersonPreteritePlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q442485, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectSecondPersonPluralForm .
    ?indicativePerfectSecondPersonPluralForm ontolex:representation ?indicativePerfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonFutureActiveSingularForm .
    ?indicativeThirdPersonFutureActiveSingularForm ontolex:representation ?indicativeThirdPersonFutureActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q501405, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectSecondPersonActiveSingularForm .
    ?indicativePerfectSecondPersonActiveSingularForm ontolex:representation ?indicativePerfectSecondPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q51929049, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonForm .
    ?perfectThirdPersonForm ontolex:representation ?perfectThirdPerson ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectFirstPersonPluralForm .
    ?indicativePerfectFirstPersonPluralForm ontolex:representation ?indicativePerfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativePresentActiveSingularForm .
    ?secondPersonImperativePresentActiveSingularForm ontolex:representation ?secondPersonImperativePresentActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q192613, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonFutureSingularForm .
    ?indicativeSecondPersonFutureSingularForm ontolex:representation ?indicativeSecondPersonFutureSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q501405, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectImperativePluralForm .
    ?perfectImperativePluralForm ontolex:representation ?perfectImperativePlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q22716, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePerfectFirstPersonActiveSingularForm .
    ?indicativePerfectFirstPersonActiveSingularForm ontolex:representation ?indicativePerfectFirstPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q625420, wd:Q21714344, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFuturePluralForm .
    ?secondPersonFuturePluralForm ontolex:representation ?secondPersonFuturePlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q501405, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFutureFirstPersonPluralForm .
    ?indicativeFutureFirstPersonPluralForm ontolex:representation ?indicativeFutureFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q501405, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectThirdPersonPluralForm .
    ?pluperfectThirdPersonPluralForm ontolex:representation ?pluperfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPresentPluralForm .
    ?indicativeFirstPersonPresentPluralForm ontolex:representation ?indicativeFirstPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPresentSingularForm .
    ?firstPersonPresentSingularForm ontolex:representation ?firstPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPresentSingularForm .
    ?thirdPersonPresentSingularForm ontolex:representation ?thirdPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectThirdPersonSingularForm .
    ?indicativePluperfectThirdPersonSingularForm ontolex:representation ?indicativePluperfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectFirstPersonSingularForm .
    ?indicativePluperfectFirstPersonSingularForm ontolex:representation ?indicativePluperfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPresentSingularForm .
    ?indicativeSecondPersonPresentSingularForm ontolex:representation ?indicativeSecondPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPresentPluralForm .
    ?secondPersonPresentPluralForm ontolex:representation ?secondPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPreteritePluralActiveForm .
    ?indicativeSecondPersonPreteritePluralActiveForm ontolex:representation ?indicativeSecondPersonPreteritePluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q442485, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?preteriteFirstPersonSingularForm .
    ?preteriteFirstPersonSingularForm ontolex:representation ?preteriteFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q442485, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePreteriteFirstPersonActiveSingularForm .
    ?indicativePreteriteFirstPersonActiveSingularForm ontolex:representation ?indicativePreteriteFirstPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q442485, wd:Q21714344, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonPluralForm .
    ?perfectSecondPersonPluralForm ontolex:representation ?perfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFutureSingularForm .
    ?thirdPersonFutureSingularForm ontolex:representation ?thirdPersonFutureSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q501405, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPreteriteForm .
    ?thirdPersonPreteriteForm ontolex:representation ?thirdPersonPreterite ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q442485 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPresentActiveSingularForm .
    ?indicativeSecondPersonPresentActiveSingularForm ontolex:representation ?indicativeSecondPersonPresentActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q192613, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPresentPluralForm .
    ?indicativeSecondPersonPresentPluralForm ontolex:representation ?indicativeSecondPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectSecondPersonPluralActiveForm .
    ?indicativePluperfectSecondPersonPluralActiveForm ontolex:representation ?indicativePluperfectSecondPersonPluralActive ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929049, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectSecondPersonSingularForm .
    ?pluperfectSecondPersonSingularForm ontolex:representation ?pluperfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveFirstPersonPreteriteIndicativeForm .
    ?singularActiveFirstPersonPreteriteIndicativeForm ontolex:representation ?singularActiveFirstPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q21714344, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePresentThirdPersonIndicativeForm .
    ?singularActivePresentThirdPersonIndicativeForm ontolex:representation ?singularActivePresentThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q192613, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPluperfectForm .
    ?pluralSecondPersonPluperfectForm ontolex:representation ?pluralSecondPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?preteriteThirdPersonForm .
    ?preteriteThirdPersonForm ontolex:representation ?preteriteThirdPerson ;
      wikibase:grammaticalFeature wd:Q442485, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPresentIndicativeForm .
    ?pluralSecondPersonPresentIndicativeForm ontolex:representation ?pluralSecondPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentThirdPersonSingularForm .
    ?indicativePresentThirdPersonSingularForm ontolex:representation ?indicativePresentThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFutureSecondPersonForm .
    ?singularFutureSecondPersonForm ontolex:representation ?singularFutureSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q501405, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentThirdPersonForm .
    ?singularPresentThirdPersonForm ontolex:representation ?singularPresentThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPerfectForm .
    ?pluralSecondPersonPerfectForm ontolex:representation ?pluralSecondPersonPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveThirdPersonPluperfectIndicativeForm .
    ?singularActiveThirdPersonPluperfectIndicativeForm ontolex:representation ?singularActiveThirdPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q51929074, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveSecondPersonPerfectIndicativeForm .
    ?singularActiveSecondPersonPerfectIndicativeForm ontolex:representation ?singularActiveSecondPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q51929049, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePresentSecondPersonIndicativeForm .
    ?singularActivePresentSecondPersonIndicativeForm ontolex:representation ?singularActivePresentSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q192613, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularImperativeForm .
    ?singularImperativeForm ontolex:representation ?singularImperative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentThirdPersonForm .
    ?presentThirdPersonForm ontolex:representation ?presentThirdPerson ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPluperfectIndicativeForm .
    ?singularFirstPersonPluperfectIndicativeForm ontolex:representation ?singularFirstPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPresentIndicativeForm .
    ?pluralFirstPersonPresentIndicativeForm ontolex:representation ?pluralFirstPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPluperfectForm .
    ?thirdPersonPluperfectForm ontolex:representation ?thirdPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveFutureThirdPersonIndicativeForm .
    ?singularActiveFutureThirdPersonIndicativeForm ontolex:representation ?singularActiveFutureThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q501405, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveFirstPersonFutureIndicativeForm .
    ?singularActiveFirstPersonFutureIndicativeForm ontolex:representation ?singularActiveFirstPersonFutureIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q21714344, wd:Q501405, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSecondPersonForm .
    ?singularPresentSecondPersonForm ontolex:representation ?singularPresentSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFutureThirdPersonForm .
    ?singularFutureThirdPersonForm ontolex:representation ?singularFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFutureSecondPersonForm .
    ?pluralFutureSecondPersonForm ontolex:representation ?pluralFutureSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q501405, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentThirdPersonForm .
    ?pluralPresentThirdPersonForm ontolex:representation ?pluralPresentThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentSecondPersonSingularForm .
    ?indicativePresentSecondPersonSingularForm ontolex:representation ?indicativePresentSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPreteriteThirdPersonIndicativeForm .
    ?singularPreteriteThirdPersonIndicativeForm ontolex:representation ?singularPreteriteThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q442485, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePreteriteSecondPersonSingularForm .
    ?indicativePreteriteSecondPersonSingularForm ontolex:representation ?indicativePreteriteSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q442485, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveFirstPersonPerfectIndicativeForm .
    ?singularActiveFirstPersonPerfectIndicativeForm ontolex:representation ?singularActiveFirstPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q21714344, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPluperfectIndicativeForm .
    ?pluralFirstPersonPluperfectIndicativeForm ontolex:representation ?pluralFirstPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonFutureForm .
    ?singularFirstPersonFutureForm ontolex:representation ?singularFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPresentIndicativeForm .
    ?singularFirstPersonPresentIndicativeForm ontolex:representation ?singularFirstPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentThirdPersonPluralForm .
    ?indicativePresentThirdPersonPluralForm ontolex:representation ?indicativePresentThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonImperativeForm .
    ?pluralFirstPersonImperativeForm ontolex:representation ?pluralFirstPersonImperative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPluperfectForm .
    ?singularThirdPersonPluperfectForm ontolex:representation ?singularThirdPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePreteriteThirdPersonPluralForm .
    ?indicativePreteriteThirdPersonPluralForm ontolex:representation ?indicativePreteriteThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q442485, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralPresentThirdPersonIndicativeForm .
    ?activePluralPresentThirdPersonIndicativeForm ontolex:representation ?activePluralPresentThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q192613, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPluperfectIndicativeForm .
    ?singularSecondPersonPluperfectIndicativeForm ontolex:representation ?singularSecondPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPresentIndicativeForm .
    ?singularThirdPersonPresentIndicativeForm ontolex:representation ?singularThirdPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSecondPersonForm .
    ?pluralPresentSecondPersonForm ontolex:representation ?pluralPresentSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentFirstPersonSingularForm .
    ?indicativePresentFirstPersonSingularForm ontolex:representation ?indicativePresentFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonForm .
    ?singularPresentFirstPersonForm ontolex:representation ?singularPresentFirstPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPerfectIndicativeForm .
    ?singularThirdPersonPerfectIndicativeForm ontolex:representation ?singularThirdPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralThirdPersonPluperfectIndicativeForm .
    ?activePluralThirdPersonPluperfectIndicativeForm ontolex:representation ?activePluralThirdPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q51929074, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFutureThirdPersonForm .
    ?pluralFutureThirdPersonForm ontolex:representation ?pluralFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralSecondPersonPerfectIndicativeForm .
    ?activePluralSecondPersonPerfectIndicativeForm ontolex:representation ?activePluralSecondPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q51929049, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralPresentSecondPersonIndicativeForm .
    ?activePluralPresentSecondPersonIndicativeForm ontolex:representation ?activePluralPresentSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q192613, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPreteriteThirdPersonIndicativeForm .
    ?pluralPreteriteThirdPersonIndicativeForm ontolex:representation ?pluralPreteriteThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q442485, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralFutureThirdPersonIndicativeForm .
    ?activePluralFutureThirdPersonIndicativeForm ontolex:representation ?activePluralFutureThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q501405, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonFutureForm .
    ?pluralFirstPersonFutureForm ontolex:representation ?pluralFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralFirstPersonFutureIndicativeForm .
    ?activePluralFirstPersonFutureIndicativeForm ontolex:representation ?activePluralFirstPersonFutureIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q21714344, wd:Q501405, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPluperfectForm .
    ?pluralThirdPersonPluperfectForm ontolex:representation ?pluralThirdPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPluperfectIndicativeForm .
    ?pluralSecondPersonPluperfectIndicativeForm ontolex:representation ?pluralSecondPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePresentFirstPersonIndicativeForm .
    ?singularActivePresentFirstPersonIndicativeForm ontolex:representation ?singularActivePresentFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q192613, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePreteriteSecondPersonPluralForm .
    ?indicativePreteriteSecondPersonPluralForm ontolex:representation ?indicativePreteriteSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q442485, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPresentIndicativeForm .
    ?pluralThirdPersonPresentIndicativeForm ontolex:representation ?pluralThirdPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPreteriteSecondPersonForm .
    ?singularPreteriteSecondPersonForm ontolex:representation ?singularPreteriteSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q442485, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPreteriteIndicativeForm .
    ?singularSecondPersonPreteriteIndicativeForm ontolex:representation ?singularSecondPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonForm .
    ?pluralPresentFirstPersonForm ontolex:representation ?pluralPresentFirstPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentThirdPersonIndicativeForm .
    ?singularPresentThirdPersonIndicativeForm ontolex:representation ?singularPresentThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPerfectIndicativeForm .
    ?pluralThirdPersonPerfectIndicativeForm ontolex:representation ?pluralThirdPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFutureSecondPersonIndicativeForm .
    ?singularFutureSecondPersonIndicativeForm ontolex:representation ?singularFutureSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q501405, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralFirstPersonPerfectIndicativeForm .
    ?activePluralFirstPersonPerfectIndicativeForm ontolex:representation ?activePluralFirstPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q21714344, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPluperfectForm .
    ?singularFirstPersonPluperfectForm ontolex:representation ?singularFirstPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePresentImperativeSecondPersonIndicativeForm .
    ?singularActivePresentImperativeSecondPersonIndicativeForm ontolex:representation ?singularActivePresentImperativeSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q192613, wd:Q22716, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveSecondPersonPluperfectIndicativeForm .
    ?singularActiveSecondPersonPluperfectIndicativeForm ontolex:representation ?singularActiveSecondPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q51929049, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonFutureIndicativeForm .
    ?pluralFirstPersonFutureIndicativeForm ontolex:representation ?pluralFirstPersonFutureIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q501405, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFutureThirdPersonIndicativeForm .
    ?singularFutureThirdPersonIndicativeForm ontolex:representation ?singularFutureThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q501405, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPerfectIndicativeForm .
    ?singularFirstPersonPerfectIndicativeForm ontolex:representation ?singularFirstPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPreteriteSecondPersonForm .
    ?pluralPreteriteSecondPersonForm ontolex:representation ?pluralPreteriteSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q442485, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePresentForm .
    ?infinitivePresentForm ontolex:representation ?infinitivePresent ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPreteriteIndicativeForm .
    ?pluralSecondPersonPreteriteIndicativeForm ontolex:representation ?pluralSecondPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentThirdPersonIndicativeForm .
    ?pluralPresentThirdPersonIndicativeForm ontolex:representation ?pluralPresentThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeInfinitivePerfectForm .
    ?activeInfinitivePerfectForm ontolex:representation ?activeInfinitivePerfect ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q179230, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFutureSecondPersonIndicativeForm .
    ?pluralFutureSecondPersonIndicativeForm ontolex:representation ?pluralFutureSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q501405, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSecondPersonIndicativeForm .
    ?singularPresentSecondPersonIndicativeForm ontolex:representation ?singularPresentSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePreteriteThirdPersonIndicativeForm .
    ?singularActivePreteriteThirdPersonIndicativeForm ontolex:representation ?singularActivePreteriteThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q442485, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPreteriteSecondPersonIndicativeForm .
    ?singularPreteriteSecondPersonIndicativeForm ontolex:representation ?singularPreteriteSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q442485, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentImperativeForm .
    ?singularPresentImperativeForm ontolex:representation ?singularPresentImperative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveThirdPersonPerfectIndicativeForm .
    ?singularActiveThirdPersonPerfectIndicativeForm ontolex:representation ?singularActiveThirdPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q51929074, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePreteriteThirdPersonSingularForm .
    ?indicativePreteriteThirdPersonSingularForm ontolex:representation ?indicativePreteriteThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q442485, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeInfinitivePresentForm .
    ?activeInfinitivePresentForm ontolex:representation ?activeInfinitivePresent ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q179230, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPreteriteThirdPersonForm .
    ?singularPreteriteThirdPersonForm ontolex:representation ?singularPreteriteThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q442485, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPreteriteIndicativeForm .
    ?pluralFirstPersonPreteriteIndicativeForm ontolex:representation ?pluralFirstPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePresentImperativeSecondPersonForm .
    ?singularActivePresentImperativeSecondPersonForm ontolex:representation ?singularActivePresentImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q192613, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPerfectForm .
    ?pluralFirstPersonPerfectForm ontolex:representation ?pluralFirstPersonPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePluralPresentImperativeSecondPersonForm .
    ?singularActivePluralPresentImperativeSecondPersonForm ontolex:representation ?singularActivePluralPresentImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q146786, wd:Q192613, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPluperfectForm .
    ?pluralFirstPersonPluperfectForm ontolex:representation ?pluralFirstPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActivePreteriteSecondPersonIndicativeForm .
    ?singularActivePreteriteSecondPersonIndicativeForm ontolex:representation ?singularActivePreteriteSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q442485, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralPresentFirstPersonIndicativeForm .
    ?activePluralPresentFirstPersonIndicativeForm ontolex:representation ?activePluralPresentFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentFirstPersonPluralForm .
    ?indicativePresentFirstPersonPluralForm ontolex:representation ?indicativePresentFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonIndicativeForm .
    ?singularPresentFirstPersonIndicativeForm ontolex:representation ?singularPresentFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralImperativeThirdPersonForm .
    ?pluralImperativeThirdPersonForm ontolex:representation ?pluralImperativeThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q22716, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonFutureIndicativeForm .
    ?singularFirstPersonFutureIndicativeForm ontolex:representation ?singularFirstPersonFutureIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q501405, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePerfectForm .
    ?infinitivePerfectForm ontolex:representation ?infinitivePerfect ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveFirstPersonPluperfectIndicativeForm .
    ?singularActiveFirstPersonPluperfectIndicativeForm ontolex:representation ?singularActiveFirstPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q21714344, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPerfectIndicativeForm .
    ?pluralFirstPersonPerfectIndicativeForm ontolex:representation ?pluralFirstPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularActiveFutureSecondPersonIndicativeForm .
    ?singularActiveFutureSecondPersonIndicativeForm ontolex:representation ?singularActiveFutureSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q501405, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFutureThirdPersonIndicativeForm .
    ?pluralFutureThirdPersonIndicativeForm ontolex:representation ?pluralFutureThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q501405, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPerfectIndicativeForm .
    ?singularSecondPersonPerfectIndicativeForm ontolex:representation ?singularSecondPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSecondPersonIndicativeForm .
    ?pluralPresentSecondPersonIndicativeForm ontolex:representation ?pluralPresentSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentImperativeForm .
    ?pluralPresentImperativeForm ontolex:representation ?pluralPresentImperative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPreteriteSecondPersonIndicativeForm .
    ?pluralPreteriteSecondPersonIndicativeForm ontolex:representation ?pluralPreteriteSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q442485, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPreteriteForm .
    ?pluralFirstPersonPreteriteForm ontolex:representation ?pluralFirstPersonPreterite ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q442485 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPreteriteThirdPersonForm .
    ?pluralPreteriteThirdPersonForm ontolex:representation ?pluralPreteriteThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q442485, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPreteriteIndicativeForm .
    ?singularFirstPersonPreteriteIndicativeForm ontolex:representation ?singularFirstPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPerfectForm .
    ?singularFirstPersonPerfectForm ontolex:representation ?singularFirstPersonPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPerfectForm .
    ?thirdPersonPerfectForm ontolex:representation ?thirdPersonPerfect ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularImperativePerfectForm .
    ?singularImperativePerfectForm ontolex:representation ?singularImperativePerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q22716, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralSecondPersonPluperfectIndicativeForm .
    ?activePluralSecondPersonPluperfectIndicativeForm ontolex:representation ?activePluralSecondPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q51929049, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPreteriteIndicativeForm .
    ?singularThirdPersonPreteriteIndicativeForm ontolex:representation ?singularThirdPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPerfectForm .
    ?singularThirdPersonPerfectForm ontolex:representation ?singularThirdPersonPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonIndicativeForm .
    ?pluralPresentFirstPersonIndicativeForm ontolex:representation ?pluralPresentFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralPreteriteThirdPersonIndicativeForm .
    ?activePluralPreteriteThirdPersonIndicativeForm ontolex:representation ?activePluralPreteriteThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q442485, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureThirdPersonForm .
    ?futureThirdPersonForm ontolex:representation ?futureThirdPerson ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralThirdPersonPerfectIndicativeForm .
    ?activePluralThirdPersonPerfectIndicativeForm ontolex:representation ?activePluralThirdPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q51929074, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPluperfectIndicativeForm .
    ?singularThirdPersonPluperfectIndicativeForm ontolex:representation ?singularThirdPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPerfectIndicativeForm .
    ?pluralSecondPersonPerfectIndicativeForm ontolex:representation ?pluralSecondPersonPerfectIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q625420, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPreteriteForm .
    ?singularFirstPersonPreteriteForm ontolex:representation ?singularFirstPersonPreterite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q442485 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralPresentImperativeSecondPersonForm .
    ?activePluralPresentImperativeSecondPersonForm ontolex:representation ?activePluralPresentImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q192613, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPluperfectForm .
    ?singularSecondPersonPluperfectForm ontolex:representation ?singularSecondPersonPluperfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q623742 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralPreteriteSecondPersonIndicativeForm .
    ?activePluralPreteriteSecondPersonIndicativeForm ontolex:representation ?activePluralPreteriteSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q442485, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralImperativePerfectForm .
    ?pluralImperativePerfectForm ontolex:representation ?pluralImperativePerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q22716, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPresentIndicativeForm .
    ?singularSecondPersonPresentIndicativeForm ontolex:representation ?singularSecondPersonPresentIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePresentSecondPersonPluralForm .
    ?indicativePresentSecondPersonPluralForm ontolex:representation ?indicativePresentSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q192613, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPerfectForm .
    ?singularSecondPersonPerfectForm ontolex:representation ?singularSecondPersonPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPreteriteIndicativeForm .
    ?pluralThirdPersonPreteriteIndicativeForm ontolex:representation ?pluralThirdPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q442485, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralFirstPersonPluperfectIndicativeForm .
    ?activePluralFirstPersonPluperfectIndicativeForm ontolex:representation ?activePluralFirstPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q21714344, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPerfectForm .
    ?pluralThirdPersonPerfectForm ontolex:representation ?pluralThirdPersonPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralFutureSecondPersonIndicativeForm .
    ?activePluralFutureSecondPersonIndicativeForm ontolex:representation ?activePluralFutureSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q501405, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralImperativeForm .
    ?pluralImperativeForm ontolex:representation ?pluralImperative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPluperfectIndicativeForm .
    ?pluralThirdPersonPluperfectIndicativeForm ontolex:representation ?pluralThirdPersonPluperfectIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q623742, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePluralFirstPersonPreteriteIndicativeForm .
    ?activePluralFirstPersonPreteriteIndicativeForm ontolex:representation ?activePluralFirstPersonPreteriteIndicative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q21714344, wd:Q442485, wd:Q682111 .
  }
}
