# tool: scribe-data
# All Punjabi (Q58635) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verbs
  ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveDefinite
  ?intransitivePhaseBasicPhase
  ?singularPassiveFirstPersonFuture
  ?intransitivePhaseBasicPhaseDirectGerund
  ?singularFeminineFirstPerson
  ?singularIntransitivePhaseBasicPhasePassiveFirstPersonSubjunctive
  ?intransitivePhaseBasicPhasePassivePluralFutureThirdPerson
  ?pluralMasculine
  ?intransitivePhaseBasicPhaseObliqueGerund
  ?pluralFirstPersonMasculine
  ?singularIntransitivePhaseBasicPhasePassiveFirstPersonFuture
  ?singularSubjunctiveSecondPerson
  ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPersonDefinite
  ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveSecondPersonDefinite
  ?singularFirstPersonMasculine
  ?intransitivePhaseBasicPhasePluralFuture
  ?conjunctiveParticipleIntransitivePhaseBasicPhaseAdverbial
  ?intransitivePhaseBasicPhasePassiveDirectGerund
  ?pluralFeminineFirstPerson
  ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctiveMasculineDefinite
  ?pluralSecondPerson
  ?intransitivePhaseBasicPhasePassiveObliqueGerund
  ?intransitivePhaseBasicPhaseGerundLocative
  ?pluralSubjunctiveSecondPerson
  ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPerson
  ?intransitivePhaseBasicPhasePluralFutureSecondPerson
  ?singularIntransitivePhaseBasicPhaseFutureThirdPerson
  ?intransitivePhaseBasicPhasePassivePluralSubjunctiveThirdPerson
  ?intransitivePhaseBasicPhasePluralSubjunctiveThirdPerson
  ?conjunctiveParticiple
  ?singularIntransitivePhaseBasicPhaseImperativeSecondPerson
  ?intransitivePhaseBasicPhasePassivePluralFirstPersonSubjunctive
  ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctive
  ?conjunctiveParticipleIntransitivePhaseBasicPhase
  ?passiveDirectGerund
  ?intransitivePhaseBasicPhasePassivePluralFirstPersonFuture
  ?intransitivePhaseBasicPhasePluralFirstPersonFuture
  ?intransitivePhaseBasicPhaseAblativeGerund
  ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineSecondPersonDefinite
  ?singularIntransitivePhaseBasicPhaseFuture
  ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveSecondPerson
  ?singularIntransitivePhaseBasicPhasePassiveFutureThirdPerson
  ?intransitivePhaseBasicPhaseObliqueDirectGerund
  ?singularMasculineThirdPerson
  ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPerson
  ?singularSecondPerson
  ?pluralFirstPerson
  ?intransitivePhaseBasicPhasePassivePluralFutureSecondPerson
  ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineThirdPersonDefinite
  ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctive
  ?singularIntransitivePhaseBasicPhaseFirstPersonFuture
  ?intransitivePhaseBasicPhasePluralMasculineSecondPerson
  ?singularSubjunctiveThirdPerson
  ?intransitivePhaseBasicPhasePluralFeminineFirstPersonSubjunctiveDefinite
  ?singularIntransitivePhaseBasicPhaseFeminineFirstPersonSubjunctiveDefinite
  ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineSecondPersonDefinite
  ?pluralSubjunctiveThirdPerson
  ?pluralFirstPersonSubjunctive
  ?singularImperativeSecondPerson
  ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPersonDefinite
  ?singularFirstPersonSubjunctive
  ?singularFirstPersonFuture
  ?singularIntransitivePhaseBasicPhaseFutureSecondPerson
  ?intransitivePhaseBasicPhasePassivePluralSubjunctiveSecondPerson
  ?directGerund
  ?intransitivePhaseBasicPhasePluralSubjunctiveSecondPerson
  ?intransitivePhaseBasicPhasePluralFutureThirdPerson
  ?intransitivePhase
  ?singularFirstPerson
  ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveMasculineDefinite
  ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineThirdPersonDefinite
  ?singularFeminineThirdPerson
  ?intransitivePhaseBasicPhaseAdverbialAbsoluteConstruction
  ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveThirdPersonDefinite
  ?singularIntransitivePhaseBasicPhasePassiveFutureSecondPerson
  ?singularIntransitivePhaseBasicPhaseSubjunctiveSecondPerson
  ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveThirdPerson
  ?singularIntransitivePhaseBasicPhaseFirstPersonMasculineFuture
  ?intransitivePhaseBasicPhasePluralImperativeSecondPerson
  ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveSecondPersonDefinite
  ?obliqueGerund
  ?singularThirdPerson

WHERE {
  ?lexeme dct:language wd:Q58635 ;
  wikibase:lexicalCategory wd:Q24905 ;
  wikibase:lemma ?verbs .
    
  # Note: We need to filter for pnb to remove shahmukhi (pnb) words.
  FILTER(lang(?verbs) = "pnb")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q21714344, wd:Q473746, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseForm .
    ?intransitivePhaseBasicPhaseForm ontolex:representation ?intransitivePhaseBasicPhase ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPassiveFirstPersonFutureForm .
    ?singularPassiveFirstPersonFutureForm ontolex:representation ?singularPassiveFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1194697, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseDirectGerundForm .
    ?intransitivePhaseBasicPhaseDirectGerundForm ontolex:representation ?intransitivePhaseBasicPhaseDirectGerund ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1751855, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineFirstPersonForm .
    ?singularFeminineFirstPersonForm ontolex:representation ?singularFeminineFirstPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhasePassiveFirstPersonSubjunctiveForm .
    ?singularIntransitivePhaseBasicPhasePassiveFirstPersonSubjunctiveForm ontolex:representation ?singularIntransitivePhaseBasicPhasePassiveFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassivePluralFutureThirdPersonForm .
    ?intransitivePhaseBasicPhasePassivePluralFutureThirdPersonForm ontolex:representation ?intransitivePhaseBasicPhasePassivePluralFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q146786, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralMasculineForm .
    ?pluralMasculineForm ontolex:representation ?pluralMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseObliqueGerundForm .
    ?intransitivePhaseBasicPhaseObliqueGerundForm ontolex:representation ?intransitivePhaseBasicPhaseObliqueGerund ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1233197, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonMasculineForm .
    ?pluralFirstPersonMasculineForm ontolex:representation ?pluralFirstPersonMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhasePassiveFirstPersonFutureForm .
    ?singularIntransitivePhaseBasicPhasePassiveFirstPersonFutureForm ontolex:representation ?singularIntransitivePhaseBasicPhasePassiveFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSubjunctiveSecondPersonForm .
    ?singularSubjunctiveSecondPersonForm ontolex:representation ?singularSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPersonDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPersonDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPersonDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q473746, wd:Q51929074, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveSecondPersonDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveSecondPersonDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveSecondPersonDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1775415, wd:Q473746, wd:Q51929049, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonMasculineForm .
    ?singularFirstPersonMasculineForm ontolex:representation ?singularFirstPersonMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFutureForm .
    ?intransitivePhaseBasicPhasePluralFutureForm ontolex:representation ?intransitivePhaseBasicPhasePluralFuture ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conjunctiveParticipleIntransitivePhaseBasicPhaseAdverbialForm .
    ?conjunctiveParticipleIntransitivePhaseBasicPhaseAdverbialForm ontolex:representation ?conjunctiveParticipleIntransitivePhaseBasicPhaseAdverbial ;
      wikibase:grammaticalFeature wd:Q113133303, wd:Q113330736, wd:Q113330960, wd:Q380012 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassiveDirectGerundForm .
    ?intransitivePhaseBasicPhasePassiveDirectGerundForm ontolex:representation ?intransitivePhaseBasicPhasePassiveDirectGerund ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q1751855, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineFirstPersonForm .
    ?pluralFeminineFirstPersonForm ontolex:representation ?pluralFeminineFirstPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctiveMasculineDefiniteForm .
    ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctiveMasculineDefiniteForm ontolex:representation ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctiveMasculineDefinite ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q21714344, wd:Q473746, wd:Q499327, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonForm .
    ?pluralSecondPersonForm ontolex:representation ?pluralSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassiveObliqueGerundForm .
    ?intransitivePhaseBasicPhasePassiveObliqueGerundForm ontolex:representation ?intransitivePhaseBasicPhasePassiveObliqueGerund ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q1233197, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseGerundLocativeForm .
    ?intransitivePhaseBasicPhaseGerundLocativeForm ontolex:representation ?intransitivePhaseBasicPhaseGerundLocative ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1923028, wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSubjunctiveSecondPersonForm .
    ?pluralSubjunctiveSecondPersonForm ontolex:representation ?pluralSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPersonForm .
    ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q1775415, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFutureSecondPersonForm .
    ?intransitivePhaseBasicPhasePluralFutureSecondPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralFutureSecondPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q501405, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFutureThirdPersonForm .
    ?singularIntransitivePhaseBasicPhaseFutureThirdPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassivePluralSubjunctiveThirdPersonForm .
    ?intransitivePhaseBasicPhasePassivePluralSubjunctiveThirdPersonForm ontolex:representation ?intransitivePhaseBasicPhasePassivePluralSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q146786, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralSubjunctiveThirdPersonForm .
    ?intransitivePhaseBasicPhasePluralSubjunctiveThirdPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conjunctiveParticipleForm .
    ?conjunctiveParticipleForm ontolex:representation ?conjunctiveParticiple ;
      wikibase:grammaticalFeature wd:Q113133303 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseImperativeSecondPersonForm .
    ?singularIntransitivePhaseBasicPhaseImperativeSecondPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhaseImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassivePluralFirstPersonSubjunctiveForm .
    ?intransitivePhaseBasicPhasePassivePluralFirstPersonSubjunctiveForm ontolex:representation ?intransitivePhaseBasicPhasePassivePluralFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q146786, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctiveForm .
    ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctiveForm ontolex:representation ?intransitivePhaseBasicPhasePluralFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conjunctiveParticipleIntransitivePhaseBasicPhaseForm .
    ?conjunctiveParticipleIntransitivePhaseBasicPhaseForm ontolex:representation ?conjunctiveParticipleIntransitivePhaseBasicPhase ;
      wikibase:grammaticalFeature wd:Q113133303, wd:Q113330736, wd:Q113330960 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveDirectGerundForm .
    ?passiveDirectGerundForm ontolex:representation ?passiveDirectGerund ;
      wikibase:grammaticalFeature wd:Q1194697, wd:Q1751855, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassivePluralFirstPersonFutureForm .
    ?intransitivePhaseBasicPhasePassivePluralFirstPersonFutureForm ontolex:representation ?intransitivePhaseBasicPhasePassivePluralFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q146786, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFirstPersonFutureForm .
    ?intransitivePhaseBasicPhasePluralFirstPersonFutureForm ontolex:representation ?intransitivePhaseBasicPhasePluralFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseAblativeGerundForm .
    ?intransitivePhaseBasicPhaseAblativeGerundForm ontolex:representation ?intransitivePhaseBasicPhaseAblativeGerund ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q156986, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineSecondPersonDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineSecondPersonDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineSecondPersonDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q473746, wd:Q499327, wd:Q51929049, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFutureForm .
    ?singularIntransitivePhaseBasicPhaseFutureForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveSecondPersonForm .
    ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveSecondPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhasePassiveFutureThirdPersonForm .
    ?singularIntransitivePhaseBasicPhasePassiveFutureThirdPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhasePassiveFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseObliqueDirectGerundForm .
    ?intransitivePhaseBasicPhaseObliqueDirectGerundForm ontolex:representation ?intransitivePhaseBasicPhaseObliqueDirectGerund ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1233197, wd:Q1751855, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineThirdPersonForm .
    ?singularMasculineThirdPersonForm ontolex:representation ?singularMasculineThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPersonForm .
    ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhaseSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonForm .
    ?singularSecondPersonForm ontolex:representation ?singularSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonForm .
    ?pluralFirstPersonForm ontolex:representation ?pluralFirstPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassivePluralFutureSecondPersonForm .
    ?intransitivePhaseBasicPhasePassivePluralFutureSecondPersonForm ontolex:representation ?intransitivePhaseBasicPhasePassivePluralFutureSecondPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q146786, wd:Q501405, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineThirdPersonDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineThirdPersonDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseSubjunctiveMasculineThirdPersonDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q473746, wd:Q499327, wd:Q51929074, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveForm .
    ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFirstPersonFutureForm .
    ?singularIntransitivePhaseBasicPhaseFirstPersonFutureForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralMasculineSecondPersonForm .
    ?intransitivePhaseBasicPhasePluralMasculineSecondPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralMasculineSecondPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q499327, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSubjunctiveThirdPersonForm .
    ?singularSubjunctiveThirdPersonForm ontolex:representation ?singularSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFeminineFirstPersonSubjunctiveDefiniteForm .
    ?intransitivePhaseBasicPhasePluralFeminineFirstPersonSubjunctiveDefiniteForm ontolex:representation ?intransitivePhaseBasicPhasePluralFeminineFirstPersonSubjunctiveDefinite ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q1775415, wd:Q21714344, wd:Q473746, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFeminineFirstPersonSubjunctiveDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseFeminineFirstPersonSubjunctiveDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFeminineFirstPersonSubjunctiveDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1775415, wd:Q21714344, wd:Q473746, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineSecondPersonDefiniteForm .
    ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineSecondPersonDefiniteForm ontolex:representation ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineSecondPersonDefinite ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q473746, wd:Q499327, wd:Q51929049, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSubjunctiveThirdPersonForm .
    ?pluralSubjunctiveThirdPersonForm ontolex:representation ?pluralSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonSubjunctiveForm .
    ?pluralFirstPersonSubjunctiveForm ontolex:representation ?pluralFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularImperativeSecondPersonForm .
    ?singularImperativeSecondPersonForm ontolex:representation ?singularImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPersonDefiniteForm .
    ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPersonDefiniteForm ontolex:representation ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveThirdPersonDefinite ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q1775415, wd:Q473746, wd:Q51929074, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonSubjunctiveForm .
    ?singularFirstPersonSubjunctiveForm ontolex:representation ?singularFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonFutureForm .
    ?singularFirstPersonFutureForm ontolex:representation ?singularFirstPersonFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFutureSecondPersonForm .
    ?singularIntransitivePhaseBasicPhaseFutureSecondPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFutureSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q501405, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePassivePluralSubjunctiveSecondPersonForm .
    ?intransitivePhaseBasicPhasePassivePluralSubjunctiveSecondPersonForm ontolex:representation ?intransitivePhaseBasicPhasePassivePluralSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q146786, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directGerundForm .
    ?directGerundForm ontolex:representation ?directGerund ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralSubjunctiveSecondPersonForm .
    ?intransitivePhaseBasicPhasePluralSubjunctiveSecondPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFutureThirdPersonForm .
    ?intransitivePhaseBasicPhasePluralFutureThirdPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseForm .
    ?intransitivePhaseForm ontolex:representation ?intransitivePhase ;
      wikibase:grammaticalFeature wd:Q113330736 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonForm .
    ?singularFirstPersonForm ontolex:representation ?singularFirstPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveMasculineDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveMasculineDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFirstPersonSubjunctiveMasculineDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q21714344, wd:Q473746, wd:Q499327, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineThirdPersonDefiniteForm .
    ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineThirdPersonDefiniteForm ontolex:representation ?intransitivePhaseBasicPhasePluralSubjunctiveMasculineThirdPersonDefinite ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q473746, wd:Q499327, wd:Q51929074, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineThirdPersonForm .
    ?singularFeminineThirdPersonForm ontolex:representation ?singularFeminineThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhaseAdverbialAbsoluteConstructionForm .
    ?intransitivePhaseBasicPhaseAdverbialAbsoluteConstructionForm ontolex:representation ?intransitivePhaseBasicPhaseAdverbialAbsoluteConstruction ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q380012, wd:Q4669807 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveThirdPersonDefiniteForm .
    ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveThirdPersonDefiniteForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFeminineSubjunctiveThirdPersonDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1775415, wd:Q473746, wd:Q51929074, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhasePassiveFutureSecondPersonForm .
    ?singularIntransitivePhaseBasicPhasePassiveFutureSecondPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhasePassiveFutureSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q501405, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseSubjunctiveSecondPersonForm .
    ?singularIntransitivePhaseBasicPhaseSubjunctiveSecondPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhaseSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveThirdPersonForm .
    ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveThirdPersonForm ontolex:representation ?singularIntransitivePhaseBasicPhasePassiveSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q1194697, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIntransitivePhaseBasicPhaseFirstPersonMasculineFutureForm .
    ?singularIntransitivePhaseBasicPhaseFirstPersonMasculineFutureForm ontolex:representation ?singularIntransitivePhaseBasicPhaseFirstPersonMasculineFuture ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q113330736, wd:Q113330960, wd:Q21714344, wd:Q499327, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralImperativeSecondPersonForm .
    ?intransitivePhaseBasicPhasePluralImperativeSecondPersonForm ontolex:representation ?intransitivePhaseBasicPhasePluralImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveSecondPersonDefiniteForm .
    ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveSecondPersonDefiniteForm ontolex:representation ?intransitivePhaseBasicPhasePluralFeminineSubjunctiveSecondPersonDefinite ;
      wikibase:grammaticalFeature wd:Q113330736, wd:Q113330960, wd:Q146786, wd:Q1775415, wd:Q473746, wd:Q51929049, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueGerundForm .
    ?obliqueGerundForm ontolex:representation ?obliqueGerund ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonForm .
    ?singularThirdPersonForm ontolex:representation ?singularThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074 .
  }
}
