# tool: scribe-data
# All German (Q188) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?propernoun
  ?nominativeSingular
  ?nominativeSingular
  ?genitiveSingular
  ?genitiveSingular
  ?dativeSingular
  ?dativeSingular
  ?accusativeSingular
  ?accusativeSingular
  ?genitiveFeminineSingular
  ?genitiveFeminineSingular
  ?genitiveMasculineSingular
  ?genitiveMasculineSingular
  ?dativeFeminineSingular
  ?dativeFeminineSingular
  ?dativeMasculineSingular
  ?dativeMasculineSingular
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q188 ;
      wikibase:lexicalCategory wd:Q147276 ;
      wikibase:lemma ?propernoun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularForm .
    ?genitiveFeminineSingularForm ontolex:representation ?genitiveFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularForm .
    ?genitiveFeminineSingularForm ontolex:representation ?genitiveFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineSingularForm .
    ?genitiveMasculineSingularForm ontolex:representation ?genitiveMasculineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineSingularForm .
    ?genitiveMasculineSingularForm ontolex:representation ?genitiveMasculineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularForm .
    ?dativeFeminineSingularForm ontolex:representation ?dativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularForm .
    ?dativeFeminineSingularForm ontolex:representation ?dativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineSingularForm .
    ?dativeMasculineSingularForm ontolex:representation ?dativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineSingularForm .
    ?dativeMasculineSingularForm ontolex:representation ?dativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q499327, wd:Q110786 .
  }
}
