# tool: scribe-data
# All Latin (Q397) proper_nouns (Q147276) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?proper_nouns
  ?masculineAblativePlural
  ?feminineAblativeSingular
  ?pluralGenitive
  ?locativeFeminineSingular
  ?masculineAccusativeSingular
  ?locativeFemininePlural
  ?masculineDativeSingular
  ?feminineAblativePlural
  ?vocativePlural
  ?masculinePluralNominative
  ?feminineAccusativeSingular
  ?feminineDativeSingular
  ?vocativeFeminineSingular
  ?masculineLocativeSingular
  ?femininePluralNominative
  ?locativeSingular
  ?masculinePluralGenitive
  ?vocativeFemininePlural
  ?nominativeSingular
  ?genitiveSingular
  ?masculineLocativePlural
  ?femininePluralGenitive
  ?accusative
  ?vocativeSingular
  ?ablativePlural
  ?dativeSingular
  ?pluralAccusative
  ?masculineVocativePlural
  ?masculinePluralAccusative
  ?femininePluralAccusative
  ?masculineNominativeSingular
  ?masculineVocativeSingular
  ?pluralDative
  ?masculinePluralDative
  ?feminineNominativeSingular
  ?femininePluralDative
  ?masculineGenitiveSingular
  ?ablativeSingular
  ?nominative
  ?accusativeSingular
  ?pluralNominative
  ?feminineGenitiveSingular
  ?vocative
  ?masculineAblativeSingular
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q147276 ;
      wikibase:lemma ?proper_nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAblativePluralForm .
    ?masculineAblativePluralForm ontolex:representation ?masculineAblativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAblativeSingularForm .
    ?feminineAblativeSingularForm ontolex:representation ?feminineAblativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralGenitiveForm .
    ?pluralGenitiveForm ontolex:representation ?pluralGenitive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularForm .
    ?locativeFeminineSingularForm ontolex:representation ?locativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralForm .
    ?locativeFemininePluralForm ontolex:representation ?locativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDativeSingularForm .
    ?masculineDativeSingularForm ontolex:representation ?masculineDativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAblativePluralForm .
    ?feminineAblativePluralForm ontolex:representation ?feminineAblativePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativePluralForm .
    ?vocativePluralForm ontolex:representation ?vocativePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralNominativeForm .
    ?masculinePluralNominativeForm ontolex:representation ?masculinePluralNominative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeSingularForm .
    ?feminineAccusativeSingularForm ontolex:representation ?feminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineDativeSingularForm .
    ?feminineDativeSingularForm ontolex:representation ?feminineDativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFeminineSingularForm .
    ?vocativeFeminineSingularForm ontolex:representation ?vocativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineLocativeSingularForm .
    ?masculineLocativeSingularForm ontolex:representation ?masculineLocativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralNominativeForm .
    ?femininePluralNominativeForm ontolex:representation ?femininePluralNominative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralGenitiveForm .
    ?masculinePluralGenitiveForm ontolex:representation ?masculinePluralGenitive ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFemininePluralForm .
    ?vocativeFemininePluralForm ontolex:representation ?vocativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineLocativePluralForm .
    ?masculineLocativePluralForm ontolex:representation ?masculineLocativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralGenitiveForm .
    ?femininePluralGenitiveForm ontolex:representation ?femininePluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeSingularForm .
    ?vocativeSingularForm ontolex:representation ?vocativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralForm .
    ?ablativePluralForm ontolex:representation ?ablativePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAccusativeForm .
    ?pluralAccusativeForm ontolex:representation ?pluralAccusative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineVocativePluralForm .
    ?masculineVocativePluralForm ontolex:representation ?masculineVocativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q185077, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralAccusativeForm .
    ?masculinePluralAccusativeForm ontolex:representation ?masculinePluralAccusative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralAccusativeForm .
    ?femininePluralAccusativeForm ontolex:representation ?femininePluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineNominativeSingularForm .
    ?masculineNominativeSingularForm ontolex:representation ?masculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineVocativeSingularForm .
    ?masculineVocativeSingularForm ontolex:representation ?masculineVocativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDativeForm .
    ?pluralDativeForm ontolex:representation ?pluralDative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralDativeForm .
    ?masculinePluralDativeForm ontolex:representation ?masculinePluralDative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineNominativeSingularForm .
    ?feminineNominativeSingularForm ontolex:representation ?feminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralDativeForm .
    ?femininePluralDativeForm ontolex:representation ?femininePluralDative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveSingularForm .
    ?masculineGenitiveSingularForm ontolex:representation ?masculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeSingularForm .
    ?ablativeSingularForm ontolex:representation ?ablativeSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralNominativeForm .
    ?pluralNominativeForm ontolex:representation ?pluralNominative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineGenitiveSingularForm .
    ?feminineGenitiveSingularForm ontolex:representation ?feminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeForm .
    ?vocativeForm ontolex:representation ?vocative ;
      wikibase:grammaticalFeature wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAblativeSingularForm .
    ?masculineAblativeSingularForm ontolex:representation ?masculineAblativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q156986, wd:Q110786 .
  }
}
