# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?dativeMasculineInanimatePlural
  ?dativeFeminineSingularComparative
  ?dativeFemininePluralPositive
  ?dativeMasculineInanimatePluralComparative
  ?vocativeMasculineInanimateSingularComparative
  ?vocativeMasculineInanimatePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
      wikibase:lexicalCategory wd:Q34698 ;
      wikibase:lemma ?adjective ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineInanimatePluralForm .
    ?dativeMasculineInanimatePluralForm ontolex:representation ?dativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularComparativeForm .
    ?dativeFeminineSingularComparativeForm ontolex:representation ?dativeFeminineSingularComparative ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePluralPositiveForm .
    ?dativeFemininePluralPositiveForm ontolex:representation ?dativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineInanimatePluralComparativeForm .
    ?dativeMasculineInanimatePluralComparativeForm ontolex:representation ?dativeMasculineInanimatePluralComparative ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q52943434, wd:Q146786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimateSingularComparativeForm .
    ?vocativeMasculineInanimateSingularComparativeForm ontolex:representation ?vocativeMasculineInanimateSingularComparative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimatePluralPositiveForm .
    ?vocativeMasculineInanimatePluralPositiveForm ontolex:representation ?vocativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }
}
