# tool: scribe-data
# All Hebrew (Q9288) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?commonSingular
  ?presentSingular
  ?presentPlural
  ?presentConstruct
  ?firstPersonSingular
  ?firstPersonPlural
  ?femininePresentSingular
  ?femininePresentPlural
  ?masculineImperativePlural
  ?masculinePresentSingular
  ?masculinePresentPlural
  ?presentSingularConstruct
  ?presentPluralConstruct
  ?pastFirstPersonSingular
  ?pastFirstPersonPlural
  ?pastThirdPersonPlural
  ?futureFirstPersonSingular
  ?futureFirstPersonPlural
  ?feminineImperativeSecondPersonSingular
  ?feminineImperativeSecondPersonPlural
  ?femininePresentSingularConstruct
  ?femininePresentPluralConstruct
  ?femininePastSecondPersonSingular
  ?femininePastSecondPersonPlural
  ?femininePastThirdPersonSingular
  ?femininePastThirdPersonPlural
  ?feminineFutureSecondPersonSingular
  ?feminineFutureSecondPersonPlural
  ?feminineFutureThirdPersonSingular
  ?feminineFutureThirdPersonPlural
  ?masculineImperativeSecondPersonSingular
  ?masculineImperativeSecondPersonPlural
  ?masculinePresentSingularConstruct
  ?masculinePresentPluralConstruct
  ?masculinePastSecondPersonSingular
  ?masculinePastSecondPersonPlural
  ?masculinePastThirdPersonSingular
  ?masculinePastThirdPersonPlural
  ?masculineFutureSecondPersonSingular
  ?masculineFutureSecondPersonPlural
  ?masculineFutureThirdPersonSingular
  ?masculineFutureThirdPersonPlural
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q9288 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?commonSingularForm .
    ?commonSingularForm ontolex:representation ?commonSingular ;
      wikibase:grammaticalFeature wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentSingularForm .
    ?presentSingularForm ontolex:representation ?presentSingular ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPluralForm .
    ?presentPluralForm ontolex:representation ?presentPlural ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentConstructForm .
    ?presentConstructForm ontolex:representation ?presentConstruct ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonSingularForm .
    ?firstPersonSingularForm ontolex:representation ?firstPersonSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralForm .
    ?firstPersonPluralForm ontolex:representation ?firstPersonPlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePresentSingularForm .
    ?femininePresentSingularForm ontolex:representation ?femininePresentSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePresentPluralForm .
    ?femininePresentPluralForm ontolex:representation ?femininePresentPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineImperativePluralForm .
    ?masculineImperativePluralForm ontolex:representation ?masculineImperativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q22716, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePresentSingularForm .
    ?masculinePresentSingularForm ontolex:representation ?masculinePresentSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePresentPluralForm .
    ?masculinePresentPluralForm ontolex:representation ?masculinePresentPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentSingularConstructForm .
    ?presentSingularConstructForm ontolex:representation ?presentSingularConstruct ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPluralConstructForm .
    ?presentPluralConstructForm ontolex:representation ?presentPluralConstruct ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFirstPersonSingularForm .
    ?pastFirstPersonSingularForm ontolex:representation ?pastFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q1994301, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFirstPersonPluralForm .
    ?pastFirstPersonPluralForm ontolex:representation ?pastFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q1994301, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastThirdPersonPluralForm .
    ?pastThirdPersonPluralForm ontolex:representation ?pastThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1994301, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureFirstPersonSingularForm .
    ?futureFirstPersonSingularForm ontolex:representation ?futureFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureFirstPersonPluralForm .
    ?futureFirstPersonPluralForm ontolex:representation ?futureFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineImperativeSecondPersonSingularForm .
    ?feminineImperativeSecondPersonSingularForm ontolex:representation ?feminineImperativeSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q22716, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineImperativeSecondPersonPluralForm .
    ?feminineImperativeSecondPersonPluralForm ontolex:representation ?feminineImperativeSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q22716, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePresentSingularConstructForm .
    ?femininePresentSingularConstructForm ontolex:representation ?femininePresentSingularConstruct ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q192613, wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePresentPluralConstructForm .
    ?femininePresentPluralConstructForm ontolex:representation ?femininePresentPluralConstruct ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q192613, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePastSecondPersonSingularForm .
    ?femininePastSecondPersonSingularForm ontolex:representation ?femininePastSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1994301, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePastSecondPersonPluralForm .
    ?femininePastSecondPersonPluralForm ontolex:representation ?femininePastSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1994301, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePastThirdPersonSingularForm .
    ?femininePastThirdPersonSingularForm ontolex:representation ?femininePastThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1994301, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePastThirdPersonPluralForm .
    ?femininePastThirdPersonPluralForm ontolex:representation ?femininePastThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1994301, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureSecondPersonSingularForm .
    ?feminineFutureSecondPersonSingularForm ontolex:representation ?feminineFutureSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureSecondPersonPluralForm .
    ?feminineFutureSecondPersonPluralForm ontolex:representation ?feminineFutureSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureThirdPersonSingularForm .
    ?feminineFutureThirdPersonSingularForm ontolex:representation ?feminineFutureThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureThirdPersonPluralForm .
    ?feminineFutureThirdPersonPluralForm ontolex:representation ?feminineFutureThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineImperativeSecondPersonSingularForm .
    ?masculineImperativeSecondPersonSingularForm ontolex:representation ?masculineImperativeSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q22716, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineImperativeSecondPersonPluralForm .
    ?masculineImperativeSecondPersonPluralForm ontolex:representation ?masculineImperativeSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q22716, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePresentSingularConstructForm .
    ?masculinePresentSingularConstructForm ontolex:representation ?masculinePresentSingularConstruct ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q192613, wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePresentPluralConstructForm .
    ?masculinePresentPluralConstructForm ontolex:representation ?masculinePresentPluralConstruct ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q192613, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastSecondPersonSingularForm .
    ?masculinePastSecondPersonSingularForm ontolex:representation ?masculinePastSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastSecondPersonPluralForm .
    ?masculinePastSecondPersonPluralForm ontolex:representation ?masculinePastSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastThirdPersonSingularForm .
    ?masculinePastThirdPersonSingularForm ontolex:representation ?masculinePastThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastThirdPersonPluralForm .
    ?masculinePastThirdPersonPluralForm ontolex:representation ?masculinePastThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureSecondPersonSingularForm .
    ?masculineFutureSecondPersonSingularForm ontolex:representation ?masculineFutureSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureSecondPersonPluralForm .
    ?masculineFutureSecondPersonPluralForm ontolex:representation ?masculineFutureSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureThirdPersonSingularForm .
    ?masculineFutureThirdPersonSingularForm ontolex:representation ?masculineFutureThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureThirdPersonPluralForm .
    ?masculineFutureThirdPersonPluralForm ontolex:representation ?masculineFutureThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929074, wd:Q146786 .
  }
}
