# tool: scribe-data
# All Czech (Q9056) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculineSingularPassiveParticiple
  ?masculineSingularActiveParticiple
  ?masculineAnimateSingularCombinedPastParticiple
  ?masculineAnimatePluralCombinedPastParticiple
  ?neuterSingularCombinedPastParticiple
  ?neuterPluralCombinedPastParticiple

WHERE {
  ?lexeme dct:language wd:Q9056 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularPassiveParticipleForm .
    ?masculineSingularPassiveParticipleForm ontolex:representation ?masculineSingularPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularActiveParticipleForm .
    ?masculineSingularActiveParticipleForm ontolex:representation ?masculineSingularActiveParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786, wd:Q72249355 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimateSingularCombinedPastParticipleForm .
    ?masculineAnimateSingularCombinedPastParticipleForm ontolex:representation ?masculineAnimateSingularCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q110786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimatePluralCombinedPastParticipleForm .
    ?masculineAnimatePluralCombinedPastParticipleForm ontolex:representation ?masculineAnimatePluralCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q146786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterSingularCombinedPastParticipleForm .
    ?neuterSingularCombinedPastParticipleForm ontolex:representation ?neuterSingularCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q110786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralCombinedPastParticipleForm .
    ?neuterPluralCombinedPastParticipleForm ontolex:representation ?neuterPluralCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q12717679 .
  }
}
