# tool: scribe-data
# All Spanish (Q1321) adjectives (Q34698) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjectives
  ?secondPersonMasculinePlural
  ?neuterPlural
  ?secondPersonSingular
  ?thirdPersonFeminineSingular
  ?thirdPersonMasculineSingular
  ?thirdPersonFemininePlural
  ?plural
  ?masculinePlural
  ?masculineFeminineSingular
  ?masculineFirstPersonPluralSingular
  ?masculineSuperlativeSingular
  ?femininePlural
  ?thirdPersonMasculinePlural
  ?firstPersonFemininePluralSingular
  ?masculineSuperlativePlural
  ?masculineFemininePlural
  ?neuterSingular
  ?singular
  ?masculineSingular
  ?masculineFirstPersonSingular
  ?feminineSingular
  ?secondPersonPlural
  ?masculineFirstPersonPlural
  ?firstPersonFeminineSingular
  ?firstPersonFemininePlural
  ?secondPersonMasculineSingular
  ?secondPersonFeminineSingular
  ?superlativeFeminineSingular
  ?secondPersonFemininePlural
  ?superlativeFemininePlural
  ?superlativeSingularFeminine
  ?superlativeSingularMasculine
  ?superlativePluralFeminine
  ?superlativePluralMasculine
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q1321 ;
      wikibase:lexicalCategory wd:Q34698 ;
      wikibase:lemma ?adjectives ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePluralForm .
    ?secondPersonMasculinePluralForm ontolex:representation ?secondPersonMasculinePlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralForm .
    ?neuterPluralForm ontolex:representation ?neuterPlural ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSingularForm .
    ?secondPersonSingularForm ontolex:representation ?secondPersonSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFeminineSingularForm .
    ?thirdPersonFeminineSingularForm ontolex:representation ?thirdPersonFeminineSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineSingularForm .
    ?thirdPersonMasculineSingularForm ontolex:representation ?thirdPersonMasculineSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFemininePluralForm .
    ?thirdPersonFemininePluralForm ontolex:representation ?thirdPersonFemininePlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralForm .
    ?masculinePluralForm ontolex:representation ?masculinePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFeminineSingularForm .
    ?masculineFeminineSingularForm ontolex:representation ?masculineFeminineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFirstPersonPluralSingularForm .
    ?masculineFirstPersonPluralSingularForm ontolex:representation ?masculineFirstPersonPluralSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q21714344, wd:Q146786, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSuperlativeSingularForm .
    ?masculineSuperlativeSingularForm ontolex:representation ?masculineSuperlativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1817208, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralForm .
    ?femininePluralForm ontolex:representation ?femininePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePluralForm .
    ?thirdPersonMasculinePluralForm ontolex:representation ?thirdPersonMasculinePlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonFemininePluralSingularForm .
    ?firstPersonFemininePluralSingularForm ontolex:representation ?firstPersonFemininePluralSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1775415, wd:Q146786, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSuperlativePluralForm .
    ?masculineSuperlativePluralForm ontolex:representation ?masculineSuperlativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1817208, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFemininePluralForm .
    ?masculineFemininePluralForm ontolex:representation ?masculineFemininePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterSingularForm .
    ?neuterSingularForm ontolex:representation ?neuterSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularForm .
    ?masculineSingularForm ontolex:representation ?masculineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFirstPersonSingularForm .
    ?masculineFirstPersonSingularForm ontolex:representation ?masculineFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularForm .
    ?feminineSingularForm ontolex:representation ?feminineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPluralForm .
    ?secondPersonPluralForm ontolex:representation ?secondPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFirstPersonPluralForm .
    ?masculineFirstPersonPluralForm ontolex:representation ?masculineFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonFeminineSingularForm .
    ?firstPersonFeminineSingularForm ontolex:representation ?firstPersonFeminineSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonFemininePluralForm .
    ?firstPersonFemininePluralForm ontolex:representation ?firstPersonFemininePlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculineSingularForm .
    ?secondPersonMasculineSingularForm ontolex:representation ?secondPersonMasculineSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFeminineSingularForm .
    ?secondPersonFeminineSingularForm ontolex:representation ?secondPersonFeminineSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeFeminineSingularForm .
    ?superlativeFeminineSingularForm ontolex:representation ?superlativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFemininePluralForm .
    ?secondPersonFemininePluralForm ontolex:representation ?secondPersonFemininePlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeFemininePluralForm .
    ?superlativeFemininePluralForm ontolex:representation ?superlativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeSingularFeminineForm .
    ?superlativeSingularFeminineForm ontolex:representation ?superlativeSingularFeminine ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeSingularMasculineForm .
    ?superlativeSingularMasculineForm ontolex:representation ?superlativeSingularMasculine ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q110786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativePluralFeminineForm .
    ?superlativePluralFeminineForm ontolex:representation ?superlativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativePluralMasculineForm .
    ?superlativePluralMasculineForm ontolex:representation ?superlativePluralMasculine ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q146786, wd:Q499327 .
  }
}
