# tool: scribe-data
# All Arabic (Q13955) proper_nouns (Q147276) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?proper_nouns
  ?definiteMasculineAccusativeSingular
  ?definiteFemininePausalSingular
  ?masculineAccusativeSingular
  ?femininePausalDual
  ?definiteMasculineGenitiveSingular
  ?masculinePausalSingular
  ?masculineNominativeSingular
  ?feminineSingular
  ?feminineAccusativeSingular
  ?definiteFeminineNominativeSingular
  ?definiteMasculinePausalSingular
  ?femininePausalSingular
  ?indefiniteFemininePausalSingular
  ?feminineNominativeSingular
  ?masculineGenitiveSingular
  ?nominative
  ?genitive
  ?accusative
  ?definiteMasculineNominativeSingular
  ?definiteFeminineAccusativeSingular
  ?indefiniteMasculinePausalSingular
  ?feminineGenitiveSingular
  ?definiteFeminineGenitiveSingular
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q13955 ;
      wikibase:lexicalCategory wd:Q147276 ;
      wikibase:lemma ?proper_nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineAccusativeSingularForm .
    ?definiteMasculineAccusativeSingularForm ontolex:representation ?definiteMasculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFemininePausalSingularForm .
    ?definiteFemininePausalSingularForm ontolex:representation ?definiteFemininePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePausalDualForm .
    ?femininePausalDualForm ontolex:representation ?femininePausalDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q117262361, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineGenitiveSingularForm .
    ?definiteMasculineGenitiveSingularForm ontolex:representation ?definiteMasculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePausalSingularForm .
    ?masculinePausalSingularForm ontolex:representation ?masculinePausalSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineNominativeSingularForm .
    ?masculineNominativeSingularForm ontolex:representation ?masculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularForm .
    ?feminineSingularForm ontolex:representation ?feminineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeSingularForm .
    ?feminineAccusativeSingularForm ontolex:representation ?feminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineNominativeSingularForm .
    ?definiteFeminineNominativeSingularForm ontolex:representation ?definiteFeminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculinePausalSingularForm .
    ?definiteMasculinePausalSingularForm ontolex:representation ?definiteMasculinePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePausalSingularForm .
    ?femininePausalSingularForm ontolex:representation ?femininePausalSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePausalSingularForm .
    ?indefiniteFemininePausalSingularForm ontolex:representation ?indefiniteFemininePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineNominativeSingularForm .
    ?feminineNominativeSingularForm ontolex:representation ?feminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveSingularForm .
    ?masculineGenitiveSingularForm ontolex:representation ?masculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineNominativeSingularForm .
    ?definiteMasculineNominativeSingularForm ontolex:representation ?definiteMasculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineAccusativeSingularForm .
    ?definiteFeminineAccusativeSingularForm ontolex:representation ?definiteFeminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculinePausalSingularForm .
    ?indefiniteMasculinePausalSingularForm ontolex:representation ?indefiniteMasculinePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineGenitiveSingularForm .
    ?feminineGenitiveSingularForm ontolex:representation ?feminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineGenitiveSingularForm .
    ?definiteFeminineGenitiveSingularForm ontolex:representation ?definiteFeminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146233, wd:Q110786 .
  }
}
