# tool: scribe-data
# All Persian (Q9168) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verbs
  ?thirdPersonSubjunctivePresentSingular
  ?thirdPersonPlural
  ?perfectThirdPersonPresentPlural
  ?secondPersonSubjunctivePresentPlural
  ?perfectFirstPersonPresentSingular
  ?indicativeSecondPersonPastPlural
  ?indicativeFirstPersonPastPlural
  ?indicativeSecondPersonPastSingular
  ?subjunctiveFirstPersonPresentSingular
  ?secondPersonSingular
  ?secondPersonSubjunctivePresentSingular
  ?firstPersonSingular
  ?perfectThirdPersonPresentSingular
  ?secondPersonPlural
  ?firstPersonPlural
  ?indicativeThirdPersonPastPlural
  ?indicativeFirstPersonPastSingular
  ?thirdPersonSubjunctivePresentPlural
  ?perfectSecondPersonPresentPlural
  ?perfectFirstPersonPresentPlural
  ?perfectSecondPersonPresentSingular
  ?indicativeThirdPersonPastSingular
  ?thirdPersonSingular
  ?subjunctiveFirstPersonPresentPlural
  ?indicativePastSecondPersonSingular
  ?subjunctivePluralFirstPersonPresent
  ?presentFirstPersonSingularSubjunctive
  ?pluralAoristFirstPersonIndicative
  ?pluralPresentSubjunctiveSecondPerson
  ?singularPresentSubjunctiveSecondPerson
  ?pluralPresentSecondPersonPerfect
  ?singularAoristFirstPersonIndicative
  ?singularPresentSecondPersonPerfect
  ?pluralAoristSecondPersonIndicative
  ?pluralPresentThirdPersonPerfect
  ?pluralSecondPersonPresentPerfect
  ?singularPresentThirdPersonPerfect
  ?singularAoristSecondPersonIndicative
  ?presentThirdPersonSingularSubjunctive
  ?singularSecondPersonPresentPerfect
  ?presentSecondPersonPluralSubjunctive
  ?pluralFirstPersonPresentPerfect
  ?singularSecondPerson
  ?pluralSecondPerson
  ?presentPerfectSecondPersonSingular
  ?singularFirstPersonPresentPerfect
  ?singularAoristThirdPersonIndicative
  ?pluralAoristThirdPersonIndicative
  ?indicativePastThirdPersonPlural
  ?pluralSecondPersonPastIndicative
  ?pluralPastFirstPersonIndicative
  ?presentPerfectThirdPersonPlural
  ?singularSecondPersonPastIndicative
  ?singularFirstPerson
  ?subjunctiveSingularSecondPersonPresent
  ?pluralFirstPerson
  ?singularPastFirstPersonIndicative
  ?presentPerfectFirstPersonSingular
  ?pluralPastSecondPersonIndicative
  ?pluralFirstPersonPastIndicative
  ?presentFirstPersonPluralSubjunctive
  ?singularPastSecondPersonIndicative
  ?indicativePastThirdPersonSingular
  ?singularFirstPersonPastIndicative
  ?subjunctivePluralSecondPersonPresent
  ?pluralPastThirdPersonIndicative
  ?pluralPresentSubjunctiveThirdPerson
  ?singularPastThirdPersonIndicative
  ?singularPresentSubjunctiveThirdPerson
  ?pluralPresentFirstPersonSubjunctive
  ?singularPresentFirstPersonSubjunctive
  ?presentSecondPersonSingularSubjunctive
  ?pluralThirdPersonPresentPerfect
  ?indicativePastFirstPersonPlural
  ?singularThirdPersonPresentPerfect
  ?singularThirdPersonPastIndicative
  ?presentPerfectSecondPersonPlural
  ?presentThirdPersonPluralSubjunctive
  ?subjunctiveSingularThirdPersonPresent
  ?indicativePastSecondPersonPlural
  ?pluralThirdPersonPastIndicative
  ?pluralThirdPerson
  ?pluralPresentFirstPersonPerfect
  ?singularThirdPerson
  ?subjunctiveSingularFirstPersonPresent
  ?presentPerfectThirdPersonSingular
  ?singularPresentFirstPersonPerfect
  ?presentPerfectFirstPersonPlural
  ?indicativePastFirstPersonSingular
  ?subjunctivePluralThirdPersonPresent
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q9168 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verbs ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSubjunctivePresentSingularForm .
    ?thirdPersonSubjunctivePresentSingularForm ontolex:representation ?thirdPersonSubjunctivePresentSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q473746, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPluralForm .
    ?thirdPersonPluralForm ontolex:representation ?thirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonPresentPluralForm .
    ?perfectThirdPersonPresentPluralForm ontolex:representation ?perfectThirdPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSubjunctivePresentPluralForm .
    ?secondPersonSubjunctivePresentPluralForm ontolex:representation ?secondPersonSubjunctivePresentPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q473746, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonPresentSingularForm .
    ?perfectFirstPersonPresentSingularForm ontolex:representation ?perfectFirstPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPastPluralForm .
    ?indicativeSecondPersonPastPluralForm ontolex:representation ?indicativeSecondPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPastPluralForm .
    ?indicativeFirstPersonPastPluralForm ontolex:representation ?indicativeFirstPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonPastSingularForm .
    ?indicativeSecondPersonPastSingularForm ontolex:representation ?indicativeSecondPersonPastSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveFirstPersonPresentSingularForm .
    ?subjunctiveFirstPersonPresentSingularForm ontolex:representation ?subjunctiveFirstPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q21714344, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSingularForm .
    ?secondPersonSingularForm ontolex:representation ?secondPersonSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSubjunctivePresentSingularForm .
    ?secondPersonSubjunctivePresentSingularForm ontolex:representation ?secondPersonSubjunctivePresentSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q473746, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonSingularForm .
    ?firstPersonSingularForm ontolex:representation ?firstPersonSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonPresentSingularForm .
    ?perfectThirdPersonPresentSingularForm ontolex:representation ?perfectThirdPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPluralForm .
    ?secondPersonPluralForm ontolex:representation ?secondPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralForm .
    ?firstPersonPluralForm ontolex:representation ?firstPersonPlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPastPluralForm .
    ?indicativeThirdPersonPastPluralForm ontolex:representation ?indicativeThirdPersonPastPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q1994301, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPastSingularForm .
    ?indicativeFirstPersonPastSingularForm ontolex:representation ?indicativeFirstPersonPastSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSubjunctivePresentPluralForm .
    ?thirdPersonSubjunctivePresentPluralForm ontolex:representation ?thirdPersonSubjunctivePresentPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q473746, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonPresentPluralForm .
    ?perfectSecondPersonPresentPluralForm ontolex:representation ?perfectSecondPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonPresentPluralForm .
    ?perfectFirstPersonPresentPluralForm ontolex:representation ?perfectFirstPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonPresentSingularForm .
    ?perfectSecondPersonPresentSingularForm ontolex:representation ?perfectSecondPersonPresentSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q192613, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonPastSingularForm .
    ?indicativeThirdPersonPastSingularForm ontolex:representation ?indicativeThirdPersonPastSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSingularForm .
    ?thirdPersonSingularForm ontolex:representation ?thirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveFirstPersonPresentPluralForm .
    ?subjunctiveFirstPersonPresentPluralForm ontolex:representation ?subjunctiveFirstPersonPresentPlural ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q21714344, wd:Q192613, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastSecondPersonSingularForm .
    ?indicativePastSecondPersonSingularForm ontolex:representation ?indicativePastSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctivePluralFirstPersonPresentForm .
    ?subjunctivePluralFirstPersonPresentForm ontolex:representation ?subjunctivePluralFirstPersonPresent ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q146786, wd:Q21714344, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentFirstPersonSingularSubjunctiveForm .
    ?presentFirstPersonSingularSubjunctiveForm ontolex:representation ?presentFirstPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q21714344, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAoristFirstPersonIndicativeForm .
    ?pluralAoristFirstPersonIndicativeForm ontolex:representation ?pluralAoristFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q216497, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSubjunctiveSecondPersonForm .
    ?pluralPresentSubjunctiveSecondPersonForm ontolex:representation ?pluralPresentSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSubjunctiveSecondPersonForm .
    ?singularPresentSubjunctiveSecondPersonForm ontolex:representation ?singularPresentSubjunctiveSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q473746, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSecondPersonPerfectForm .
    ?pluralPresentSecondPersonPerfectForm ontolex:representation ?pluralPresentSecondPersonPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929049, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAoristFirstPersonIndicativeForm .
    ?singularAoristFirstPersonIndicativeForm ontolex:representation ?singularAoristFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q216497, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSecondPersonPerfectForm .
    ?singularPresentSecondPersonPerfectForm ontolex:representation ?singularPresentSecondPersonPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929049, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAoristSecondPersonIndicativeForm .
    ?pluralAoristSecondPersonIndicativeForm ontolex:representation ?pluralAoristSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q216497, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentThirdPersonPerfectForm .
    ?pluralPresentThirdPersonPerfectForm ontolex:representation ?pluralPresentThirdPersonPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929074, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPresentPerfectForm .
    ?pluralSecondPersonPresentPerfectForm ontolex:representation ?pluralSecondPersonPresentPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q1240211 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentThirdPersonPerfectForm .
    ?singularPresentThirdPersonPerfectForm ontolex:representation ?singularPresentThirdPersonPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929074, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAoristSecondPersonIndicativeForm .
    ?singularAoristSecondPersonIndicativeForm ontolex:representation ?singularAoristSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q216497, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentThirdPersonSingularSubjunctiveForm .
    ?presentThirdPersonSingularSubjunctiveForm ontolex:representation ?presentThirdPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q51929074, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPresentPerfectForm .
    ?singularSecondPersonPresentPerfectForm ontolex:representation ?singularSecondPersonPresentPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q1240211 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentSecondPersonPluralSubjunctiveForm .
    ?presentSecondPersonPluralSubjunctiveForm ontolex:representation ?presentSecondPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q51929049, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPresentPerfectForm .
    ?pluralFirstPersonPresentPerfectForm ontolex:representation ?pluralFirstPersonPresentPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q1240211 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonForm .
    ?singularSecondPersonForm ontolex:representation ?singularSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonForm .
    ?pluralSecondPersonForm ontolex:representation ?pluralSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectSecondPersonSingularForm .
    ?presentPerfectSecondPersonSingularForm ontolex:representation ?presentPerfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1240211, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPresentPerfectForm .
    ?singularFirstPersonPresentPerfectForm ontolex:representation ?singularFirstPersonPresentPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q1240211 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAoristThirdPersonIndicativeForm .
    ?singularAoristThirdPersonIndicativeForm ontolex:representation ?singularAoristThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q216497, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAoristThirdPersonIndicativeForm .
    ?pluralAoristThirdPersonIndicativeForm ontolex:representation ?pluralAoristThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q216497, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastThirdPersonPluralForm .
    ?indicativePastThirdPersonPluralForm ontolex:representation ?indicativePastThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPastIndicativeForm .
    ?pluralSecondPersonPastIndicativeForm ontolex:representation ?pluralSecondPersonPastIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q1994301, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPastFirstPersonIndicativeForm .
    ?pluralPastFirstPersonIndicativeForm ontolex:representation ?pluralPastFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1994301, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectThirdPersonPluralForm .
    ?presentPerfectThirdPersonPluralForm ontolex:representation ?presentPerfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1240211, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPastIndicativeForm .
    ?singularSecondPersonPastIndicativeForm ontolex:representation ?singularSecondPersonPastIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q1994301, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonForm .
    ?singularFirstPersonForm ontolex:representation ?singularFirstPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveSingularSecondPersonPresentForm .
    ?subjunctiveSingularSecondPersonPresentForm ontolex:representation ?subjunctiveSingularSecondPersonPresent ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q110786, wd:Q51929049, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonForm .
    ?pluralFirstPersonForm ontolex:representation ?pluralFirstPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastFirstPersonIndicativeForm .
    ?singularPastFirstPersonIndicativeForm ontolex:representation ?singularPastFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectFirstPersonSingularForm .
    ?presentPerfectFirstPersonSingularForm ontolex:representation ?presentPerfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q1240211, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPastSecondPersonIndicativeForm .
    ?pluralPastSecondPersonIndicativeForm ontolex:representation ?pluralPastSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1994301, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPastIndicativeForm .
    ?pluralFirstPersonPastIndicativeForm ontolex:representation ?pluralFirstPersonPastIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q1994301, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentFirstPersonPluralSubjunctiveForm .
    ?presentFirstPersonPluralSubjunctiveForm ontolex:representation ?presentFirstPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q21714344, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastSecondPersonIndicativeForm .
    ?singularPastSecondPersonIndicativeForm ontolex:representation ?singularPastSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastThirdPersonSingularForm .
    ?indicativePastThirdPersonSingularForm ontolex:representation ?indicativePastThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPastIndicativeForm .
    ?singularFirstPersonPastIndicativeForm ontolex:representation ?singularFirstPersonPastIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q1994301, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctivePluralSecondPersonPresentForm .
    ?subjunctivePluralSecondPersonPresentForm ontolex:representation ?subjunctivePluralSecondPersonPresent ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q146786, wd:Q51929049, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPastThirdPersonIndicativeForm .
    ?pluralPastThirdPersonIndicativeForm ontolex:representation ?pluralPastThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1994301, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSubjunctiveThirdPersonForm .
    ?pluralPresentSubjunctiveThirdPersonForm ontolex:representation ?pluralPresentSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastThirdPersonIndicativeForm .
    ?singularPastThirdPersonIndicativeForm ontolex:representation ?singularPastThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSubjunctiveThirdPersonForm .
    ?singularPresentSubjunctiveThirdPersonForm ontolex:representation ?singularPresentSubjunctiveThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q473746, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonSubjunctiveForm .
    ?pluralPresentFirstPersonSubjunctiveForm ontolex:representation ?pluralPresentFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonSubjunctiveForm .
    ?singularPresentFirstPersonSubjunctiveForm ontolex:representation ?singularPresentFirstPersonSubjunctive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentSecondPersonSingularSubjunctiveForm .
    ?presentSecondPersonSingularSubjunctiveForm ontolex:representation ?presentSecondPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q51929049, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPresentPerfectForm .
    ?pluralThirdPersonPresentPerfectForm ontolex:representation ?pluralThirdPersonPresentPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q1240211 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastFirstPersonPluralForm .
    ?indicativePastFirstPersonPluralForm ontolex:representation ?indicativePastFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPresentPerfectForm .
    ?singularThirdPersonPresentPerfectForm ontolex:representation ?singularThirdPersonPresentPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q1240211 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPastIndicativeForm .
    ?singularThirdPersonPastIndicativeForm ontolex:representation ?singularThirdPersonPastIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q1994301, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectSecondPersonPluralForm .
    ?presentPerfectSecondPersonPluralForm ontolex:representation ?presentPerfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1240211, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentThirdPersonPluralSubjunctiveForm .
    ?presentThirdPersonPluralSubjunctiveForm ontolex:representation ?presentThirdPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q51929074, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveSingularThirdPersonPresentForm .
    ?subjunctiveSingularThirdPersonPresentForm ontolex:representation ?subjunctiveSingularThirdPersonPresent ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q110786, wd:Q51929074, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastSecondPersonPluralForm .
    ?indicativePastSecondPersonPluralForm ontolex:representation ?indicativePastSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonPastIndicativeForm .
    ?pluralThirdPersonPastIndicativeForm ontolex:representation ?pluralThirdPersonPastIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074, wd:Q1994301, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonForm .
    ?pluralThirdPersonForm ontolex:representation ?pluralThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonPerfectForm .
    ?pluralPresentFirstPersonPerfectForm ontolex:representation ?pluralPresentFirstPersonPerfect ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonForm .
    ?singularThirdPersonForm ontolex:representation ?singularThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveSingularFirstPersonPresentForm .
    ?subjunctiveSingularFirstPersonPresentForm ontolex:representation ?subjunctiveSingularFirstPersonPresent ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q110786, wd:Q21714344, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectThirdPersonSingularForm .
    ?presentPerfectThirdPersonSingularForm ontolex:representation ?presentPerfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1240211, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonPerfectForm .
    ?singularPresentFirstPersonPerfectForm ontolex:representation ?singularPresentFirstPersonPerfect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectFirstPersonPluralForm .
    ?presentPerfectFirstPersonPluralForm ontolex:representation ?presentPerfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q1240211, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastFirstPersonSingularForm .
    ?indicativePastFirstPersonSingularForm ontolex:representation ?indicativePastFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctivePluralThirdPersonPresentForm .
    ?subjunctivePluralThirdPersonPresentForm ontolex:representation ?subjunctivePluralThirdPersonPresent ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q146786, wd:Q51929074, wd:Q192613 .
  }
}
