# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?singular
  ?passiveParticiple
  ?performativeFirstPersonSingular
  ?masculineActivePastDual
  ?masculineActivePastSecondPersonSingular
  ?commonActivePastSecondPersonDual

WHERE {
  ?lexeme dct:language wd:Q13955 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
    ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
      wikibase:grammaticalFeature wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?performativeFirstPersonSingularForm .
    ?performativeFirstPersonSingularForm ontolex:representation ?performativeFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q124351233, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineActivePastDualForm .
    ?masculineActivePastDualForm ontolex:representation ?masculineActivePastDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q1994301, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineActivePastSecondPersonSingularForm .
    ?masculineActivePastSecondPersonSingularForm ontolex:representation ?masculineActivePastSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q1994301, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?commonActivePastSecondPersonDualForm .
    ?commonActivePastSecondPersonDualForm ontolex:representation ?commonActivePastSecondPersonDual ;
      wikibase:grammaticalFeature wd:Q1305037, wd:Q1317831, wd:Q1994301, wd:Q51929049, wd:Q110022 .
  }
}
