# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verbs
  ?secondPersonMasculineImperativePluralActive
  ?thirdPersonMasculineActivePerformativeDual
  ?thirdPersonSubjunctiveFeminineActiveFiilMudariSingular
  ?secondPersonImperativeFeminineActiveSingular
  ?thirdPersonMasculineActivePerformativeSingular
  ?thirdPersonMasculinePastSingular
  ?firstPersonPastPluralActive
  ?secondPersonMasculinePastActiveSingular
  ?thirdPersonFeminineActivePerformativeSingular
  ?firstPersonPastActiveSingular
  ?firstPersonPluralActivePerformative
  ?indicativeFirstPersonFiilMudariSingular
  ?perfectFirstPersonActiveSingular
  ?secondPersonImperativeFemininePluralActive
  ?indicativeThirdPersonFeminineActiveFiilMudariDual
  ?indefiniteThirdPersonMasculinePastSingular
  ?indicativeFirstPersonPluralActiveFiilMudari
  ?secondPersonPastFemininePluralActive
  ?perfectSecondPersonMasculineActiveSingular
  ?secondPersonMasculinePerformativePassiveSingular
  ?thirdPersonPastFeminineActiveSingular
  ?indicativePluperfectThirdPersonActiveSingular
  ?secondPersonFemininePluralActivePerformative
  ?thirdPersonPastFeminineActiveDual
  ?secondPersonActivePerformativeDual
  ?indicativeSecondPersonFemininePluralActiveFiilMudari
  ?secondPersonImperativeActiveDual
  ?secondPersonMasculinePluralActivePerformative
  ?indicativeSecondPersonMasculineActiveFiilMudariSingular
  ?firstPersonPerformativePassiveSingular
  ?indicativeSecondPersonFeminineActiveFiilMudariSingular
  ?secondPersonSubjunctivePluralActiveFiilMudari
  ?thirdPersonFeminineActivePerformativeDual
  ?past
  ?secondPersonMasculinePastPluralActive
  ?thirdPersonMasculinePluralActivePerformative
  ?firstPersonFiilMudariSingular
  ?subjunctiveFirstPersonPluralActiveFiilMudari
  ?firstPersonPerformativeSingular
  ?thirdPersonMasculineSingular
  ?indicativeThirdPersonMasculineActiveFiilMudariDual
  ?thirdPersonMasculineSubjunctivePluralActiveFiilMudari
  ?indicativeThirdPersonMasculinePerformativeSingular
  ?firstPersonActiveFiilMudariSingular
  ?thirdPersonMasculinePastPluralActive
  ?thirdPersonMasculineSubjunctiveActiveFiilMudariSingular
  ?secondPersonMasculineImperativeActiveSingular
  ?masculinePlural
  ?thirdPersonMasculineSubjunctiveActiveFiilMudariDual
  ?secondPersonPastFeminineActiveSingular
  ?thirdPersonMasculinePastActiveDual
  ?femininePlural
  ?indicativeFirstPersonActiveFiilMudariSingular
  ?passiveParticiple
  ?masculinePastActiveDual
  ?thirdPersonMasculineActiveFiilMudariSingular
  ?thirdPersonMasculinePerformativeSingular
  ?secondPersonFemininePerformativePassiveSingular
  ?singular
  ?perfectSecondPersonFeminineActiveSingular
  ?indicativeSecondPersonMasculinePluralActiveFiilMudari
  ?secondPersonPastActiveCommonDual
  ?indicativeThirdPersonMasculineActiveFiilMudariSingular
  ?indicativeSecondPersonActiveFiilMudariDual
  ?indicativeThirdPersonFeminineActiveFiilMudariSingular
  ?secondPersonSubjunctiveFemininePluralActiveFiilMudari
  ?secondPersonSubjunctiveActiveFiilMudariDual
  ?secondPersonFeminineActivePerformativeSingular
  ?secondPersonSubjunctiveFeminineActiveFiilMudariSingular
  ?thirdPersonSubjunctiveFeminineActiveFiilMudariDual
  ?secondPersonMasculineSubjunctivePluralActiveFiilMudari
  ?thirdPersonPastFeminineSingular
  ?thirdPersonPastFemininePluralActive
  ?secondPersonMasculineActivePerformativeSingular
  ?subjunctiveFirstPersonActiveFiilMudariSingular
  ?thirdPersonFemininePluralActivePerformative
  ?thirdPersonSubjunctiveFemininePluralActiveFiilMudari
  ?firstPersonActivePerformativeSingular
  ?dualThirdPersonPerformativeActiveMasculine
  ?fiilMudariDualThirdPersonIndicativeMasculine
  ?fiilMudariSingularThirdPersonIndicativeFeminine
  ?fiilMudariPluralFirstPersonIndicative
  ?fiilMudariPluralSecondPersonIndicativeFeminine
  ?singularThirdPersonPerformativeActiveFeminine
  ?fiilMudariSingularThirdPersonIndicativeMasculine
  ?dualSecondPersonPerformativeActive
  ?dualThirdPersonPerformativeActiveFeminine
  ?singularSecondPersonPerformativeActiveMasculine
  ?fiilMudariSingularFirstPersonIndicative
  ?fiilMudariSingularSecondPersonIndicativeFeminine
  ?singularSecondPersonPerformativeActiveFeminine
  ?fiilMudariDualSecondPersonIndicative
  ?pluralFirstPersonPerformativeActive
  ?fiilMudariPluralSecondPersonIndicativeMasculine
  ?fiilMudariDualThirdPersonIndicativeFeminine
  ?fiilMudariSingularSecondPersonIndicativeMasculine
  ?singularFirstPersonPerformativeActive
  ?pluralSecondPersonPerformativeActiveMasculine
  ?singularThirdPersonPerformativeActiveMasculine
  ?pluralSecondPersonPerformativeActiveFeminine
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q13955 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verbs ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculineImperativePluralActiveForm .
    ?secondPersonMasculineImperativePluralActiveForm ontolex:representation ?secondPersonMasculineImperativePluralActive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q22716, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineActivePerformativeDualForm .
    ?thirdPersonMasculineActivePerformativeDualForm ontolex:representation ?thirdPersonMasculineActivePerformativeDual ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSubjunctiveFeminineActiveFiilMudariSingularForm .
    ?thirdPersonSubjunctiveFeminineActiveFiilMudariSingularForm ontolex:representation ?thirdPersonSubjunctiveFeminineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q473746, wd:Q1775415, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativeFeminineActiveSingularForm .
    ?secondPersonImperativeFeminineActiveSingularForm ontolex:representation ?secondPersonImperativeFeminineActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q1775415, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineActivePerformativeSingularForm .
    ?thirdPersonMasculineActivePerformativeSingularForm ontolex:representation ?thirdPersonMasculineActivePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePastSingularForm .
    ?thirdPersonMasculinePastSingularForm ontolex:representation ?thirdPersonMasculinePastSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPastPluralActiveForm .
    ?firstPersonPastPluralActiveForm ontolex:representation ?firstPersonPastPluralActive ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1994301, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePastActiveSingularForm .
    ?secondPersonMasculinePastActiveSingularForm ontolex:representation ?secondPersonMasculinePastActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q1994301, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFeminineActivePerformativeSingularForm .
    ?thirdPersonFeminineActivePerformativeSingularForm ontolex:representation ?thirdPersonFeminineActivePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPastActiveSingularForm .
    ?firstPersonPastActiveSingularForm ontolex:representation ?firstPersonPastActiveSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1994301, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralActivePerformativeForm .
    ?firstPersonPluralActivePerformativeForm ontolex:representation ?firstPersonPluralActivePerformative ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q1317831, wd:Q124351233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonFiilMudariSingularForm .
    ?indicativeFirstPersonFiilMudariSingularForm ontolex:representation ?indicativeFirstPersonFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonActiveSingularForm .
    ?perfectFirstPersonActiveSingularForm ontolex:representation ?perfectFirstPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativeFemininePluralActiveForm .
    ?secondPersonImperativeFemininePluralActiveForm ontolex:representation ?secondPersonImperativeFemininePluralActive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q1775415, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonFeminineActiveFiilMudariDualForm .
    ?indicativeThirdPersonFeminineActiveFiilMudariDualForm ontolex:representation ?indicativeThirdPersonFeminineActiveFiilMudariDual ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q1775415, wd:Q1317831, wd:Q12230930, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteThirdPersonMasculinePastSingularForm .
    ?indefiniteThirdPersonMasculinePastSingularForm ontolex:representation ?indefiniteThirdPersonMasculinePastSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q51929074, wd:Q499327, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPluralActiveFiilMudariForm .
    ?indicativeFirstPersonPluralActiveFiilMudariForm ontolex:representation ?indicativeFirstPersonPluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPastFemininePluralActiveForm .
    ?secondPersonPastFemininePluralActiveForm ontolex:representation ?secondPersonPastFemininePluralActive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1994301, wd:Q1775415, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonMasculineActiveSingularForm .
    ?perfectSecondPersonMasculineActiveSingularForm ontolex:representation ?perfectSecondPersonMasculineActiveSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q499327, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePerformativePassiveSingularForm .
    ?secondPersonMasculinePerformativePassiveSingularForm ontolex:representation ?secondPersonMasculinePerformativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q124351233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPastFeminineActiveSingularForm .
    ?thirdPersonPastFeminineActiveSingularForm ontolex:representation ?thirdPersonPastFeminineActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1994301, wd:Q1775415, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePluperfectThirdPersonActiveSingularForm .
    ?indicativePluperfectThirdPersonActiveSingularForm ontolex:representation ?indicativePluperfectThirdPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q623742, wd:Q51929074, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFemininePluralActivePerformativeForm .
    ?secondPersonFemininePluralActivePerformativeForm ontolex:representation ?secondPersonFemininePluralActivePerformative ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1775415, wd:Q146786, wd:Q1317831, wd:Q124351233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPastFeminineActiveDualForm .
    ?thirdPersonPastFeminineActiveDualForm ontolex:representation ?thirdPersonPastFeminineActiveDual ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1994301, wd:Q1775415, wd:Q1317831, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonActivePerformativeDualForm .
    ?secondPersonActivePerformativeDualForm ontolex:representation ?secondPersonActivePerformativeDual ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1317831, wd:Q124351233, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonFemininePluralActiveFiilMudariForm .
    ?indicativeSecondPersonFemininePluralActiveFiilMudariForm ontolex:representation ?indicativeSecondPersonFemininePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q1775415, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonImperativeActiveDualForm .
    ?secondPersonImperativeActiveDualForm ontolex:representation ?secondPersonImperativeActiveDual ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q22716, wd:Q1317831, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePluralActivePerformativeForm .
    ?secondPersonMasculinePluralActivePerformativeForm ontolex:representation ?secondPersonMasculinePluralActivePerformative ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q146786, wd:Q1317831, wd:Q124351233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonMasculineActiveFiilMudariSingularForm .
    ?indicativeSecondPersonMasculineActiveFiilMudariSingularForm ontolex:representation ?indicativeSecondPersonMasculineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q499327, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPerformativePassiveSingularForm .
    ?firstPersonPerformativePassiveSingularForm ontolex:representation ?firstPersonPerformativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q124351233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonFeminineActiveFiilMudariSingularForm .
    ?indicativeSecondPersonFeminineActiveFiilMudariSingularForm ontolex:representation ?indicativeSecondPersonFeminineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q1775415, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSubjunctivePluralActiveFiilMudariForm .
    ?secondPersonSubjunctivePluralActiveFiilMudariForm ontolex:representation ?secondPersonSubjunctivePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q473746, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFeminineActivePerformativeDualForm .
    ?thirdPersonFeminineActivePerformativeDualForm ontolex:representation ?thirdPersonFeminineActivePerformativeDual ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastForm .
    ?pastForm ontolex:representation ?past ;
      wikibase:grammaticalFeature wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculinePastPluralActiveForm .
    ?secondPersonMasculinePastPluralActiveForm ontolex:representation ?secondPersonMasculinePastPluralActive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q1994301, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePluralActivePerformativeForm .
    ?thirdPersonMasculinePluralActivePerformativeForm ontolex:representation ?thirdPersonMasculinePluralActivePerformative ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q146786, wd:Q1317831, wd:Q124351233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonFiilMudariSingularForm .
    ?firstPersonFiilMudariSingularForm ontolex:representation ?firstPersonFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveFirstPersonPluralActiveFiilMudariForm .
    ?subjunctiveFirstPersonPluralActiveFiilMudariForm ontolex:representation ?subjunctiveFirstPersonPluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q21714344, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPerformativeSingularForm .
    ?firstPersonPerformativeSingularForm ontolex:representation ?firstPersonPerformativeSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineSingularForm .
    ?thirdPersonMasculineSingularForm ontolex:representation ?thirdPersonMasculineSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonMasculineActiveFiilMudariDualForm .
    ?indicativeThirdPersonMasculineActiveFiilMudariDualForm ontolex:representation ?indicativeThirdPersonMasculineActiveFiilMudariDual ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q499327, wd:Q1317831, wd:Q12230930, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineSubjunctivePluralActiveFiilMudariForm .
    ?thirdPersonMasculineSubjunctivePluralActiveFiilMudariForm ontolex:representation ?thirdPersonMasculineSubjunctivePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q473746, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonMasculinePerformativeSingularForm .
    ?indicativeThirdPersonMasculinePerformativeSingularForm ontolex:representation ?indicativeThirdPersonMasculinePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q499327, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonActiveFiilMudariSingularForm .
    ?firstPersonActiveFiilMudariSingularForm ontolex:representation ?firstPersonActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePastPluralActiveForm .
    ?thirdPersonMasculinePastPluralActiveForm ontolex:representation ?thirdPersonMasculinePastPluralActive ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1994301, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineSubjunctiveActiveFiilMudariSingularForm .
    ?thirdPersonMasculineSubjunctiveActiveFiilMudariSingularForm ontolex:representation ?thirdPersonMasculineSubjunctiveActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q473746, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculineImperativeActiveSingularForm .
    ?secondPersonMasculineImperativeActiveSingularForm ontolex:representation ?secondPersonMasculineImperativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q22716, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralForm .
    ?masculinePluralForm ontolex:representation ?masculinePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineSubjunctiveActiveFiilMudariDualForm .
    ?thirdPersonMasculineSubjunctiveActiveFiilMudariDualForm ontolex:representation ?thirdPersonMasculineSubjunctiveActiveFiilMudariDual ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q473746, wd:Q1317831, wd:Q12230930, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPastFeminineActiveSingularForm .
    ?secondPersonPastFeminineActiveSingularForm ontolex:representation ?secondPersonPastFeminineActiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1994301, wd:Q1775415, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePastActiveDualForm .
    ?thirdPersonMasculinePastActiveDualForm ontolex:representation ?thirdPersonMasculinePastActiveDual ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1994301, wd:Q1317831, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralForm .
    ?femininePluralForm ontolex:representation ?femininePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeFirstPersonActiveFiilMudariSingularForm .
    ?indicativeFirstPersonActiveFiilMudariSingularForm ontolex:representation ?indicativeFirstPersonActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
    ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
      wikibase:grammaticalFeature wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastActiveDualForm .
    ?masculinePastActiveDualForm ontolex:representation ?masculinePastActiveDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q1317831, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculineActiveFiilMudariSingularForm .
    ?thirdPersonMasculineActiveFiilMudariSingularForm ontolex:representation ?thirdPersonMasculineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonMasculinePerformativeSingularForm .
    ?thirdPersonMasculinePerformativeSingularForm ontolex:representation ?thirdPersonMasculinePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q499327, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFemininePerformativePassiveSingularForm .
    ?secondPersonFemininePerformativePassiveSingularForm ontolex:representation ?secondPersonFemininePerformativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1775415, wd:Q124351233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonFeminineActiveSingularForm .
    ?perfectSecondPersonFeminineActiveSingularForm ontolex:representation ?perfectSecondPersonFeminineActiveSingular ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q1775415, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonMasculinePluralActiveFiilMudariForm .
    ?indicativeSecondPersonMasculinePluralActiveFiilMudariForm ontolex:representation ?indicativeSecondPersonMasculinePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q499327, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPastActiveCommonDualForm .
    ?secondPersonPastActiveCommonDualForm ontolex:representation ?secondPersonPastActiveCommonDual ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1994301, wd:Q1317831, wd:Q1305037, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonMasculineActiveFiilMudariSingularForm .
    ?indicativeThirdPersonMasculineActiveFiilMudariSingularForm ontolex:representation ?indicativeThirdPersonMasculineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q499327, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonActiveFiilMudariDualForm .
    ?indicativeSecondPersonActiveFiilMudariDualForm ontolex:representation ?indicativeSecondPersonActiveFiilMudariDual ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q1317831, wd:Q12230930, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeThirdPersonFeminineActiveFiilMudariSingularForm .
    ?indicativeThirdPersonFeminineActiveFiilMudariSingularForm ontolex:representation ?indicativeThirdPersonFeminineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q51929074, wd:Q1775415, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSubjunctiveFemininePluralActiveFiilMudariForm .
    ?secondPersonSubjunctiveFemininePluralActiveFiilMudariForm ontolex:representation ?secondPersonSubjunctiveFemininePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q473746, wd:Q1775415, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSubjunctiveActiveFiilMudariDualForm .
    ?secondPersonSubjunctiveActiveFiilMudariDualForm ontolex:representation ?secondPersonSubjunctiveActiveFiilMudariDual ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q473746, wd:Q1317831, wd:Q12230930, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonFeminineActivePerformativeSingularForm .
    ?secondPersonFeminineActivePerformativeSingularForm ontolex:representation ?secondPersonFeminineActivePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonSubjunctiveFeminineActiveFiilMudariSingularForm .
    ?secondPersonSubjunctiveFeminineActiveFiilMudariSingularForm ontolex:representation ?secondPersonSubjunctiveFeminineActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q473746, wd:Q1775415, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSubjunctiveFeminineActiveFiilMudariDualForm .
    ?thirdPersonSubjunctiveFeminineActiveFiilMudariDualForm ontolex:representation ?thirdPersonSubjunctiveFeminineActiveFiilMudariDual ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q473746, wd:Q1775415, wd:Q1317831, wd:Q12230930, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculineSubjunctivePluralActiveFiilMudariForm .
    ?secondPersonMasculineSubjunctivePluralActiveFiilMudariForm ontolex:representation ?secondPersonMasculineSubjunctivePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q473746, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPastFeminineSingularForm .
    ?thirdPersonPastFeminineSingularForm ontolex:representation ?thirdPersonPastFeminineSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1994301, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPastFemininePluralActiveForm .
    ?thirdPersonPastFemininePluralActiveForm ontolex:representation ?thirdPersonPastFemininePluralActive ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1994301, wd:Q1775415, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonMasculineActivePerformativeSingularForm .
    ?secondPersonMasculineActivePerformativeSingularForm ontolex:representation ?secondPersonMasculineActivePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?subjunctiveFirstPersonActiveFiilMudariSingularForm .
    ?subjunctiveFirstPersonActiveFiilMudariSingularForm ontolex:representation ?subjunctiveFirstPersonActiveFiilMudariSingular ;
      wikibase:grammaticalFeature wd:Q473746, wd:Q21714344, wd:Q1317831, wd:Q12230930, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonFemininePluralActivePerformativeForm .
    ?thirdPersonFemininePluralActivePerformativeForm ontolex:representation ?thirdPersonFemininePluralActivePerformative ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q1775415, wd:Q146786, wd:Q1317831, wd:Q124351233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSubjunctiveFemininePluralActiveFiilMudariForm .
    ?thirdPersonSubjunctiveFemininePluralActiveFiilMudariForm ontolex:representation ?thirdPersonSubjunctiveFemininePluralActiveFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q473746, wd:Q1775415, wd:Q146786, wd:Q1317831, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonActivePerformativeSingularForm .
    ?firstPersonActivePerformativeSingularForm ontolex:representation ?firstPersonActivePerformativeSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q1317831, wd:Q124351233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualThirdPersonPerformativeActiveMasculineForm .
    ?dualThirdPersonPerformativeActiveMasculineForm ontolex:representation ?dualThirdPersonPerformativeActiveMasculine ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q51929074, wd:Q124351233, wd:Q1317831, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariDualThirdPersonIndicativeMasculineForm .
    ?fiilMudariDualThirdPersonIndicativeMasculineForm ontolex:representation ?fiilMudariDualThirdPersonIndicativeMasculine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110022, wd:Q51929074, wd:Q682111, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariSingularThirdPersonIndicativeFeminineForm .
    ?fiilMudariSingularThirdPersonIndicativeFeminineForm ontolex:representation ?fiilMudariSingularThirdPersonIndicativeFeminine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110786, wd:Q51929074, wd:Q682111, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariPluralFirstPersonIndicativeForm .
    ?fiilMudariPluralFirstPersonIndicativeForm ontolex:representation ?fiilMudariPluralFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q146786, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariPluralSecondPersonIndicativeFeminineForm .
    ?fiilMudariPluralSecondPersonIndicativeFeminineForm ontolex:representation ?fiilMudariPluralSecondPersonIndicativeFeminine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q146786, wd:Q51929049, wd:Q682111, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPerformativeActiveFeminineForm .
    ?singularThirdPersonPerformativeActiveFeminineForm ontolex:representation ?singularThirdPersonPerformativeActiveFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q124351233, wd:Q1317831, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariSingularThirdPersonIndicativeMasculineForm .
    ?fiilMudariSingularThirdPersonIndicativeMasculineForm ontolex:representation ?fiilMudariSingularThirdPersonIndicativeMasculine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110786, wd:Q51929074, wd:Q682111, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualSecondPersonPerformativeActiveForm .
    ?dualSecondPersonPerformativeActiveForm ontolex:representation ?dualSecondPersonPerformativeActive ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q51929049, wd:Q124351233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualThirdPersonPerformativeActiveFeminineForm .
    ?dualThirdPersonPerformativeActiveFeminineForm ontolex:representation ?dualThirdPersonPerformativeActiveFeminine ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q51929074, wd:Q124351233, wd:Q1317831, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPerformativeActiveMasculineForm .
    ?singularSecondPersonPerformativeActiveMasculineForm ontolex:representation ?singularSecondPersonPerformativeActiveMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q124351233, wd:Q1317831, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariSingularFirstPersonIndicativeForm .
    ?fiilMudariSingularFirstPersonIndicativeForm ontolex:representation ?fiilMudariSingularFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110786, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariSingularSecondPersonIndicativeFeminineForm .
    ?fiilMudariSingularSecondPersonIndicativeFeminineForm ontolex:representation ?fiilMudariSingularSecondPersonIndicativeFeminine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110786, wd:Q51929049, wd:Q682111, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularSecondPersonPerformativeActiveFeminineForm .
    ?singularSecondPersonPerformativeActiveFeminineForm ontolex:representation ?singularSecondPersonPerformativeActiveFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929049, wd:Q124351233, wd:Q1317831, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariDualSecondPersonIndicativeForm .
    ?fiilMudariDualSecondPersonIndicativeForm ontolex:representation ?fiilMudariDualSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110022, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFirstPersonPerformativeActiveForm .
    ?pluralFirstPersonPerformativeActiveForm ontolex:representation ?pluralFirstPersonPerformativeActive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q124351233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariPluralSecondPersonIndicativeMasculineForm .
    ?fiilMudariPluralSecondPersonIndicativeMasculineForm ontolex:representation ?fiilMudariPluralSecondPersonIndicativeMasculine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q146786, wd:Q51929049, wd:Q682111, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariDualThirdPersonIndicativeFeminineForm .
    ?fiilMudariDualThirdPersonIndicativeFeminineForm ontolex:representation ?fiilMudariDualThirdPersonIndicativeFeminine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110022, wd:Q51929074, wd:Q682111, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariSingularSecondPersonIndicativeMasculineForm .
    ?fiilMudariSingularSecondPersonIndicativeMasculineForm ontolex:representation ?fiilMudariSingularSecondPersonIndicativeMasculine ;
      wikibase:grammaticalFeature wd:Q12230930, wd:Q110786, wd:Q51929049, wd:Q682111, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFirstPersonPerformativeActiveForm .
    ?singularFirstPersonPerformativeActiveForm ontolex:representation ?singularFirstPersonPerformativeActive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q124351233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPerformativeActiveMasculineForm .
    ?pluralSecondPersonPerformativeActiveMasculineForm ontolex:representation ?pluralSecondPersonPerformativeActiveMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q124351233, wd:Q1317831, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonPerformativeActiveMasculineForm .
    ?singularThirdPersonPerformativeActiveMasculineForm ontolex:representation ?singularThirdPersonPerformativeActiveMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074, wd:Q124351233, wd:Q1317831, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonPerformativeActiveFeminineForm .
    ?pluralSecondPersonPerformativeActiveFeminineForm ontolex:representation ?pluralSecondPersonPerformativeActiveFeminine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049, wd:Q124351233, wd:Q1317831, wd:Q1775415 .
  }
}
