name: ⌨️ New keyboard
description: Suggest a new language keyboard for Scribe!
labels: ["new keyboard"]
projects: ["scribe-org/1"]
title: Add <language> keyboard
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched [open new keyboard issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+keyboard%22)
          required: true
        - label: I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
        - label: This issue is about one language, and I've changed the title to reflect this
          required: true
  - type: textarea
    id: support
    attributes:
      label: Language support
      placeholder: |
        Tell us about the language and how Scribe can help people with it.
        Examples:
          - The number of noun genders
          - How verbs are conjugated
          - Preposition-case relationships
          - Other grammar rules that are hard
    validations:
      required: true
  - type: textarea
    id: contribution
    attributes:
      label: Contribution
      placeholder: Let us know if you'd like to help and how :)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in adding another Scribe keyboard!
