
# tool: scribe-data
# All russian (Q7737) adjectives (Q34698) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?adjectives
    ?singular
  ?accusative
  ?neuter
  ?singular
  ?feminine
  ?instrumental
  ?plural
  ?singular
  ?accusative
  ?inanimate
  ?singular
  ?neuter
  ?instrumental
  ?singular
  ?nominative
  ?masculine
  ?singular
  ?dative
  ?neuter
  ?singular
  ?neuter
  ?singular
  ?nominative
  ?feminine
  ?singular
  ?accusative
  ?feminine
  ?animate
  ?singular
  ?accusative
  ?masculine
  ?singular
  ?accusative
  ?feminine
  ?singular
  ?accusative
  ?feminine
  ?inanimate
  ?singular
  ?accusative
  ?masculine
  ?animate
  ?singular
  ?genitive
  ?neuter
  ?singular
  ?feminine
  ?prepositional
  ?singular
  ?accusative
  ?masculine
  ?inanimate
  ?singular
  ?neuter
  ?prepositional
  ?singular
  ?feminine
  ?short
  ?singular
  ?dative
  ?masculine
  ?singular
  ?dative
  ?feminine
  ?singular
  ?neuter
  ?short
  ?plural
  ?instrumental
  ?singular
  ?accusative
  ?neuter
  ?animate
  ?singular
  ?masculine
  ?singular
  ?feminine
  ?singular
  ?accusative
  ?neuter
  ?inanimate
  ?accusative
  ?plural
  ?animate
  ?comparative
  ?singular
  ?genitive
  ?masculine
  ?singular
  ?genitive
  ?feminine
  ?accusative
  ?plural
  ?inanimate
  ?plural
  ?prepositional
  ?singular
  ?short
  ?masculine
  ?singular
  ?nominative
  ?singular
  ?instrumental
  ?masculine
  ?nominative
  ?plural
  ?masculine
  ?singular
  ?prepositional
  ?masculine
  ?singular
  ?nominative
  ?neuter
  ?nominative
  ?masculine
  ?superlative
  WHERE {
    ?lexeme dct:language wd:Q7737 ;
        wikibase:lexicalCategory wd:Q34698 ;
        wikibase:lemma ?adjectives .
        FILTER(lang(?adjectives) = "ru")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?prepositionalForm .
            ?prepositionalForm ontolex:representation ?prepositional ;
                wikibase:grammaticalFeature wd:Q2114906 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?prepositionalForm .
            ?prepositionalForm ontolex:representation ?prepositional ;
                wikibase:grammaticalFeature wd:Q2114906 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?shortForm .
            ?shortForm ontolex:representation ?short ;
                wikibase:grammaticalFeature wd:Q4239848 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?shortForm .
            ?shortForm ontolex:representation ?short ;
                wikibase:grammaticalFeature wd:Q4239848 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?comparativeForm .
            ?comparativeForm ontolex:representation ?comparative ;
                wikibase:grammaticalFeature wd:Q14169499 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?prepositionalForm .
            ?prepositionalForm ontolex:representation ?prepositional ;
                wikibase:grammaticalFeature wd:Q2114906 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?shortForm .
            ?shortForm ontolex:representation ?short ;
                wikibase:grammaticalFeature wd:Q4239848 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?prepositionalForm .
            ?prepositionalForm ontolex:representation ?prepositional ;
                wikibase:grammaticalFeature wd:Q2114906 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?superlativeForm .
            ?superlativeForm ontolex:representation ?superlative ;
                wikibase:grammaticalFeature wd:Q1817208 .
        }
}