# tool: scribe-data
# All Latin (Q397) pronouns (Q36224) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pronouns
  ?masculinePluralAccusative
  ?masculinePluralGenitive
  ?neuterAblativeSingular
  ?masculineNominativeSingular
  ?genitiveSingular
  ?neuterPluralGenitive
  ?neuterPluralAccusative
  ?masculineAccusativeSingular
  ?masculinePluralNominative
  ?feminineAblativeSingular
  ?neuterNominativeSingular
  ?femininePluralAccusative
  ?neuterAccusativeSingular
  ?femininePluralGenitive
  ?neuterPluralNominative
  ?feminineNominativeSingular
  ?pluralDative
  ?feminineAccusativeSingular
  ?femininePluralNominative
  ?dativeSingular
  ?ablativePlural
  ?masculineAblativeSingular
  ?genitivePluralNeuter
  ?accusativePluralNeuter
  ?nominativePluralFeminine
  ?nominativePluralNeuter
  ?singularDative
  ?singularAblativeNeuter
  ?genitivePluralMasculine
  ?accusativePluralMasculine
  ?singularAblativeFeminine
  ?dativePlural
  ?nominativePluralMasculine
  ?singularAblativeMasculine
  ?pluralAblative
  ?singularNominativeFeminine
  ?singularNominativeNeuter
  ?singularGenitive
  ?singularNominativeMasculine
  ?singularAccusativeFeminine
  ?singularAccusativeNeuter
  ?singularAccusativeMasculine
  ?genitivePluralFeminine
  ?accusativePluralFeminine
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q36224 ;
      wikibase:lemma ?pronouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralAccusativeForm .
    ?masculinePluralAccusativeForm ontolex:representation ?masculinePluralAccusative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralGenitiveForm .
    ?masculinePluralGenitiveForm ontolex:representation ?masculinePluralGenitive ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterAblativeSingularForm .
    ?neuterAblativeSingularForm ontolex:representation ?neuterAblativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineNominativeSingularForm .
    ?masculineNominativeSingularForm ontolex:representation ?masculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralGenitiveForm .
    ?neuterPluralGenitiveForm ontolex:representation ?neuterPluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralAccusativeForm .
    ?neuterPluralAccusativeForm ontolex:representation ?neuterPluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralNominativeForm .
    ?masculinePluralNominativeForm ontolex:representation ?masculinePluralNominative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAblativeSingularForm .
    ?feminineAblativeSingularForm ontolex:representation ?feminineAblativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterNominativeSingularForm .
    ?neuterNominativeSingularForm ontolex:representation ?neuterNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralAccusativeForm .
    ?femininePluralAccusativeForm ontolex:representation ?femininePluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterAccusativeSingularForm .
    ?neuterAccusativeSingularForm ontolex:representation ?neuterAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralGenitiveForm .
    ?femininePluralGenitiveForm ontolex:representation ?femininePluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralNominativeForm .
    ?neuterPluralNominativeForm ontolex:representation ?neuterPluralNominative ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineNominativeSingularForm .
    ?feminineNominativeSingularForm ontolex:representation ?feminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDativeForm .
    ?pluralDativeForm ontolex:representation ?pluralDative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeSingularForm .
    ?feminineAccusativeSingularForm ontolex:representation ?feminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralNominativeForm .
    ?femininePluralNominativeForm ontolex:representation ?femininePluralNominative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralForm .
    ?ablativePluralForm ontolex:representation ?ablativePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAblativeSingularForm .
    ?masculineAblativeSingularForm ontolex:representation ?masculineAblativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralNeuterForm .
    ?genitivePluralNeuterForm ontolex:representation ?genitivePluralNeuter ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralNeuterForm .
    ?accusativePluralNeuterForm ontolex:representation ?accusativePluralNeuter ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralFeminineForm .
    ?nominativePluralFeminineForm ontolex:representation ?nominativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralNeuterForm .
    ?nominativePluralNeuterForm ontolex:representation ?nominativePluralNeuter ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeForm .
    ?singularDativeForm ontolex:representation ?singularDative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeNeuterForm .
    ?singularAblativeNeuterForm ontolex:representation ?singularAblativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralMasculineForm .
    ?genitivePluralMasculineForm ontolex:representation ?genitivePluralMasculine ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralMasculineForm .
    ?accusativePluralMasculineForm ontolex:representation ?accusativePluralMasculine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeFeminineForm .
    ?singularAblativeFeminineForm ontolex:representation ?singularAblativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralMasculineForm .
    ?nominativePluralMasculineForm ontolex:representation ?nominativePluralMasculine ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeMasculineForm .
    ?singularAblativeMasculineForm ontolex:representation ?singularAblativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativeForm .
    ?pluralAblativeForm ontolex:representation ?pluralAblative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeFeminineForm .
    ?singularNominativeFeminineForm ontolex:representation ?singularNominativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeNeuterForm .
    ?singularNominativeNeuterForm ontolex:representation ?singularNominativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeMasculineForm .
    ?singularNominativeMasculineForm ontolex:representation ?singularNominativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAccusativeFeminineForm .
    ?singularAccusativeFeminineForm ontolex:representation ?singularAccusativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146078, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAccusativeNeuterForm .
    ?singularAccusativeNeuterForm ontolex:representation ?singularAccusativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146078, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAccusativeMasculineForm .
    ?singularAccusativeMasculineForm ontolex:representation ?singularAccusativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146078, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralFeminineForm .
    ?genitivePluralFeminineForm ontolex:representation ?genitivePluralFeminine ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralFeminineForm .
    ?accusativePluralFeminineForm ontolex:representation ?accusativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775415 .
  }
}
