# tool: scribe-data
# All Estonian (Q9072) postpositions (Q161873) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?postposition
  ?partitiveSingular
  ?partitivePlural
  ?translativeSingular
  ?translativePlural
  ?terminativeSingular
  ?terminativePlural

WHERE {
  ?lexeme dct:language wd:Q9072 ;
      wikibase:lexicalCategory wd:Q161873 ;
      wikibase:lemma ?postposition ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveSingularForm .
    ?partitiveSingularForm ontolex:representation ?partitiveSingular ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitivePluralForm .
    ?partitivePluralForm ontolex:representation ?partitivePlural ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativeSingularForm .
    ?translativeSingularForm ontolex:representation ?translativeSingular ;
      wikibase:grammaticalFeature wd:Q950170, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativePluralForm .
    ?translativePluralForm ontolex:representation ?translativePlural ;
      wikibase:grammaticalFeature wd:Q950170, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?terminativeSingularForm .
    ?terminativeSingularForm ontolex:representation ?terminativeSingular ;
      wikibase:grammaticalFeature wd:Q747019, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?terminativePluralForm .
    ?terminativePluralForm ontolex:representation ?terminativePlural ;
      wikibase:grammaticalFeature wd:Q747019, wd:Q146786 .
  }
}
