
# tool: scribe-data
# All french (Q150) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?verbs
    ?singular
  ?preterite
  ?secondPerson
  ?indicative
  ?plural
  ?present
  ?thirdPerson
  ?indicative
  ?singular
  ?firstPerson
  ?preterite
  ?indicative
  ?imperfect
  ?plural
  ?firstPerson
  ?indicative
  ?imperfect
  ?plural
  ?subjunctive
  ?secondPerson
  ?imperfect
  ?plural
  ?secondPerson
  ?indicative
  ?gerund
  ?plural
  ?present
  ?firstPerson
  ?indicative
  ?plural
  ?present
  ?subjunctive
  ?secondPerson
  ?plural
  ?feminine
  ?past
  ?participle
  ?plural
  ?present
  ?secondPerson
  ?indicative
  ?singular
  ?pastParticiple
  ?masculine
  ?singular
  ?pastParticiple
  ?feminine
  ?past
  ?participle
  ?singular
  ?present
  ?imperative
  ?secondPerson
  ?singular
  ?present
  ?firstPerson
  ?conditional
  ?imperfect
  ?singular
  ?firstPerson
  ?subjunctive
  ?plural
  ?simpleFuture
  ?firstPerson
  ?indicative
  ?plural
  ?firstPerson
  ?preterite
  ?indicative
  ?present
  ?participle
  ?singular
  ?present
  ?thirdPerson
  ?conditional
  ?imperfect
  ?singular
  ?subjunctive
  ?thirdPerson
  ?plural
  ?simpleFuture
  ?thirdPerson
  ?indicative
  ?singular
  ?present
  ?subjunctive
  ?thirdPerson
  ?singular
  ?present
  ?secondPerson
  ?indicative
  ?singular
  ?present
  ?firstPerson
  ?subjunctive
  ?singular
  ?present
  ?secondPerson
  ?conditional
  ?plural
  ?past
  ?masculine
  ?participle
  ?plural
  ?simpleFuture
  ?secondPerson
  ?indicative
  ?pastParticiple
  ?plural
  ?masculine
  ?plural
  ?present
  ?thirdPerson
  ?conditional
  ?pastParticiple
  ?singular
  ?feminine
  ?past
  ?participle
  ?plural
  ?present
  ?imperative
  ?secondPerson
  ?infinitive
  ?plural
  ?present
  ?firstPerson
  ?conditional
  ?imperfect
  ?singular
  ?thirdPerson
  ?indicative
  ?plural
  ?present
  ?secondPerson
  ?conditional
  ?imperfect
  ?plural
  ?firstPerson
  ?subjunctive
  ?infinitive
  ?singular
  ?past
  ?masculine
  ?participle
  ?imperfect
  ?singular
  ?firstPerson
  ?indicative
  ?imperfect
  ?singular
  ?subjunctive
  ?secondPerson
  ?singular
  ?present
  ?subjunctive
  ?secondPerson
  ?imperfect
  ?singular
  ?secondPerson
  ?indicative
  ?plural
  ?preterite
  ?secondPerson
  ?indicative
  ?plural
  ?present
  ?firstPerson
  ?subjunctive
  ?plural
  ?preterite
  ?thirdPerson
  ?indicative
  ?imperfect
  ?plural
  ?subjunctive
  ?thirdPerson
  ?plural
  ?present
  ?firstPerson
  ?imperative
  ?plural
  ?simpleFuture
  ?future
  ?thirdPerson
  ?indicative
  ?singular
  ?simpleFuture
  ?future
  ?thirdPerson
  ?indicative
  ?plural
  ?present
  ?subjunctive
  ?thirdPerson
  ?singular
  ?simpleFuture
  ?firstPerson
  ?indicative
  ?plural
  ?simpleFuture
  ?future
  ?secondPerson
  ?indicative
  ?singular
  ?present
  ?firstPerson
  ?indicative
  ?singular
  ?simpleFuture
  ?firstPerson
  ?future
  ?indicative
  ?singular
  ?present
  ?thirdPerson
  ?indicative
  ?presentParticiple
  ?present
  ?participle
  ?singular
  ?pastParticiple
  ?past
  ?masculine
  ?participle
  ?presentParticiple
  ?singular
  ?preterite
  ?thirdPerson
  ?indicative
  ?singular
  ?simpleFuture
  ?secondPerson
  ?indicative
  ?singular
  ?simpleFuture
  ?thirdPerson
  ?indicative
  ?imperfect
  ?plural
  ?thirdPerson
  ?indicative
  ?singular
  ?pastParticiple
  ?feminine
  WHERE {
    ?lexeme dct:language wd:Q150 ;
        wikibase:lexicalCategory wd:Q24905 ;
        wikibase:lemma ?verbs .
        FILTER(lang(?verbs) = "fr")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?preteriteForm .
            ?preteriteForm ontolex:representation ?preterite ;
                wikibase:grammaticalFeature wd:Q442485 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?preteriteForm .
            ?preteriteForm ontolex:representation ?preterite ;
                wikibase:grammaticalFeature wd:Q442485 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?gerundForm .
            ?gerundForm ontolex:representation ?gerund ;
                wikibase:grammaticalFeature wd:Q1923028 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastParticipleForm .
            ?pastParticipleForm ontolex:representation ?pastParticiple ;
                wikibase:grammaticalFeature wd:Q12717679 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastParticipleForm .
            ?pastParticipleForm ontolex:representation ?pastParticiple ;
                wikibase:grammaticalFeature wd:Q12717679 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?preteriteForm .
            ?preteriteForm ontolex:representation ?preterite ;
                wikibase:grammaticalFeature wd:Q442485 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastParticipleForm .
            ?pastParticipleForm ontolex:representation ?pastParticiple ;
                wikibase:grammaticalFeature wd:Q12717679 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastParticipleForm .
            ?pastParticipleForm ontolex:representation ?pastParticiple ;
                wikibase:grammaticalFeature wd:Q12717679 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?conditionalForm .
            ?conditionalForm ontolex:representation ?conditional ;
                wikibase:grammaticalFeature wd:Q625581 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?preteriteForm .
            ?preteriteForm ontolex:representation ?preterite ;
                wikibase:grammaticalFeature wd:Q442485 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?preteriteForm .
            ?preteriteForm ontolex:representation ?preterite ;
                wikibase:grammaticalFeature wd:Q442485 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?futureForm .
            ?futureForm ontolex:representation ?future ;
                wikibase:grammaticalFeature wd:Q501405 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?futureForm .
            ?futureForm ontolex:representation ?future ;
                wikibase:grammaticalFeature wd:Q501405 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?subjunctiveForm .
            ?subjunctiveForm ontolex:representation ?subjunctive ;
                wikibase:grammaticalFeature wd:Q473746 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?futureForm .
            ?futureForm ontolex:representation ?future ;
                wikibase:grammaticalFeature wd:Q501405 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?futureForm .
            ?futureForm ontolex:representation ?future ;
                wikibase:grammaticalFeature wd:Q501405 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentParticipleForm .
            ?presentParticipleForm ontolex:representation ?presentParticiple ;
                wikibase:grammaticalFeature wd:Q10345583 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastParticipleForm .
            ?pastParticipleForm ontolex:representation ?pastParticiple ;
                wikibase:grammaticalFeature wd:Q12717679 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentParticipleForm .
            ?presentParticipleForm ontolex:representation ?presentParticiple ;
                wikibase:grammaticalFeature wd:Q10345583 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?preteriteForm .
            ?preteriteForm ontolex:representation ?preterite ;
                wikibase:grammaticalFeature wd:Q442485 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simpleFutureForm .
            ?simpleFutureForm ontolex:representation ?simpleFuture ;
                wikibase:grammaticalFeature wd:Q1475560 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperfectForm .
            ?imperfectForm ontolex:representation ?imperfect ;
                wikibase:grammaticalFeature wd:Q108524486 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastParticipleForm .
            ?pastParticipleForm ontolex:representation ?pastParticiple ;
                wikibase:grammaticalFeature wd:Q12717679 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
}