# tool: scribe-data
# All Spanish (Q1321) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?personalpronoun
  ?masculinePlural
  ?nominativeVocativeFeminineMasculineSingularPlural
  ?masculineSingular
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q1321 ;
      wikibase:lexicalCategory wd:Q468801 ;
      wikibase:lemma ?personalpronoun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralForm .
    ?masculinePluralForm ontolex:representation ?masculinePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeVocativeFeminineMasculineSingularPluralForm .
    ?nominativeVocativeFeminineMasculineSingularPluralForm ontolex:representation ?nominativeVocativeFeminineMasculineSingularPlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q185077, wd:Q1775415, wd:Q499327, wd:Q110786, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularForm .
    ?masculineSingularForm ontolex:representation ?masculineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786 .
  }
}
