# tool: scribe-data
# All Hebrew (Q9288) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nouns
  ?masculineFemininePlural
  ?feminineSingular
  ?masculineDual
  ?masculineConstructPlural
  ?nominativeSingular
  ?masculineConstructSingular
  ?feminineDual
  ?feminineConstructPlural
  ?masculineFeminineConstructSingular
  ?feminineConstructSingular
  ?masculineFeminine
  ?masculinePlural
  ?masculineFeminineSingular
  ?constructPlural
  ?feminineConstructDual
  ?femininePlural
  ?constructSingular
  ?masculineConstructDual
  ?masculineFeminineConstructPlural
  ?pluralNominative
  ?masculineSingular
  ?singularConstructMasculine
  ?pluralConstruct
  ?singularNominative
  ?pluralConstructFeminineMasculine
  ?pluralFeminine
  ?pluralConstructFeminine
  ?pluralFeminineMasculine
  ?pluralMasculine
  ?singularConstruct
  ?dualFeminine
  ?pluralConstructMasculine
  ?dualConstructFeminine
  ?singularConstructFeminineMasculine
  ?singularFeminine
  ?singularConstructFeminine
  ?singularFeminineMasculine
  ?nominativePlural
  ?dualMasculine
  ?feminineMasculine
  ?dualConstructMasculine
  ?singularMasculine
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q9288 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFemininePluralForm .
    ?masculineFemininePluralForm ontolex:representation ?masculineFemininePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularForm .
    ?feminineSingularForm ontolex:representation ?feminineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDualForm .
    ?masculineDualForm ontolex:representation ?masculineDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructPluralForm .
    ?masculineConstructPluralForm ontolex:representation ?masculineConstructPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructSingularForm .
    ?masculineConstructSingularForm ontolex:representation ?masculineConstructSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineDualForm .
    ?feminineDualForm ontolex:representation ?feminineDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructPluralForm .
    ?feminineConstructPluralForm ontolex:representation ?feminineConstructPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFeminineConstructSingularForm .
    ?masculineFeminineConstructSingularForm ontolex:representation ?masculineFeminineConstructSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415, wd:Q1641446, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructSingularForm .
    ?feminineConstructSingularForm ontolex:representation ?feminineConstructSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFeminineForm .
    ?masculineFeminineForm ontolex:representation ?masculineFeminine ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralForm .
    ?masculinePluralForm ontolex:representation ?masculinePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFeminineSingularForm .
    ?masculineFeminineSingularForm ontolex:representation ?masculineFeminineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructPluralForm .
    ?constructPluralForm ontolex:representation ?constructPlural ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructDualForm .
    ?feminineConstructDualForm ontolex:representation ?feminineConstructDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralForm .
    ?femininePluralForm ontolex:representation ?femininePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructSingularForm .
    ?constructSingularForm ontolex:representation ?constructSingular ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructDualForm .
    ?masculineConstructDualForm ontolex:representation ?masculineConstructDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFeminineConstructPluralForm .
    ?masculineFeminineConstructPluralForm ontolex:representation ?masculineFeminineConstructPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1775415, wd:Q1641446, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralNominativeForm .
    ?pluralNominativeForm ontolex:representation ?pluralNominative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularForm .
    ?masculineSingularForm ontolex:representation ?masculineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularConstructMasculineForm .
    ?singularConstructMasculineForm ontolex:representation ?singularConstructMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1641446, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralConstructForm .
    ?pluralConstructForm ontolex:representation ?pluralConstruct ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralConstructFeminineMasculineForm .
    ?pluralConstructFeminineMasculineForm ontolex:representation ?pluralConstructFeminineMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1641446, wd:Q1775415, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineForm .
    ?pluralFeminineForm ontolex:representation ?pluralFeminine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralConstructFeminineForm .
    ?pluralConstructFeminineForm ontolex:representation ?pluralConstructFeminine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1641446, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineMasculineForm .
    ?pluralFeminineMasculineForm ontolex:representation ?pluralFeminineMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralMasculineForm .
    ?pluralMasculineForm ontolex:representation ?pluralMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularConstructForm .
    ?singularConstructForm ontolex:representation ?singularConstruct ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualFeminineForm .
    ?dualFeminineForm ontolex:representation ?dualFeminine ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralConstructMasculineForm .
    ?pluralConstructMasculineForm ontolex:representation ?pluralConstructMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1641446, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualConstructFeminineForm .
    ?dualConstructFeminineForm ontolex:representation ?dualConstructFeminine ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q1641446, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularConstructFeminineMasculineForm .
    ?singularConstructFeminineMasculineForm ontolex:representation ?singularConstructFeminineMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1641446, wd:Q1775415, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineForm .
    ?singularFeminineForm ontolex:representation ?singularFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularConstructFeminineForm .
    ?singularConstructFeminineForm ontolex:representation ?singularConstructFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1641446, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineMasculineForm .
    ?singularFeminineMasculineForm ontolex:representation ?singularFeminineMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralForm .
    ?nominativePluralForm ontolex:representation ?nominativePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualMasculineForm .
    ?dualMasculineForm ontolex:representation ?dualMasculine ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculineForm .
    ?feminineMasculineForm ontolex:representation ?feminineMasculine ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualConstructMasculineForm .
    ?dualConstructMasculineForm ontolex:representation ?dualConstructMasculine ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q1641446, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineForm .
    ?singularMasculineForm ontolex:representation ?singularMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327 .
  }
}
