# tool: scribe-data
# All Slovak (Q9058) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nouns
  ?locativeFeminineSingular
  ?pluralGenitive
  ?animateLocativeSingular
  ?masculineAccusativeSingular
  ?locativeFemininePlural
  ?masculineDativeSingular
  ?inanimateLocativeSingular
  ?masculinePluralNominative
  ?feminineAccusativeSingular
  ?feminineDativeSingular
  ?masculineLocativeSingular
  ?locativeSingular
  ?femininePluralNominative
  ?masculinePluralGenitive
  ?nominativeSingular
  ?genitiveSingular
  ?masculineLocativePlural
  ?femininePluralGenitive
  ?vocativeSingular
  ?instrumentalPlural
  ?dativeSingular
  ?pluralAccusative
  ?masculineInstrumentalSingular
  ?instrumentalFeminineSingular
  ?masculinePluralAccusative
  ?singular
  ?instrumentalFemininePlural
  ?femininePluralAccusative
  ?masculineInstrumentalPlural
  ?masculineNominativeSingular
  ?pluralDative
  ?masculinePluralDative
  ?feminineNominativeSingular
  ?femininePluralDative
  ?instrumentalSingular
  ?masculineGenitiveSingular
  ?neuter
  ?accusativeSingular
  ?locativePlural
  ?animateAccusativeSingular
  ?feminineGenitiveSingular
  ?animateDativeSingular
  ?inanimateAccusativeSingular
  ?inanimateDativeSingular
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q9058 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularForm .
    ?locativeFeminineSingularForm ontolex:representation ?locativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralGenitiveForm .
    ?pluralGenitiveForm ontolex:representation ?pluralGenitive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?animateLocativeSingularForm .
    ?animateLocativeSingularForm ontolex:representation ?animateLocativeSingular ;
      wikibase:grammaticalFeature wd:Q51927507, wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralForm .
    ?locativeFemininePluralForm ontolex:representation ?locativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDativeSingularForm .
    ?masculineDativeSingularForm ontolex:representation ?masculineDativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inanimateLocativeSingularForm .
    ?inanimateLocativeSingularForm ontolex:representation ?inanimateLocativeSingular ;
      wikibase:grammaticalFeature wd:Q51927539, wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralNominativeForm .
    ?masculinePluralNominativeForm ontolex:representation ?masculinePluralNominative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeSingularForm .
    ?feminineAccusativeSingularForm ontolex:representation ?feminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineDativeSingularForm .
    ?feminineDativeSingularForm ontolex:representation ?feminineDativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineLocativeSingularForm .
    ?masculineLocativeSingularForm ontolex:representation ?masculineLocativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralNominativeForm .
    ?femininePluralNominativeForm ontolex:representation ?femininePluralNominative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralGenitiveForm .
    ?masculinePluralGenitiveForm ontolex:representation ?masculinePluralGenitive ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineLocativePluralForm .
    ?masculineLocativePluralForm ontolex:representation ?masculineLocativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralGenitiveForm .
    ?femininePluralGenitiveForm ontolex:representation ?femininePluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeSingularForm .
    ?vocativeSingularForm ontolex:representation ?vocativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalPluralForm .
    ?instrumentalPluralForm ontolex:representation ?instrumentalPlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAccusativeForm .
    ?pluralAccusativeForm ontolex:representation ?pluralAccusative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineInstrumentalSingularForm .
    ?masculineInstrumentalSingularForm ontolex:representation ?masculineInstrumentalSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularForm .
    ?instrumentalFeminineSingularForm ontolex:representation ?instrumentalFeminineSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralAccusativeForm .
    ?masculinePluralAccusativeForm ontolex:representation ?masculinePluralAccusative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFemininePluralForm .
    ?instrumentalFemininePluralForm ontolex:representation ?instrumentalFemininePlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralAccusativeForm .
    ?femininePluralAccusativeForm ontolex:representation ?femininePluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineInstrumentalPluralForm .
    ?masculineInstrumentalPluralForm ontolex:representation ?masculineInstrumentalPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q192997, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineNominativeSingularForm .
    ?masculineNominativeSingularForm ontolex:representation ?masculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDativeForm .
    ?pluralDativeForm ontolex:representation ?pluralDative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralDativeForm .
    ?masculinePluralDativeForm ontolex:representation ?masculinePluralDative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineNominativeSingularForm .
    ?feminineNominativeSingularForm ontolex:representation ?feminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralDativeForm .
    ?femininePluralDativeForm ontolex:representation ?femininePluralDative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalSingularForm .
    ?instrumentalSingularForm ontolex:representation ?instrumentalSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveSingularForm .
    ?masculineGenitiveSingularForm ontolex:representation ?masculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterForm .
    ?neuterForm ontolex:representation ?neuter ;
      wikibase:grammaticalFeature wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativePluralForm .
    ?locativePluralForm ontolex:representation ?locativePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?animateAccusativeSingularForm .
    ?animateAccusativeSingularForm ontolex:representation ?animateAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q51927507, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineGenitiveSingularForm .
    ?feminineGenitiveSingularForm ontolex:representation ?feminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?animateDativeSingularForm .
    ?animateDativeSingularForm ontolex:representation ?animateDativeSingular ;
      wikibase:grammaticalFeature wd:Q51927507, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inanimateAccusativeSingularForm .
    ?inanimateAccusativeSingularForm ontolex:representation ?inanimateAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q51927539, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inanimateDativeSingularForm .
    ?inanimateDativeSingularForm ontolex:representation ?inanimateDativeSingular ;
      wikibase:grammaticalFeature wd:Q51927539, wd:Q145599, wd:Q110786 .
  }
}
