
# tool: scribe-data
# All slovak (Q9058) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?nouns
    ?singular
  ?nominative
  ?feminine
  ?nominative
  ?plural
  ?masculine
  ?genitive
  ?plural
  ?feminine
  ?neuter
  ?dative
  ?plural
  ?masculine
  ?singular
  ?dative
  ?feminine
  ?dative
  ?plural
  ?singular
  ?nominative
  ?masculine
  ?genitive
  ?plural
  ?masculine
  ?accusative
  ?plural
  ?plural
  ?feminine
  ?instrumental
  ?singular
  ?locative
  ?nominative
  ?plural
  ?singular
  ?feminine
  ?instrumental
  ?singular
  ?dative
  ?inanimate
  ?singular
  ?dative
  ?masculine
  ?singular
  ?dative
  ?animate
  ?plural
  ?instrumental
  ?singular
  ?singular
  ?dative
  ?singular
  ?accusative
  ?singular
  ?locative
  ?inanimate
  ?singular
  ?locative
  ?masculine
  ?singular
  ?locative
  ?animate
  ?dative
  ?plural
  ?feminine
  ?singular
  ?accusative
  ?feminine
  ?accusative
  ?plural
  ?singular
  ?nominative
  ?singular
  ?genitive
  ?feminine
  ?accusative
  ?plural
  ?feminine
  ?genitive
  ?plural
  ?singular
  ?instrumental
  ?masculine
  ?plural
  ?feminine
  ?locative
  ?singular
  ?genitive
  ?singular
  ?vocative
  ?singular
  ?accusative
  ?inanimate
  ?plural
  ?locative
  ?masculine
  ?singular
  ?feminine
  ?locative
  ?singular
  ?instrumental
  ?nominative
  ?plural
  ?feminine
  ?singular
  ?accusative
  ?animate
  ?nominative
  ?plural
  ?singular
  ?accusative
  ?masculine
  ?accusative
  ?plural
  ?plural
  ?locative
  ?plural
  ?instrumental
  ?masculine
  ?singular
  ?genitive
  ?masculine
  ?accusative
  ?plural
  ?masculine
  WHERE {
    ?lexeme dct:language wd:Q9058 ;
        wikibase:lexicalCategory wd:Q1084 ;
        wikibase:lemma ?nouns .
        FILTER(lang(?nouns) = "sk")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?vocativeForm .
            ?vocativeForm ontolex:representation ?vocative ;
                wikibase:grammaticalFeature wd:Q185077 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inanimateForm .
            ?inanimateForm ontolex:representation ?inanimate ;
                wikibase:grammaticalFeature wd:Q51927539 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?animateForm .
            ?animateForm ontolex:representation ?animate ;
                wikibase:grammaticalFeature wd:Q51927507 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineForm .
            ?masculineForm ontolex:representation ?masculine ;
                wikibase:grammaticalFeature wd:Q499327 .
        }
}