# tool: scribe-data
# All Norwegian (Q25164) adjectives (Q34698) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjectives
  ?superlative
  ?singularMasculineIndefinite
  ?comparative
  ?singularNeuterIndefinite
  ?singularFeminineMasculineIndefinite
  ?singularNeuter
  ?superlativeDefinite
  ?singularDefinite
  ?singularFeminineIndefinite
  ?feminineMasculineIndefiniteSingular
  ?neuterIndefiniteSingular
  ?definiteSingular
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q25164 ;
      wikibase:lexicalCategory wd:Q34698 ;
      wikibase:lemma ?adjectives ;
      schema:dateModified ?lastModified .
    
  # Note: We need to filter for nn to remove nynorsk (nn) words.
  FILTER(lang(?adjectives) = "nn")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeForm .
    ?superlativeForm ontolex:representation ?superlative ;
      wikibase:grammaticalFeature wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineIndefiniteForm .
    ?singularMasculineIndefiniteForm ontolex:representation ?singularMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comparativeForm .
    ?comparativeForm ontolex:representation ?comparative ;
      wikibase:grammaticalFeature wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterIndefiniteForm .
    ?singularNeuterIndefiniteForm ontolex:representation ?singularNeuterIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineMasculineIndefiniteForm .
    ?singularFeminineMasculineIndefiniteForm ontolex:representation ?singularFeminineMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterForm .
    ?singularNeuterForm ontolex:representation ?singularNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeDefiniteForm .
    ?superlativeDefiniteForm ontolex:representation ?superlativeDefinite ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDefiniteForm .
    ?singularDefiniteForm ontolex:representation ?singularDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineIndefiniteForm .
    ?singularFeminineIndefiniteForm ontolex:representation ?singularFeminineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculineIndefiniteSingularForm .
    ?feminineMasculineIndefiniteSingularForm ontolex:representation ?feminineMasculineIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterIndefiniteSingularForm .
    ?neuterIndefiniteSingularForm ontolex:representation ?neuterIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteSingularForm .
    ?definiteSingularForm ontolex:representation ?definiteSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q110786 .
  }
}
