# tool: scribe-data
# All english (Q1860) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?verbs
    ?simplePresentThirdPerson
  WHERE {
    ?lexeme dct:language wd:Q1860 ;
        wikibase:lexicalCategory wd:Q24905 ;
        wikibase:lemma ?verbs .
        FILTER(lang(?verbs) = "en")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?simplePresentThirdPersonForm .
            ?simplePresentThirdPersonForm ontolex:representation ?simplePresentThirdPerson ;
                wikibase:grammaticalFeature wd:Q3910936, wd:Q51929074 .
        }

}