# tool: scribe-data
# All English (Q1860) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?present
  ?future
  ?combinedPastParticiple
  ?contraction
  ?presentSubjunctive
  ?thirdPersonSingular

WHERE {
  ?lexeme dct:language wd:Q1860 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentForm .
    ?presentForm ontolex:representation ?present ;
      wikibase:grammaticalFeature wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureForm .
    ?futureForm ontolex:representation ?future ;
      wikibase:grammaticalFeature wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?combinedPastParticipleForm .
    ?combinedPastParticipleForm ontolex:representation ?combinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?contractionForm .
    ?contractionForm ontolex:representation ?contraction ;
      wikibase:grammaticalFeature wd:Q126473 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentSubjunctiveForm .
    ?presentSubjunctiveForm ontolex:representation ?presentSubjunctive ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSingularForm .
    ?thirdPersonSingularForm ontolex:representation ?thirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786 .
  }
}
