
# tool: scribe-data
# All greek (Q36510) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
   (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?verbs
    ?pastImperfect
  ?plural
  ?thirdPerson
  ?indicative
  ?plural
  ?present
  ?thirdPerson
  ?indicative
  ?plural
  ?firstPerson
  ?plural
  ?present
  ?firstPerson
  ?indicative
  ?plural
  ?present
  ?secondPerson
  ?indicative
  ?plural
  ?secondPerson
  ?singular
  ?present
  ?singular
  ?firstPerson
  ?singular
  ?past
  ?firstPerson
  ?singular
  ?secondPerson
  ?singular
  ?past
  ?firstPerson
  ?singular
  ?pastImperfect
  ?firstPerson
  ?indicative
  ?plural
  ?past
  ?thirdPerson
  ?singular
  ?past
  ?thirdPerson
  ?singular
  ?pastImperfect
  ?secondPerson
  ?indicative
  ?singular
  ?pastImperfect
  ?thirdPerson
  ?indicative
  ?singular
  ?firstPerson
  ?infinitive
  ?singular
  ?imperative
  ?secondPerson
  ?plural
  ?imperative
  ?secondPerson
  ?singular
  ?firstPerson
  ?plural
  ?past
  ?firstPerson
  ?singular
  ?past
  ?firstPerson
  ?plural
  ?past
  ?secondPerson
  ?singular
  ?past
  ?secondPerson
  ?plural
  ?thirdPerson
  ?singular
  ?present
  ?firstPerson
  ?indicative
  ?pastImperfect
  ?plural
  ?firstPerson
  ?indicative
  ?singular
  ?present
  ?thirdPerson
  ?indicative
  ?singular
  ?thirdPerson
  ?presentParticiple
  ?singular
  ?present
  ?secondPerson
  ?indicative
  ?pastImperfect
  ?plural
  ?secondPerson
  ?indicative
  WHERE {
    ?lexeme dct:language wd:Q36510 ;
        wikibase:lexicalCategory wd:Q24905 ;
        wikibase:lemma ?verbs .
        FILTER(lang(?verbs) = "el")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectForm .
            ?pastImperfectForm ontolex:representation ?pastImperfect ;
                wikibase:grammaticalFeature wd:Q12547192 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectForm .
            ?pastImperfectForm ontolex:representation ?pastImperfect ;
                wikibase:grammaticalFeature wd:Q12547192 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectForm .
            ?pastImperfectForm ontolex:representation ?pastImperfect ;
                wikibase:grammaticalFeature wd:Q12547192 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectForm .
            ?pastImperfectForm ontolex:representation ?pastImperfect ;
                wikibase:grammaticalFeature wd:Q12547192 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?imperativeForm .
            ?imperativeForm ontolex:representation ?imperative ;
                wikibase:grammaticalFeature wd:Q22716 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectForm .
            ?pastImperfectForm ontolex:representation ?pastImperfect ;
                wikibase:grammaticalFeature wd:Q12547192 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?firstPersonForm .
            ?firstPersonForm ontolex:representation ?firstPerson ;
                wikibase:grammaticalFeature wd:Q21714344 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?thirdPersonForm .
            ?thirdPersonForm ontolex:representation ?thirdPerson ;
                wikibase:grammaticalFeature wd:Q51929074 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentParticipleForm .
            ?presentParticipleForm ontolex:representation ?presentParticiple ;
                wikibase:grammaticalFeature wd:Q10345583 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?presentForm .
            ?presentForm ontolex:representation ?present ;
                wikibase:grammaticalFeature wd:Q192613 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectForm .
            ?pastImperfectForm ontolex:representation ?pastImperfect ;
                wikibase:grammaticalFeature wd:Q12547192 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?secondPersonForm .
            ?secondPersonForm ontolex:representation ?secondPerson ;
                wikibase:grammaticalFeature wd:Q51929049 .
        }
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeForm .
            ?indicativeForm ontolex:representation ?indicative ;
                wikibase:grammaticalFeature wd:Q682111 .
        }
}