# tool: scribe-data
# All Dagbani (Q32238) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?neuter
  ?pastImperfect
  ?combinedPresentParticiple
  ?adverbial
  ?phrase
  ?thirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q32238 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterForm .
    ?neuterForm ontolex:representation ?neuter ;
      wikibase:grammaticalFeature wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastImperfectForm .
    ?pastImperfectForm ontolex:representation ?pastImperfect ;
      wikibase:grammaticalFeature wd:Q12547192 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?combinedPresentParticipleForm .
    ?combinedPresentParticipleForm ontolex:representation ?combinedPresentParticiple ;
      wikibase:grammaticalFeature wd:Q10345583 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbialForm .
    ?adverbialForm ontolex:representation ?adverbial ;
      wikibase:grammaticalFeature wd:Q380012 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?phraseForm .
    ?phraseForm ontolex:representation ?phrase ;
      wikibase:grammaticalFeature wd:Q187931 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPluralForm .
    ?thirdPersonPluralForm ontolex:representation ?thirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786 .
  }
}
