# tool: scribe-data
# All Dagbani (Q32238) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?simplePresent
  ?pastImperfect
  ?presentParticiple
  ?phrase
  ?comparative
  ?thirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q32238 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentForm .
    ?simplePresentForm ontolex:representation ?simplePresent ;
      wikibase:grammaticalFeature wd:Q3910936 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastImperfectForm .
    ?pastImperfectForm ontolex:representation ?pastImperfect ;
      wikibase:grammaticalFeature wd:Q12547192 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentParticipleForm .
    ?presentParticipleForm ontolex:representation ?presentParticiple ;
      wikibase:grammaticalFeature wd:Q10345583 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?phraseForm .
    ?phraseForm ontolex:representation ?phrase ;
      wikibase:grammaticalFeature wd:Q187931 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comparativeForm .
    ?comparativeForm ontolex:representation ?comparative ;
      wikibase:grammaticalFeature wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPluralForm .
    ?thirdPersonPluralForm ontolex:representation ?thirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786 .
  }
}
