# tool: scribe-data
# All Polish (Q809) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?instrumental
  ?singular
  ?superlative
  ?masculinePersonalPlural
  ?dativeNeuterSingular
  ?dativeNeuterSingularPositive

WHERE {
  ?lexeme dct:language wd:Q809 ;
      wikibase:lexicalCategory wd:Q34698 ;
      wikibase:lemma ?adjective ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalForm .
    ?instrumentalForm ontolex:representation ?instrumental ;
      wikibase:grammaticalFeature wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeForm .
    ?superlativeForm ontolex:representation ?superlative ;
      wikibase:grammaticalFeature wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePersonalPluralForm .
    ?masculinePersonalPluralForm ontolex:representation ?masculinePersonalPlural ;
      wikibase:grammaticalFeature wd:Q27918551, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeNeuterSingularForm .
    ?dativeNeuterSingularForm ontolex:representation ?dativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeNeuterSingularPositiveForm .
    ?dativeNeuterSingularPositiveForm ontolex:representation ?dativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }
}
