# tool: scribe-data
# All Russian (Q7737) personal_pronouns (Q468801) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?personal_pronouns
  ?instrumental
  ?firstPersonAccusativeSingular
  ?prepositional
  ?firstPersonPluralNominative
  ?secondPersonDativeSingular
  ?firstPersonInstrumentalPlural
  ?dative
  ?genitiveSingular
  ?firstPersonGenitiveSingular
  ?accusativeSingular
  ?firstPersonPluralGenitive
  ?secondPersonAccusativeSingular
  ?secondPersonPluralNominative
  ?firstPersonPluralDative
  ?firstPersonPrepositionalSingular
  ?secondPersonInstrumentalPlural
  ?firstPersonNominativeSingular
  ?secondPersonGenitiveSingular
  ?genitive
  ?accusative
  ?firstPersonPrepositionalPlural
  ?nominativeSingular
  ?secondPersonPluralDative
  ?secondPersonPrepositionalSingular
  ?secondPersonNominativeSingular
  ?firstPersonPluralAccusative
  ?firstPersonDativeSingular
  ?instrumentalSingular
  ?firstPersonInstrumentalSingular
  ?prepositionalSingular
  ?secondPersonPrepositionalPlural
  ?dativeSingular
  ?nominative
  ?secondPersonPluralAccusative
  ?secondPersonInstrumentalSingular
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q7737 ;
      wikibase:lexicalCategory wd:Q468801 ;
      wikibase:lemma ?personal_pronouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalForm .
    ?instrumentalForm ontolex:representation ?instrumental ;
      wikibase:grammaticalFeature wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonAccusativeSingularForm .
    ?firstPersonAccusativeSingularForm ontolex:representation ?firstPersonAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalForm .
    ?prepositionalForm ontolex:representation ?prepositional ;
      wikibase:grammaticalFeature wd:Q2114906 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralNominativeForm .
    ?firstPersonPluralNominativeForm ontolex:representation ?firstPersonPluralNominative ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonDativeSingularForm .
    ?secondPersonDativeSingularForm ontolex:representation ?secondPersonDativeSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonInstrumentalPluralForm .
    ?firstPersonInstrumentalPluralForm ontolex:representation ?firstPersonInstrumentalPlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q192997, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeForm .
    ?dativeForm ontolex:representation ?dative ;
      wikibase:grammaticalFeature wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonGenitiveSingularForm .
    ?firstPersonGenitiveSingularForm ontolex:representation ?firstPersonGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralGenitiveForm .
    ?firstPersonPluralGenitiveForm ontolex:representation ?firstPersonPluralGenitive ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonAccusativeSingularForm .
    ?secondPersonAccusativeSingularForm ontolex:representation ?secondPersonAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPluralNominativeForm .
    ?secondPersonPluralNominativeForm ontolex:representation ?secondPersonPluralNominative ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralDativeForm .
    ?firstPersonPluralDativeForm ontolex:representation ?firstPersonPluralDative ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPrepositionalSingularForm .
    ?firstPersonPrepositionalSingularForm ontolex:representation ?firstPersonPrepositionalSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q2114906, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonInstrumentalPluralForm .
    ?secondPersonInstrumentalPluralForm ontolex:representation ?secondPersonInstrumentalPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q192997, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonNominativeSingularForm .
    ?firstPersonNominativeSingularForm ontolex:representation ?firstPersonNominativeSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonGenitiveSingularForm .
    ?secondPersonGenitiveSingularForm ontolex:representation ?secondPersonGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPrepositionalPluralForm .
    ?firstPersonPrepositionalPluralForm ontolex:representation ?firstPersonPrepositionalPlural ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q2114906, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPluralDativeForm .
    ?secondPersonPluralDativeForm ontolex:representation ?secondPersonPluralDative ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPrepositionalSingularForm .
    ?secondPersonPrepositionalSingularForm ontolex:representation ?secondPersonPrepositionalSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q2114906, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonNominativeSingularForm .
    ?secondPersonNominativeSingularForm ontolex:representation ?secondPersonNominativeSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonPluralAccusativeForm .
    ?firstPersonPluralAccusativeForm ontolex:representation ?firstPersonPluralAccusative ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonDativeSingularForm .
    ?firstPersonDativeSingularForm ontolex:representation ?firstPersonDativeSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalSingularForm .
    ?instrumentalSingularForm ontolex:representation ?instrumentalSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonInstrumentalSingularForm .
    ?firstPersonInstrumentalSingularForm ontolex:representation ?firstPersonInstrumentalSingular ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalSingularForm .
    ?prepositionalSingularForm ontolex:representation ?prepositionalSingular ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPrepositionalPluralForm .
    ?secondPersonPrepositionalPluralForm ontolex:representation ?secondPersonPrepositionalPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q2114906, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPluralAccusativeForm .
    ?secondPersonPluralAccusativeForm ontolex:representation ?secondPersonPluralAccusative ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonInstrumentalSingularForm .
    ?secondPersonInstrumentalSingularForm ontolex:representation ?secondPersonInstrumentalSingular ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q192997, wd:Q110786 .
  }
}
