# tool: scribe-data
# All Norwegian (Q25167) adjectives (Q34698) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjectives
  ?indefiniteMasculineSingular
  ?indefiniteFeminineSingular
  ?definitePlural
  ?indefiniteMasculineFeminineSingular
  ?definiteSingular
  ?indefiniteNeuterSingular
  ?definiteSuperlative
  ?indefinitePlural
  ?indefiniteSingular
  ?pluralDefinite
  ?superlativeDefinite
  ?singularIndefinite
  ?pluralIndefinite
  ?singularNeuterIndefinite
  ?singularFeminineIndefinite
  ?singularMasculineIndefinite
  ?singularFeminineMasculineIndefinite
  ?singularDefinite
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q25167 ;
      wikibase:lexicalCategory wd:Q34698 ;
      wikibase:lemma ?adjectives ;
      schema:dateModified ?lastModified .
    
  # Note: We need to filter for nb to remove bokmål (nb) words.
  FILTER(lang(?adjectives) = "nb")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineSingularForm .
    ?indefiniteMasculineSingularForm ontolex:representation ?indefiniteMasculineSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineSingularForm .
    ?indefiniteFeminineSingularForm ontolex:representation ?indefiniteFeminineSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePluralForm .
    ?definitePluralForm ontolex:representation ?definitePlural ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineFeminineSingularForm .
    ?indefiniteMasculineFeminineSingularForm ontolex:representation ?indefiniteMasculineFeminineSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteSingularForm .
    ?definiteSingularForm ontolex:representation ?definiteSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteNeuterSingularForm .
    ?indefiniteNeuterSingularForm ontolex:representation ?indefiniteNeuterSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteSuperlativeForm .
    ?definiteSuperlativeForm ontolex:representation ?definiteSuperlative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePluralForm .
    ?indefinitePluralForm ontolex:representation ?indefinitePlural ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteSingularForm .
    ?indefiniteSingularForm ontolex:representation ?indefiniteSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDefiniteForm .
    ?pluralDefiniteForm ontolex:representation ?pluralDefinite ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeDefiniteForm .
    ?superlativeDefiniteForm ontolex:representation ?superlativeDefinite ;
      wikibase:grammaticalFeature wd:Q1817208, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteForm .
    ?singularIndefiniteForm ontolex:representation ?singularIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteForm .
    ?pluralIndefiniteForm ontolex:representation ?pluralIndefinite ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterIndefiniteForm .
    ?singularNeuterIndefiniteForm ontolex:representation ?singularNeuterIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineIndefiniteForm .
    ?singularFeminineIndefiniteForm ontolex:representation ?singularFeminineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineIndefiniteForm .
    ?singularMasculineIndefiniteForm ontolex:representation ?singularMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineMasculineIndefiniteForm .
    ?singularFeminineMasculineIndefiniteForm ontolex:representation ?singularFeminineMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDefiniteForm .
    ?singularDefiniteForm ontolex:representation ?singularDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997851 .
  }
}
