# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nouns
  ?participlePerfectNeuterPluralGenitivePassive
  ?participleFutureMasculineDativeActiveSingular
  ?participlePerfectFemininePluralNominativePassive
  ?neuterPluralGenitive
  ?participleFutureNeuterDativePassiveSingular
  ?participleFutureNeuterPluralAccusativeActive
  ?pluralGenitiveCommon
  ?participlePerfectAblativePluralPassive
  ?ablativePlural
  ?participlePerfectVocativeNeuterPluralPassive
  ?participleFutureVocativeNeuterPassiveSingular
  ?participlePerfectVocativeNeuterPassiveSingular
  ?vocativeAccusativeNominativeSingular
  ?participleFutureMasculineVocativePassiveSingular
  ?participleFutureVocativeFeminineActiveSingular
  ?participleFutureMasculineGenitivePassiveSingular
  ?participlePresentNeuterPluralActiveNominative
  ?ablativePluralCommon
  ?nominativeCommonSingular
  ?genitiveCommonSingular
  ?masculineNominativeSingular
  ?femininePluralDative
  ?participleFutureVocativeFemininePassiveSingular
  ?participlePerfectVocativeFemininePassiveSingular
  ?accusativeSingular
  ?dative
  ?participleFutureNeuterPluralActiveNominative
  ?participlePresentNeuterPluralAccusativeActive
  ?vocativePluralAccusativeNominative
  ?masculineAblativePlural
  ?feminineAblativeSingular
  ?pluralNominativeCommon
  ?participleFutureMasculinePluralGenitivePassive
  ?common
  ?participleFutureNeuterActiveNominativeSingular
  ?feminineDativeSingular
  ?vocativeFeminineSingular
  ?vocativePluralCommon
  ?participlePresentAblativePluralActive
  ?participleFutureAblativePluralPassive
  ?participleFutureFeminineNominativePassiveSingular
  ?accusative
  ?presentIndicativeFirstPersonActiveSingular
  ?participleFutureMasculinePluralActiveNominative
  ?participleFutureNeuterPluralGenitiveActive
  ?vocativeNeuterSingular
  ?pluralAccusative
  ?participleFutureFeminineGenitivePassiveSingular
  ?masculinePluralAccusative
  ?neuterGenitiveSingular
  ?participlePresentAblativeActiveSingular
  ?vocativeCommonSingular
  ?presentInfinitiveActive
  ?feminineGenitiveSingular
  ?participlePerfectNeuterGenitivePassiveSingular
  ?neuterAccusativeSingular
  ?participlePerfectNeuterNominativePassiveSingular
  ?participlePresentPluralAccusativeActiveCommon
  ?participlePerfectMasculineDativePassiveSingular
  ?participleFutureFemininePluralGenitivePassive
  ?participlePerfectPluralDativePassive
  ?ablativeDativeSingular
  ?nominativeSingular
  ?genitiveSingular
  ?participleFutureFemininePluralActiveNominative
  ?participleFutureMasculineNominativePassiveSingular
  ?participlePerfectMasculineNominativePassiveSingular
  ?neuterNominativeSingular
  ?participleFutureNeuterGenitiveActiveSingular
  ?participleFutureNeuterPluralNominativePassive
  ?participlePerfectVocativeFemininePluralPassive
  ?participleFutureMasculineVocativeActiveSingular
  ?feminineNominativeSingular
  ?participleFutureNeuterAblativeActiveSingular
  ?ablativeSingular
  ?nominative
  ?genitive
  ?neuterAblativePlural
  ?participlePresentGenitiveActiveSingular
  ?masculine
  ?locativeFemininePlural
  ?masculineAccusativeSingular
  ?participleFutureFemininePluralAccusativePassive
  ?participleFutureNeuterAccusativePassiveSingular
  ?participlePresentDativeActiveSingular
  ?participlePerfectNeuterDativePassiveSingular
  ?participlePerfectFemininePluralAccusativePassive
  ?feminineAblativePlural
  ?femininePluralGenitive
  ?neuterPluralAccusative
  ?participlePresentPluralActiveNominativeCommon
  ?vocativeSingular
  ?pluralAccusativeCommon
  ?participlePerfectMasculineVocativePassiveSingular
  ?vocativeNeuterPlural
  ?participlePerfectMasculineGenitivePassiveSingular
  ?participleFutureMasculineAccusativeActiveSingular
  ?participlePresentActiveNominativeSingular
  ?participleFutureFeminineAccusativePassiveSingular
  ?participlePerfectFeminineAccusativePassiveSingular
  ?locativePlural
  ?vocative
  ?participleFutureMasculinePluralAccusativePassive
  ?participlePerfectMasculinePluralGenitivePassive
  ?locativeFeminineSingular
  ?locativePluralCommon
  ?ablativeCommonSingular
  ?participleFuturePluralDativeActive
  ?masculinePluralNominative
  ?participleFutureMasculinePluralNominativePassive
  ?participleFutureFeminineAblativePassiveSingular
  ?masculineLocativeSingular
  ?locativeNeuterSingular
  ?participlePerfectFeminineNominativePassiveSingular
  ?participlePerfectFeminineGenitivePassiveSingular
  ?participleFutureNeuterAccusativeActiveSingular
  ?pluralDative
  ?participleFutureFeminineAccusativeActiveSingular
  ?participlePresentAccusativeActiveCommonSingular
  ?participleFutureMasculineAccusativePassiveSingular
  ?participleFutureMasculineVocativePluralActive
  ?participleFutureMasculineVocativePluralPassive
  ?participleFutureNeuterPluralAccusativePassive
  ?neuter
  ?participlePresentPluralDativeActive
  ?participleFutureFeminineGenitiveActiveSingular
  ?participlePerfectFemininePluralGenitivePassive
  ?participleFutureFemininePluralAccusativeActive
  ?participleFutureNeuterPluralGenitivePassive
  ?participleFutureMasculineActiveNominativeSingular
  ?feminine
  ?participleFutureFemininePluralNominativePassive
  ?feminineAccusativeSingular
  ?vocativeFemininePlural
  ?participlePresentNeuterAccusativeActiveSingular
  ?participleFutureFeminineAblativeActiveSingular
  ?dativeSingular
  ?participleFutureVocativeNeuterPluralPassive
  ?participlePerfectNeuterPluralNominativePassive
  ?neuterPluralDative
  ?masculineVocativePlural
  ?participleFutureVocativeNeuterPluralActive
  ?singular
  ?neuterAblativeSingular
  ?participleFutureNeuterNominativePassiveSingular
  ?participleFutureVocativeFemininePluralActive
  ?neuterDativeSingular
  ?neuterPluralNominative
  ?participlePerfectNeuterAccusativePassiveSingular
  ?participleFutureFeminineActiveNominativeSingular
  ?allativeSingular
  ?supineNeuterAblativeSingular
  ?vocativePlural
  ?participleFutureMasculineAblativePassiveSingular
  ?participlePerfectMasculineAblativePassiveSingular
  ?participlePresentVocativePluralActiveCommon
  ?participleFutureMasculinePluralGenitiveActive
  ?ablative
  ?femininePluralNominative
  ?locativeSingular
  ?masculinePluralGenitive
  ?masculineLocativePlural
  ?locativeNeuterPlural
  ?participlePresentVocativeNeuterPluralActive
  ?participlePerfectNeuterAblativePassiveSingular
  ?participlePresentPluralGenitiveActive
  ?pluralDativeCommon
  ?femininePluralAccusative
  ?masculinePluralDative
  ?dativeCommonSingular
  ?participleFutureMasculineGenitiveActiveSingular
  ?participlePerfectMasculinePluralAccusativePassive
  ?masculineAblativeSingular
  ?ablativePluralDative
  ?participleFutureNeuterGenitivePassiveSingular
  ?participleFutureMasculineDativePassiveSingular
  ?participleFutureVocativeNeuterActiveSingular
  ?participleFutureMasculinePluralAccusativeActive
  ?participlePresentVocativeActiveSingular
  ?masculineDativeSingular
  ?participlePerfectMasculinePluralNominativePassive
  ?participlePerfectFeminineAblativePassiveSingular
  ?accusativeCommonSingular
  ?participleFutureFemininePluralGenitiveActive
  ?participleFutureFeminineDativeActiveSingular
  ?participleFutureNeuterAblativePassiveSingular
  ?participleFutureMasculineAblativeActiveSingular
  ?presentIndicativeThirdPersonActiveSingular
  ?locativeCommonSingular
  ?participleFutureAblativePluralActive
  ?participleFutureNeuterDativeActiveSingular
  ?masculineVocativeSingular
  ?participlePerfectMasculineAccusativePassiveSingular
  ?supineNeuterAccusativeSingular
  ?participleFutureVocativeFemininePluralPassive
  ?participlePerfectMasculineVocativePluralPassive
  ?participlePerfectNeuterPluralAccusativePassive
  ?masculineGenitiveSingular
  ?participleFuturePluralDativePassive
  ?participlePerfectFeminineDativePassiveSingular
  ?participleFutureFeminineDativePassiveSingular
  ?singularGenitive
  ?singularAblative
  ?pluralAblative
  ?singularNominative
   ?lastModified

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterPluralGenitivePassiveForm .
    ?participlePerfectNeuterPluralGenitivePassiveForm ontolex:representation ?participlePerfectNeuterPluralGenitivePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q146786, wd:Q146233, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineDativeActiveSingularForm .
    ?participleFutureMasculineDativeActiveSingularForm ontolex:representation ?participleFutureMasculineDativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q145599, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFemininePluralNominativePassiveForm .
    ?participlePerfectFemininePluralNominativePassiveForm ontolex:representation ?participlePerfectFemininePluralNominativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q146786, wd:Q131105, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralGenitiveForm .
    ?neuterPluralGenitiveForm ontolex:representation ?neuterPluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterDativePassiveSingularForm .
    ?participleFutureNeuterDativePassiveSingularForm ontolex:representation ?participleFutureNeuterDativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q145599, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterPluralAccusativeActiveForm .
    ?participleFutureNeuterPluralAccusativeActiveForm ontolex:representation ?participleFutureNeuterPluralAccusativeActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146786, wd:Q146078, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralGenitiveCommonForm .
    ?pluralGenitiveCommonForm ontolex:representation ?pluralGenitiveCommon ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146233, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectAblativePluralPassiveForm .
    ?participlePerfectAblativePluralPassiveForm ontolex:representation ?participlePerfectAblativePluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q156986, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralForm .
    ?ablativePluralForm ontolex:representation ?ablativePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectVocativeNeuterPluralPassiveForm .
    ?participlePerfectVocativeNeuterPluralPassiveForm ontolex:representation ?participlePerfectVocativeNeuterPluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q185077, wd:Q1775461, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeNeuterPassiveSingularForm .
    ?participleFutureVocativeNeuterPassiveSingularForm ontolex:representation ?participleFutureVocativeNeuterPassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775461, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectVocativeNeuterPassiveSingularForm .
    ?participlePerfectVocativeNeuterPassiveSingularForm ontolex:representation ?participlePerfectVocativeNeuterPassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q185077, wd:Q1775461, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeAccusativeNominativeSingularForm .
    ?vocativeAccusativeNominativeSingularForm ontolex:representation ?vocativeAccusativeNominativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q146078, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineVocativePassiveSingularForm .
    ?participleFutureMasculineVocativePassiveSingularForm ontolex:representation ?participleFutureMasculineVocativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q185077, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeFeminineActiveSingularForm .
    ?participleFutureVocativeFeminineActiveSingularForm ontolex:representation ?participleFutureVocativeFeminineActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775415, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineGenitivePassiveSingularForm .
    ?participleFutureMasculineGenitivePassiveSingularForm ontolex:representation ?participleFutureMasculineGenitivePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentNeuterPluralActiveNominativeForm .
    ?participlePresentNeuterPluralActiveNominativeForm ontolex:representation ?participlePresentNeuterPluralActiveNominative ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q1775461, wd:Q146786, wd:Q1317831, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralCommonForm .
    ?ablativePluralCommonForm ontolex:representation ?ablativePluralCommon ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeCommonSingularForm .
    ?nominativeCommonSingularForm ontolex:representation ?nominativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveCommonSingularForm .
    ?genitiveCommonSingularForm ontolex:representation ?genitiveCommonSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineNominativeSingularForm .
    ?masculineNominativeSingularForm ontolex:representation ?masculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralDativeForm .
    ?femininePluralDativeForm ontolex:representation ?femininePluralDative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeFemininePassiveSingularForm .
    ?participleFutureVocativeFemininePassiveSingularForm ontolex:representation ?participleFutureVocativeFemininePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775415, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectVocativeFemininePassiveSingularForm .
    ?participlePerfectVocativeFemininePassiveSingularForm ontolex:representation ?participlePerfectVocativeFemininePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q185077, wd:Q1775415, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeForm .
    ?dativeForm ontolex:representation ?dative ;
      wikibase:grammaticalFeature wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterPluralActiveNominativeForm .
    ?participleFutureNeuterPluralActiveNominativeForm ontolex:representation ?participleFutureNeuterPluralActiveNominative ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146786, wd:Q1317831, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentNeuterPluralAccusativeActiveForm .
    ?participlePresentNeuterPluralAccusativeActiveForm ontolex:representation ?participlePresentNeuterPluralAccusativeActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q1775461, wd:Q146786, wd:Q146078, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativePluralAccusativeNominativeForm .
    ?vocativePluralAccusativeNominativeForm ontolex:representation ?vocativePluralAccusativeNominative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q146786, wd:Q146078, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAblativePluralForm .
    ?masculineAblativePluralForm ontolex:representation ?masculineAblativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAblativeSingularForm .
    ?feminineAblativeSingularForm ontolex:representation ?feminineAblativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralNominativeCommonForm .
    ?pluralNominativeCommonForm ontolex:representation ?pluralNominativeCommon ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q131105, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculinePluralGenitivePassiveForm .
    ?participleFutureMasculinePluralGenitivePassiveForm ontolex:representation ?participleFutureMasculinePluralGenitivePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146786, wd:Q146233, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?commonForm .
    ?commonForm ontolex:representation ?common ;
      wikibase:grammaticalFeature wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterActiveNominativeSingularForm .
    ?participleFutureNeuterActiveNominativeSingularForm ontolex:representation ?participleFutureNeuterActiveNominativeSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q1317831, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineDativeSingularForm .
    ?feminineDativeSingularForm ontolex:representation ?feminineDativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFeminineSingularForm .
    ?vocativeFeminineSingularForm ontolex:representation ?vocativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativePluralCommonForm .
    ?vocativePluralCommonForm ontolex:representation ?vocativePluralCommon ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q146786, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentAblativePluralActiveForm .
    ?participlePresentAblativePluralActiveForm ontolex:representation ?participlePresentAblativePluralActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q156986, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureAblativePluralPassiveForm .
    ?participleFutureAblativePluralPassiveForm ontolex:representation ?participleFutureAblativePluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q156986, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineNominativePassiveSingularForm .
    ?participleFutureFeminineNominativePassiveSingularForm ontolex:representation ?participleFutureFeminineNominativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q131105, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentIndicativeFirstPersonActiveSingularForm .
    ?presentIndicativeFirstPersonActiveSingularForm ontolex:representation ?presentIndicativeFirstPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q56682909, wd:Q21714344, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculinePluralActiveNominativeForm .
    ?participleFutureMasculinePluralActiveNominativeForm ontolex:representation ?participleFutureMasculinePluralActiveNominative ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146786, wd:Q1317831, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterPluralGenitiveActiveForm .
    ?participleFutureNeuterPluralGenitiveActiveForm ontolex:representation ?participleFutureNeuterPluralGenitiveActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146786, wd:Q146233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularForm .
    ?vocativeNeuterSingularForm ontolex:representation ?vocativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAccusativeForm .
    ?pluralAccusativeForm ontolex:representation ?pluralAccusative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineGenitivePassiveSingularForm .
    ?participleFutureFeminineGenitivePassiveSingularForm ontolex:representation ?participleFutureFeminineGenitivePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralAccusativeForm .
    ?masculinePluralAccusativeForm ontolex:representation ?masculinePluralAccusative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterGenitiveSingularForm .
    ?neuterGenitiveSingularForm ontolex:representation ?neuterGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentAblativeActiveSingularForm .
    ?participlePresentAblativeActiveSingularForm ontolex:representation ?participlePresentAblativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q156986, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeCommonSingularForm .
    ?vocativeCommonSingularForm ontolex:representation ?vocativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentInfinitiveActiveForm .
    ?presentInfinitiveActiveForm ontolex:representation ?presentInfinitiveActive ;
      wikibase:grammaticalFeature wd:Q52434245, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineGenitiveSingularForm .
    ?feminineGenitiveSingularForm ontolex:representation ?feminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterGenitivePassiveSingularForm .
    ?participlePerfectNeuterGenitivePassiveSingularForm ontolex:representation ?participlePerfectNeuterGenitivePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q146233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterAccusativeSingularForm .
    ?neuterAccusativeSingularForm ontolex:representation ?neuterAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterNominativePassiveSingularForm .
    ?participlePerfectNeuterNominativePassiveSingularForm ontolex:representation ?participlePerfectNeuterNominativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q131105, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentPluralAccusativeActiveCommonForm .
    ?participlePresentPluralAccusativeActiveCommonForm ontolex:representation ?participlePresentPluralAccusativeActiveCommon ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q146786, wd:Q146078, wd:Q1317831, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineDativePassiveSingularForm .
    ?participlePerfectMasculineDativePassiveSingularForm ontolex:representation ?participlePerfectMasculineDativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q145599, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFemininePluralGenitivePassiveForm .
    ?participleFutureFemininePluralGenitivePassiveForm ontolex:representation ?participleFutureFemininePluralGenitivePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146786, wd:Q146233, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectPluralDativePassiveForm .
    ?participlePerfectPluralDativePassiveForm ontolex:representation ?participlePerfectPluralDativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q146786, wd:Q145599, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeDativeSingularForm .
    ?ablativeDativeSingularForm ontolex:representation ?ablativeDativeSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFemininePluralActiveNominativeForm .
    ?participleFutureFemininePluralActiveNominativeForm ontolex:representation ?participleFutureFemininePluralActiveNominative ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146786, wd:Q1317831, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineNominativePassiveSingularForm .
    ?participleFutureMasculineNominativePassiveSingularForm ontolex:representation ?participleFutureMasculineNominativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q131105, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineNominativePassiveSingularForm .
    ?participlePerfectMasculineNominativePassiveSingularForm ontolex:representation ?participlePerfectMasculineNominativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q131105, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterNominativeSingularForm .
    ?neuterNominativeSingularForm ontolex:representation ?neuterNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterGenitiveActiveSingularForm .
    ?participleFutureNeuterGenitiveActiveSingularForm ontolex:representation ?participleFutureNeuterGenitiveActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146233, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterPluralNominativePassiveForm .
    ?participleFutureNeuterPluralNominativePassiveForm ontolex:representation ?participleFutureNeuterPluralNominativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146786, wd:Q131105, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectVocativeFemininePluralPassiveForm .
    ?participlePerfectVocativeFemininePluralPassiveForm ontolex:representation ?participlePerfectVocativeFemininePluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q185077, wd:Q1775415, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineVocativeActiveSingularForm .
    ?participleFutureMasculineVocativeActiveSingularForm ontolex:representation ?participleFutureMasculineVocativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q185077, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineNominativeSingularForm .
    ?feminineNominativeSingularForm ontolex:representation ?feminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterAblativeActiveSingularForm .
    ?participleFutureNeuterAblativeActiveSingularForm ontolex:representation ?participleFutureNeuterAblativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q156986, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeSingularForm .
    ?ablativeSingularForm ontolex:representation ?ablativeSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterAblativePluralForm .
    ?neuterAblativePluralForm ontolex:representation ?neuterAblativePlural ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentGenitiveActiveSingularForm .
    ?participlePresentGenitiveActiveSingularForm ontolex:representation ?participlePresentGenitiveActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q146233, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineForm .
    ?masculineForm ontolex:representation ?masculine ;
      wikibase:grammaticalFeature wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralForm .
    ?locativeFemininePluralForm ontolex:representation ?locativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFemininePluralAccusativePassiveForm .
    ?participleFutureFemininePluralAccusativePassiveForm ontolex:representation ?participleFutureFemininePluralAccusativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146786, wd:Q146078, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterAccusativePassiveSingularForm .
    ?participleFutureNeuterAccusativePassiveSingularForm ontolex:representation ?participleFutureNeuterAccusativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146078, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentDativeActiveSingularForm .
    ?participlePresentDativeActiveSingularForm ontolex:representation ?participlePresentDativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q145599, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterDativePassiveSingularForm .
    ?participlePerfectNeuterDativePassiveSingularForm ontolex:representation ?participlePerfectNeuterDativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q145599, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFemininePluralAccusativePassiveForm .
    ?participlePerfectFemininePluralAccusativePassiveForm ontolex:representation ?participlePerfectFemininePluralAccusativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q146786, wd:Q146078, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAblativePluralForm .
    ?feminineAblativePluralForm ontolex:representation ?feminineAblativePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralGenitiveForm .
    ?femininePluralGenitiveForm ontolex:representation ?femininePluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralAccusativeForm .
    ?neuterPluralAccusativeForm ontolex:representation ?neuterPluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentPluralActiveNominativeCommonForm .
    ?participlePresentPluralActiveNominativeCommonForm ontolex:representation ?participlePresentPluralActiveNominativeCommon ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q146786, wd:Q1317831, wd:Q131105, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeSingularForm .
    ?vocativeSingularForm ontolex:representation ?vocativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAccusativeCommonForm .
    ?pluralAccusativeCommonForm ontolex:representation ?pluralAccusativeCommon ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146078, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineVocativePassiveSingularForm .
    ?participlePerfectMasculineVocativePassiveSingularForm ontolex:representation ?participlePerfectMasculineVocativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q185077, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterPluralForm .
    ?vocativeNeuterPluralForm ontolex:representation ?vocativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineGenitivePassiveSingularForm .
    ?participlePerfectMasculineGenitivePassiveSingularForm ontolex:representation ?participlePerfectMasculineGenitivePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q146233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineAccusativeActiveSingularForm .
    ?participleFutureMasculineAccusativeActiveSingularForm ontolex:representation ?participleFutureMasculineAccusativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146078, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentActiveNominativeSingularForm .
    ?participlePresentActiveNominativeSingularForm ontolex:representation ?participlePresentActiveNominativeSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q1317831, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineAccusativePassiveSingularForm .
    ?participleFutureFeminineAccusativePassiveSingularForm ontolex:representation ?participleFutureFeminineAccusativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146078, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFeminineAccusativePassiveSingularForm .
    ?participlePerfectFeminineAccusativePassiveSingularForm ontolex:representation ?participlePerfectFeminineAccusativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q146078, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativePluralForm .
    ?locativePluralForm ontolex:representation ?locativePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeForm .
    ?vocativeForm ontolex:representation ?vocative ;
      wikibase:grammaticalFeature wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculinePluralAccusativePassiveForm .
    ?participleFutureMasculinePluralAccusativePassiveForm ontolex:representation ?participleFutureMasculinePluralAccusativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146786, wd:Q146078, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculinePluralGenitivePassiveForm .
    ?participlePerfectMasculinePluralGenitivePassiveForm ontolex:representation ?participlePerfectMasculinePluralGenitivePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q146786, wd:Q146233, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularForm .
    ?locativeFeminineSingularForm ontolex:representation ?locativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativePluralCommonForm .
    ?locativePluralCommonForm ontolex:representation ?locativePluralCommon ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q146786, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeCommonSingularForm .
    ?ablativeCommonSingularForm ontolex:representation ?ablativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFuturePluralDativeActiveForm .
    ?participleFuturePluralDativeActiveForm ontolex:representation ?participleFuturePluralDativeActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q146786, wd:Q145599, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralNominativeForm .
    ?masculinePluralNominativeForm ontolex:representation ?masculinePluralNominative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculinePluralNominativePassiveForm .
    ?participleFutureMasculinePluralNominativePassiveForm ontolex:representation ?participleFutureMasculinePluralNominativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146786, wd:Q131105, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineAblativePassiveSingularForm .
    ?participleFutureFeminineAblativePassiveSingularForm ontolex:representation ?participleFutureFeminineAblativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q156986, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineLocativeSingularForm .
    ?masculineLocativeSingularForm ontolex:representation ?masculineLocativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularForm .
    ?locativeNeuterSingularForm ontolex:representation ?locativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFeminineNominativePassiveSingularForm .
    ?participlePerfectFeminineNominativePassiveSingularForm ontolex:representation ?participlePerfectFeminineNominativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q131105, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFeminineGenitivePassiveSingularForm .
    ?participlePerfectFeminineGenitivePassiveSingularForm ontolex:representation ?participlePerfectFeminineGenitivePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q146233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterAccusativeActiveSingularForm .
    ?participleFutureNeuterAccusativeActiveSingularForm ontolex:representation ?participleFutureNeuterAccusativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146078, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDativeForm .
    ?pluralDativeForm ontolex:representation ?pluralDative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineAccusativeActiveSingularForm .
    ?participleFutureFeminineAccusativeActiveSingularForm ontolex:representation ?participleFutureFeminineAccusativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146078, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentAccusativeActiveCommonSingularForm .
    ?participlePresentAccusativeActiveCommonSingularForm ontolex:representation ?participlePresentAccusativeActiveCommonSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q146078, wd:Q1317831, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineAccusativePassiveSingularForm .
    ?participleFutureMasculineAccusativePassiveSingularForm ontolex:representation ?participleFutureMasculineAccusativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146078, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineVocativePluralActiveForm .
    ?participleFutureMasculineVocativePluralActiveForm ontolex:representation ?participleFutureMasculineVocativePluralActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q185077, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineVocativePluralPassiveForm .
    ?participleFutureMasculineVocativePluralPassiveForm ontolex:representation ?participleFutureMasculineVocativePluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q185077, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterPluralAccusativePassiveForm .
    ?participleFutureNeuterPluralAccusativePassiveForm ontolex:representation ?participleFutureNeuterPluralAccusativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146786, wd:Q146078, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterForm .
    ?neuterForm ontolex:representation ?neuter ;
      wikibase:grammaticalFeature wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentPluralDativeActiveForm .
    ?participlePresentPluralDativeActiveForm ontolex:representation ?participlePresentPluralDativeActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q146786, wd:Q145599, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineGenitiveActiveSingularForm .
    ?participleFutureFeminineGenitiveActiveSingularForm ontolex:representation ?participleFutureFeminineGenitiveActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146233, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFemininePluralGenitivePassiveForm .
    ?participlePerfectFemininePluralGenitivePassiveForm ontolex:representation ?participlePerfectFemininePluralGenitivePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q146786, wd:Q146233, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFemininePluralAccusativeActiveForm .
    ?participleFutureFemininePluralAccusativeActiveForm ontolex:representation ?participleFutureFemininePluralAccusativeActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146786, wd:Q146078, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterPluralGenitivePassiveForm .
    ?participleFutureNeuterPluralGenitivePassiveForm ontolex:representation ?participleFutureNeuterPluralGenitivePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146786, wd:Q146233, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineActiveNominativeSingularForm .
    ?participleFutureMasculineActiveNominativeSingularForm ontolex:representation ?participleFutureMasculineActiveNominativeSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q1317831, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineForm .
    ?feminineForm ontolex:representation ?feminine ;
      wikibase:grammaticalFeature wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFemininePluralNominativePassiveForm .
    ?participleFutureFemininePluralNominativePassiveForm ontolex:representation ?participleFutureFemininePluralNominativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146786, wd:Q131105, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeSingularForm .
    ?feminineAccusativeSingularForm ontolex:representation ?feminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFemininePluralForm .
    ?vocativeFemininePluralForm ontolex:representation ?vocativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentNeuterAccusativeActiveSingularForm .
    ?participlePresentNeuterAccusativeActiveSingularForm ontolex:representation ?participlePresentNeuterAccusativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q1775461, wd:Q146078, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineAblativeActiveSingularForm .
    ?participleFutureFeminineAblativeActiveSingularForm ontolex:representation ?participleFutureFeminineAblativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q156986, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeNeuterPluralPassiveForm .
    ?participleFutureVocativeNeuterPluralPassiveForm ontolex:representation ?participleFutureVocativeNeuterPluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775461, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterPluralNominativePassiveForm .
    ?participlePerfectNeuterPluralNominativePassiveForm ontolex:representation ?participlePerfectNeuterPluralNominativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q146786, wd:Q131105, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralDativeForm .
    ?neuterPluralDativeForm ontolex:representation ?neuterPluralDative ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineVocativePluralForm .
    ?masculineVocativePluralForm ontolex:representation ?masculineVocativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q185077, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeNeuterPluralActiveForm .
    ?participleFutureVocativeNeuterPluralActiveForm ontolex:representation ?participleFutureVocativeNeuterPluralActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775461, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterAblativeSingularForm .
    ?neuterAblativeSingularForm ontolex:representation ?neuterAblativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterNominativePassiveSingularForm .
    ?participleFutureNeuterNominativePassiveSingularForm ontolex:representation ?participleFutureNeuterNominativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q131105, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeFemininePluralActiveForm .
    ?participleFutureVocativeFemininePluralActiveForm ontolex:representation ?participleFutureVocativeFemininePluralActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775415, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterDativeSingularForm .
    ?neuterDativeSingularForm ontolex:representation ?neuterDativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralNominativeForm .
    ?neuterPluralNominativeForm ontolex:representation ?neuterPluralNominative ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterAccusativePassiveSingularForm .
    ?participlePerfectNeuterAccusativePassiveSingularForm ontolex:representation ?participlePerfectNeuterAccusativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q146078, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineActiveNominativeSingularForm .
    ?participleFutureFeminineActiveNominativeSingularForm ontolex:representation ?participleFutureFeminineActiveNominativeSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q1317831, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeSingularForm .
    ?allativeSingularForm ontolex:representation ?allativeSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?supineNeuterAblativeSingularForm .
    ?supineNeuterAblativeSingularForm ontolex:representation ?supineNeuterAblativeSingular ;
      wikibase:grammaticalFeature wd:Q548470, wd:Q1775461, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativePluralForm .
    ?vocativePluralForm ontolex:representation ?vocativePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineAblativePassiveSingularForm .
    ?participleFutureMasculineAblativePassiveSingularForm ontolex:representation ?participleFutureMasculineAblativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q156986, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineAblativePassiveSingularForm .
    ?participlePerfectMasculineAblativePassiveSingularForm ontolex:representation ?participlePerfectMasculineAblativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q156986, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentVocativePluralActiveCommonForm .
    ?participlePresentVocativePluralActiveCommonForm ontolex:representation ?participlePresentVocativePluralActiveCommon ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q185077, wd:Q146786, wd:Q1317831, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculinePluralGenitiveActiveForm .
    ?participleFutureMasculinePluralGenitiveActiveForm ontolex:representation ?participleFutureMasculinePluralGenitiveActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146786, wd:Q146233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeForm .
    ?ablativeForm ontolex:representation ?ablative ;
      wikibase:grammaticalFeature wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralNominativeForm .
    ?femininePluralNominativeForm ontolex:representation ?femininePluralNominative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralGenitiveForm .
    ?masculinePluralGenitiveForm ontolex:representation ?masculinePluralGenitive ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineLocativePluralForm .
    ?masculineLocativePluralForm ontolex:representation ?masculineLocativePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralForm .
    ?locativeNeuterPluralForm ontolex:representation ?locativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentVocativeNeuterPluralActiveForm .
    ?participlePresentVocativeNeuterPluralActiveForm ontolex:representation ?participlePresentVocativeNeuterPluralActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q185077, wd:Q1775461, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterAblativePassiveSingularForm .
    ?participlePerfectNeuterAblativePassiveSingularForm ontolex:representation ?participlePerfectNeuterAblativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q156986, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentPluralGenitiveActiveForm .
    ?participlePresentPluralGenitiveActiveForm ontolex:representation ?participlePresentPluralGenitiveActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q146786, wd:Q146233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDativeCommonForm .
    ?pluralDativeCommonForm ontolex:representation ?pluralDativeCommon ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q145599, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralAccusativeForm .
    ?femininePluralAccusativeForm ontolex:representation ?femininePluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralDativeForm .
    ?masculinePluralDativeForm ontolex:representation ?masculinePluralDative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeCommonSingularForm .
    ?dativeCommonSingularForm ontolex:representation ?dativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineGenitiveActiveSingularForm .
    ?participleFutureMasculineGenitiveActiveSingularForm ontolex:representation ?participleFutureMasculineGenitiveActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146233, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculinePluralAccusativePassiveForm .
    ?participlePerfectMasculinePluralAccusativePassiveForm ontolex:representation ?participlePerfectMasculinePluralAccusativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q146786, wd:Q146078, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAblativeSingularForm .
    ?masculineAblativeSingularForm ontolex:representation ?masculineAblativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralDativeForm .
    ?ablativePluralDativeForm ontolex:representation ?ablativePluralDative ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterGenitivePassiveSingularForm .
    ?participleFutureNeuterGenitivePassiveSingularForm ontolex:representation ?participleFutureNeuterGenitivePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q146233, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineDativePassiveSingularForm .
    ?participleFutureMasculineDativePassiveSingularForm ontolex:representation ?participleFutureMasculineDativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q145599, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeNeuterActiveSingularForm .
    ?participleFutureVocativeNeuterActiveSingularForm ontolex:representation ?participleFutureVocativeNeuterActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775461, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculinePluralAccusativeActiveForm .
    ?participleFutureMasculinePluralAccusativeActiveForm ontolex:representation ?participleFutureMasculinePluralAccusativeActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q146786, wd:Q146078, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePresentVocativeActiveSingularForm .
    ?participlePresentVocativeActiveSingularForm ontolex:representation ?participlePresentVocativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q192613, wd:Q185077, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDativeSingularForm .
    ?masculineDativeSingularForm ontolex:representation ?masculineDativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculinePluralNominativePassiveForm .
    ?participlePerfectMasculinePluralNominativePassiveForm ontolex:representation ?participlePerfectMasculinePluralNominativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q146786, wd:Q131105, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFeminineAblativePassiveSingularForm .
    ?participlePerfectFeminineAblativePassiveSingularForm ontolex:representation ?participlePerfectFeminineAblativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q156986, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeCommonSingularForm .
    ?accusativeCommonSingularForm ontolex:representation ?accusativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFemininePluralGenitiveActiveForm .
    ?participleFutureFemininePluralGenitiveActiveForm ontolex:representation ?participleFutureFemininePluralGenitiveActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q146786, wd:Q146233, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineDativeActiveSingularForm .
    ?participleFutureFeminineDativeActiveSingularForm ontolex:representation ?participleFutureFeminineDativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q145599, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterAblativePassiveSingularForm .
    ?participleFutureNeuterAblativePassiveSingularForm ontolex:representation ?participleFutureNeuterAblativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q156986, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureMasculineAblativeActiveSingularForm .
    ?participleFutureMasculineAblativeActiveSingularForm ontolex:representation ?participleFutureMasculineAblativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q499327, wd:Q156986, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentIndicativeThirdPersonActiveSingularForm .
    ?presentIndicativeThirdPersonActiveSingularForm ontolex:representation ?presentIndicativeThirdPersonActiveSingular ;
      wikibase:grammaticalFeature wd:Q56682909, wd:Q51929074, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeCommonSingularForm .
    ?locativeCommonSingularForm ontolex:representation ?locativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureAblativePluralActiveForm .
    ?participleFutureAblativePluralActiveForm ontolex:representation ?participleFutureAblativePluralActive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q156986, wd:Q146786, wd:Q1317831 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureNeuterDativeActiveSingularForm .
    ?participleFutureNeuterDativeActiveSingularForm ontolex:representation ?participleFutureNeuterDativeActiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775461, wd:Q145599, wd:Q1317831, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineVocativeSingularForm .
    ?masculineVocativeSingularForm ontolex:representation ?masculineVocativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineAccusativePassiveSingularForm .
    ?participlePerfectMasculineAccusativePassiveSingularForm ontolex:representation ?participlePerfectMasculineAccusativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q146078, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?supineNeuterAccusativeSingularForm .
    ?supineNeuterAccusativeSingularForm ontolex:representation ?supineNeuterAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q548470, wd:Q1775461, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureVocativeFemininePluralPassiveForm .
    ?participleFutureVocativeFemininePluralPassiveForm ontolex:representation ?participleFutureVocativeFemininePluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q185077, wd:Q1775415, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectMasculineVocativePluralPassiveForm .
    ?participlePerfectMasculineVocativePluralPassiveForm ontolex:representation ?participlePerfectMasculineVocativePluralPassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q499327, wd:Q185077, wd:Q146786, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectNeuterPluralAccusativePassiveForm .
    ?participlePerfectNeuterPluralAccusativePassiveForm ontolex:representation ?participlePerfectNeuterPluralAccusativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775461, wd:Q146786, wd:Q146078, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveSingularForm .
    ?masculineGenitiveSingularForm ontolex:representation ?masculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFuturePluralDativePassiveForm .
    ?participleFuturePluralDativePassiveForm ontolex:representation ?participleFuturePluralDativePassive ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q146786, wd:Q145599, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participlePerfectFeminineDativePassiveSingularForm .
    ?participlePerfectFeminineDativePassiveSingularForm ontolex:representation ?participlePerfectFeminineDativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q625420, wd:Q1775415, wd:Q145599, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?participleFutureFeminineDativePassiveSingularForm .
    ?participleFutureFeminineDativePassiveSingularForm ontolex:representation ?participleFutureFeminineDativePassiveSingular ;
      wikibase:grammaticalFeature wd:Q814722, wd:Q501405, wd:Q1775415, wd:Q145599, wd:Q1194697, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeForm .
    ?singularAblativeForm ontolex:representation ?singularAblative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativeForm .
    ?pluralAblativeForm ontolex:representation ?pluralAblative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }
}
