# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nouns
  ?genitiveSingular
  ?ablativePlural
  ?ablativeSingular
  ?nominativeSingular
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralForm .
    ?ablativePluralForm ontolex:representation ?ablativePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeSingularForm .
    ?ablativeSingularForm ontolex:representation ?ablativeSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }
}
