# tool: scribe-data
# All Estonian (Q9072) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?inessive
  ?elative
  ?translative
  ?inessiveSingular
  ?elativeSingular
  ?translativeSingular

WHERE {
  ?lexeme dct:language wd:Q9072 ;
      wikibase:lexicalCategory wd:Q468801 ;
      wikibase:lemma ?personalpronoun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveForm .
    ?inessiveForm ontolex:representation ?inessive ;
      wikibase:grammaticalFeature wd:Q282031 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeForm .
    ?elativeForm ontolex:representation ?elative ;
      wikibase:grammaticalFeature wd:Q394253 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativeForm .
    ?translativeForm ontolex:representation ?translative ;
      wikibase:grammaticalFeature wd:Q950170 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveSingularForm .
    ?inessiveSingularForm ontolex:representation ?inessiveSingular ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeSingularForm .
    ?elativeSingularForm ontolex:representation ?elativeSingular ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativeSingularForm .
    ?translativeSingularForm ontolex:representation ?translativeSingular ;
      wikibase:grammaticalFeature wd:Q950170, wd:Q110786 .
  }
}
