# tool: scribe-data
# All Dagbani (Q32238) pronouns (Q36224) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pronouns
  ?thirdPersonPlural
  ?secondPersonPlural
  ?thirdPersonSingular
  ?pluralThirdPerson
  ?pluralSecondPerson
  ?singularThirdPerson
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q32238 ;
      wikibase:lexicalCategory wd:Q36224 ;
      wikibase:lemma ?pronouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonPluralForm .
    ?thirdPersonPluralForm ontolex:representation ?thirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonPluralForm .
    ?secondPersonPluralForm ontolex:representation ?secondPersonPlural ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonSingularForm .
    ?thirdPersonSingularForm ontolex:representation ?thirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralThirdPersonForm .
    ?pluralThirdPersonForm ontolex:representation ?pluralThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralSecondPersonForm .
    ?pluralSecondPersonForm ontolex:representation ?pluralSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularThirdPersonForm .
    ?singularThirdPersonForm ontolex:representation ?singularThirdPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q51929074 .
  }
}
