# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?past
  ?singular
  ?fiilMudari
  ?nominativeDefiniteSingular
  ?nominativeDefinitePlural

WHERE {
  ?lexeme dct:language wd:Q13955 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?noun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastForm .
    ?pastForm ontolex:representation ?past ;
      wikibase:grammaticalFeature wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariForm .
    ?fiilMudariForm ontolex:representation ?fiilMudari ;
      wikibase:grammaticalFeature wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDefiniteSingularForm .
    ?nominativeDefiniteSingularForm ontolex:representation ?nominativeDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDefinitePluralForm .
    ?nominativeDefinitePluralForm ontolex:representation ?nominativeDefinitePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q53997851, wd:Q146786 .
  }
}
