# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nouns
  ?definitePluralAccusative
  ?definiteMasculinePausal
  ?feminineConstructAccusativeSingular
  ?accusativeDual
  ?pausalSingular
  ?genitiveSingular
  ?indefiniteMasculineSingular
  ?accusativeSingular
  ?definiteMasculineAccusativeDual
  ?definiteMasculineGenitiveSingular
  ?feminineAccusative
  ?indefiniteMasculineAccusative
  ?femininePausal
  ?definiteFemininePluralAccusative
  ?past
  ?definiteMasculinePausalSingular
  ?pluralNominative
  ?feminineConstructAccusativeDual
  ?definiteGenitiveSingular
  ?definiteFeminineNominativeDual
  ?indefinitePluralPausal
  ?definitePlural
  ?feminineSingular
  ?constructPluralNominative
  ?masculineDual
  ?indefinitePluralNominative
  ?indefiniteFeminineNominativeSingular
  ?masculineConstructGenitiveDual
  ?definiteMasculineSingular
  ?indefiniteMasculineGenitiveDual
  ?genitiveNominativeSingular
  ?feminine
  ?definiteMasculineAccusative
  ?indefiniteFeminineAccusativeSingular
  ?indefinitePausal
  ?feminineGenitive
  ?definitePluralPausal
  ?masculineGenitive
  ?feminineConstructPluralGenitive
  ?indefiniteFemininePluralNominative
  ?indefiniteSingular
  ?definitePluralNominative
  ?definiteFeminineNominativeSingular
  ?indefiniteFeminineAccusativeDual
  ?definiteMasculineGenitiveDual
  ?pluralPausal
  ?indefinite
  ?constructAccusativeSingular
  ?masculinePausalSingular
  ?definiteFeminineAccusativeSingular
  ?indefiniteAccusativeSingular
  ?feminineConstructPluralAccusative
  ?indefiniteFeminineGenitiveSingular
  ?indefiniteMasculinePausalDual
  ?definiteFemininePluralNominative
  ?definiteSingular
  ?constructNominativeSingular
  ?masculineConstructNominativeDual
  ?indefiniteFeminineSingular
  ?indefiniteNominativeSingular
  ?indefiniteMasculineNominativeDual
  ?definiteFeminineAccusativeDual
  ?definite
  ?masculineNominative
  ?gerund
  ?definiteAccusativeSingular
  ?masculinePlural
  ?definiteFeminineGenitiveSingular
  ?masculinePausalDual
  ?indefiniteFemininePluralPausal
  ?nominativeSingular
  ?definiteMasculinePausalDual
  ?indefiniteMasculineNominative
  ?femininePausalSingular
  ?definiteFeminineSingular
  ?definiteNominativeSingular
  ?definiteMasculineNominativeDual
  ?singular
  ?indefiniteFemininePluralAccusative
  ?indefiniteMasculinePausalSingular
  ?indefiniteFemininePausalSingular
  ?masculineConstructNominativeSingular
  ?indefiniteFemininePausalDual
  ?indefiniteGenitiveSingular
  ?constructPluralGenitive
  ?masculineGenitiveAccusativeDual
  ?feminineConstructNominativeDual
  ?indefiniteMasculineNominativeSingular
  ?indefinitePluralGenitive
  ?definiteFemininePluralPausal
  ?masculineAccusative
  ?masculineConstructAccusativeSingular
  ?constructPausalSingular
  ?definiteMasculineNominative
  ?feminineNominative
  ?plural
  ?indefiniteMasculineAccusativeSingular
  ?indefinitePausalSingular
  ?feminineConstructPluralNominative
  ?dual
  ?femininePlural
  ?indefiniteFemininePluralGenitive
  ?constructPluralAccusative
  ?definiteFemininePausalSingular
  ?indefinitePluralAccusative
  ?feminineConstructGenitiveSingular
  ?masculinePausal
  ?indefiniteMasculinePluralNominative
  ?nominativeDual
  ?indefiniteFeminineNominativeDual
  ?fiilMudari
  ?definiteMasculineNominativeSingular
  ?masculineConstructGenitiveSingular
  ?masculineConstructAccusativeDual
  ?indefiniteMasculinePluralPausal
  ?definitePluralGenitive
  ?indefiniteMasculineAccusativeDual
  ?indefiniteMasculineGenitiveSingular
  ?masculineSingular
  ?feminineConstructNominativeSingular
  ?definiteMasculinePlural
  ?constructGenitiveSingular
  ?definiteMasculineAccusativeSingular
  ?definitePausalSingular
  ?indefiniteNominative
  ?femininePluralPausal
  ?definiteFemininePluralGenitive
  ?feminineConstructSingular
  ?indefinitePlural
  ?dualIndefiniteFemininePausal
  ?pluralIndefiniteFeminineNominative
  ?pluralIndefiniteFeminineGenitive
  ?dualIndefiniteFeminineNominative
  ?dualIndefiniteFeminineGenitive
  ?pluralIndefiniteMasculineAccusative
  ?dualIndefiniteMasculineAccusative
  ?pluralIndefiniteMasculineNominative
  ?singularIndefiniteFeminineAccusative
  ?dualIndefiniteMasculineNominative
  ?singularIndefiniteMasculineGenitive
  ?singularIndefiniteFemininePausal
  ?singularIndefiniteFeminineNominative
  ?singularIndefiniteFeminineGenitive
  ?pluralIndefiniteMasculinePausal
  ?dualIndefiniteMasculinePausal
  ?dualIndefiniteMasculineGenitive
  ?singularIndefiniteMasculineAccusative
  ?singularIndefiniteMasculineNominative
  ?pluralIndefiniteFeminineAccusative
  ?dualIndefiniteFeminineAccusative
  ?pluralIndefiniteMasculineGenitive
  ?pluralIndefiniteFemininePausal
  ?singularIndefiniteMasculinePausal
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q13955 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?nouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePluralAccusativeForm .
    ?definitePluralAccusativeForm ontolex:representation ?definitePluralAccusative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculinePausalForm .
    ?definiteMasculinePausalForm ontolex:representation ?definiteMasculinePausal ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructAccusativeSingularForm .
    ?feminineConstructAccusativeSingularForm ontolex:representation ?feminineConstructAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeDualForm .
    ?accusativeDualForm ontolex:representation ?accusativeDual ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalSingularForm .
    ?pausalSingularForm ontolex:representation ?pausalSingular ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineSingularForm .
    ?indefiniteMasculineSingularForm ontolex:representation ?indefiniteMasculineSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineAccusativeDualForm .
    ?definiteMasculineAccusativeDualForm ontolex:representation ?definiteMasculineAccusativeDual ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineGenitiveSingularForm .
    ?definiteMasculineGenitiveSingularForm ontolex:representation ?definiteMasculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeForm .
    ?feminineAccusativeForm ontolex:representation ?feminineAccusative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineAccusativeForm .
    ?indefiniteMasculineAccusativeForm ontolex:representation ?indefiniteMasculineAccusative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePausalForm .
    ?femininePausalForm ontolex:representation ?femininePausal ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFemininePluralAccusativeForm .
    ?definiteFemininePluralAccusativeForm ontolex:representation ?definiteFemininePluralAccusative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastForm .
    ?pastForm ontolex:representation ?past ;
      wikibase:grammaticalFeature wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculinePausalSingularForm .
    ?definiteMasculinePausalSingularForm ontolex:representation ?definiteMasculinePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralNominativeForm .
    ?pluralNominativeForm ontolex:representation ?pluralNominative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructAccusativeDualForm .
    ?feminineConstructAccusativeDualForm ontolex:representation ?feminineConstructAccusativeDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteGenitiveSingularForm .
    ?definiteGenitiveSingularForm ontolex:representation ?definiteGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineNominativeDualForm .
    ?definiteFeminineNominativeDualForm ontolex:representation ?definiteFeminineNominativeDual ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePluralPausalForm .
    ?indefinitePluralPausalForm ontolex:representation ?indefinitePluralPausal ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePluralForm .
    ?definitePluralForm ontolex:representation ?definitePlural ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularForm .
    ?feminineSingularForm ontolex:representation ?feminineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructPluralNominativeForm .
    ?constructPluralNominativeForm ontolex:representation ?constructPluralNominative ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDualForm .
    ?masculineDualForm ontolex:representation ?masculineDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePluralNominativeForm .
    ?indefinitePluralNominativeForm ontolex:representation ?indefinitePluralNominative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineNominativeSingularForm .
    ?indefiniteFeminineNominativeSingularForm ontolex:representation ?indefiniteFeminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructGenitiveDualForm .
    ?masculineConstructGenitiveDualForm ontolex:representation ?masculineConstructGenitiveDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q146233, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineSingularForm .
    ?definiteMasculineSingularForm ontolex:representation ?definiteMasculineSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineGenitiveDualForm .
    ?indefiniteMasculineGenitiveDualForm ontolex:representation ?indefiniteMasculineGenitiveDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146233, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNominativeSingularForm .
    ?genitiveNominativeSingularForm ontolex:representation ?genitiveNominativeSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineForm .
    ?feminineForm ontolex:representation ?feminine ;
      wikibase:grammaticalFeature wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineAccusativeForm .
    ?definiteMasculineAccusativeForm ontolex:representation ?definiteMasculineAccusative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineAccusativeSingularForm .
    ?indefiniteFeminineAccusativeSingularForm ontolex:representation ?indefiniteFeminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePausalForm .
    ?indefinitePausalForm ontolex:representation ?indefinitePausal ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineGenitiveForm .
    ?feminineGenitiveForm ontolex:representation ?feminineGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePluralPausalForm .
    ?definitePluralPausalForm ontolex:representation ?definitePluralPausal ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveForm .
    ?masculineGenitiveForm ontolex:representation ?masculineGenitive ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructPluralGenitiveForm .
    ?feminineConstructPluralGenitiveForm ontolex:representation ?feminineConstructPluralGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePluralNominativeForm .
    ?indefiniteFemininePluralNominativeForm ontolex:representation ?indefiniteFemininePluralNominative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteSingularForm .
    ?indefiniteSingularForm ontolex:representation ?indefiniteSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePluralNominativeForm .
    ?definitePluralNominativeForm ontolex:representation ?definitePluralNominative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineNominativeSingularForm .
    ?definiteFeminineNominativeSingularForm ontolex:representation ?definiteFeminineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineAccusativeDualForm .
    ?indefiniteFeminineAccusativeDualForm ontolex:representation ?indefiniteFeminineAccusativeDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineGenitiveDualForm .
    ?definiteMasculineGenitiveDualForm ontolex:representation ?definiteMasculineGenitiveDual ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146233, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPausalForm .
    ?pluralPausalForm ontolex:representation ?pluralPausal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteForm .
    ?indefiniteForm ontolex:representation ?indefinite ;
      wikibase:grammaticalFeature wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructAccusativeSingularForm .
    ?constructAccusativeSingularForm ontolex:representation ?constructAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePausalSingularForm .
    ?masculinePausalSingularForm ontolex:representation ?masculinePausalSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineAccusativeSingularForm .
    ?definiteFeminineAccusativeSingularForm ontolex:representation ?definiteFeminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteAccusativeSingularForm .
    ?indefiniteAccusativeSingularForm ontolex:representation ?indefiniteAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructPluralAccusativeForm .
    ?feminineConstructPluralAccusativeForm ontolex:representation ?feminineConstructPluralAccusative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineGenitiveSingularForm .
    ?indefiniteFeminineGenitiveSingularForm ontolex:representation ?indefiniteFeminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculinePausalDualForm .
    ?indefiniteMasculinePausalDualForm ontolex:representation ?indefiniteMasculinePausalDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q117262361, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFemininePluralNominativeForm .
    ?definiteFemininePluralNominativeForm ontolex:representation ?definiteFemininePluralNominative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteSingularForm .
    ?definiteSingularForm ontolex:representation ?definiteSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructNominativeSingularForm .
    ?constructNominativeSingularForm ontolex:representation ?constructNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructNominativeDualForm .
    ?masculineConstructNominativeDualForm ontolex:representation ?masculineConstructNominativeDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineSingularForm .
    ?indefiniteFeminineSingularForm ontolex:representation ?indefiniteFeminineSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteNominativeSingularForm .
    ?indefiniteNominativeSingularForm ontolex:representation ?indefiniteNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineNominativeDualForm .
    ?indefiniteMasculineNominativeDualForm ontolex:representation ?indefiniteMasculineNominativeDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineAccusativeDualForm .
    ?definiteFeminineAccusativeDualForm ontolex:representation ?definiteFeminineAccusativeDual ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteForm .
    ?definiteForm ontolex:representation ?definite ;
      wikibase:grammaticalFeature wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineNominativeForm .
    ?masculineNominativeForm ontolex:representation ?masculineNominative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?gerundForm .
    ?gerundForm ontolex:representation ?gerund ;
      wikibase:grammaticalFeature wd:Q1923028 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteAccusativeSingularForm .
    ?definiteAccusativeSingularForm ontolex:representation ?definiteAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralForm .
    ?masculinePluralForm ontolex:representation ?masculinePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineGenitiveSingularForm .
    ?definiteFeminineGenitiveSingularForm ontolex:representation ?definiteFeminineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePausalDualForm .
    ?masculinePausalDualForm ontolex:representation ?masculinePausalDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q117262361, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePluralPausalForm .
    ?indefiniteFemininePluralPausalForm ontolex:representation ?indefiniteFemininePluralPausal ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculinePausalDualForm .
    ?definiteMasculinePausalDualForm ontolex:representation ?definiteMasculinePausalDual ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q117262361, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineNominativeForm .
    ?indefiniteMasculineNominativeForm ontolex:representation ?indefiniteMasculineNominative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePausalSingularForm .
    ?femininePausalSingularForm ontolex:representation ?femininePausalSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFeminineSingularForm .
    ?definiteFeminineSingularForm ontolex:representation ?definiteFeminineSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteNominativeSingularForm .
    ?definiteNominativeSingularForm ontolex:representation ?definiteNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineNominativeDualForm .
    ?definiteMasculineNominativeDualForm ontolex:representation ?definiteMasculineNominativeDual ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePluralAccusativeForm .
    ?indefiniteFemininePluralAccusativeForm ontolex:representation ?indefiniteFemininePluralAccusative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculinePausalSingularForm .
    ?indefiniteMasculinePausalSingularForm ontolex:representation ?indefiniteMasculinePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePausalSingularForm .
    ?indefiniteFemininePausalSingularForm ontolex:representation ?indefiniteFemininePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructNominativeSingularForm .
    ?masculineConstructNominativeSingularForm ontolex:representation ?masculineConstructNominativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePausalDualForm .
    ?indefiniteFemininePausalDualForm ontolex:representation ?indefiniteFemininePausalDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q117262361, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteGenitiveSingularForm .
    ?indefiniteGenitiveSingularForm ontolex:representation ?indefiniteGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructPluralGenitiveForm .
    ?constructPluralGenitiveForm ontolex:representation ?constructPluralGenitive ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveAccusativeDualForm .
    ?masculineGenitiveAccusativeDualForm ontolex:representation ?masculineGenitiveAccusativeDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructNominativeDualForm .
    ?feminineConstructNominativeDualForm ontolex:representation ?feminineConstructNominativeDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineNominativeSingularForm .
    ?indefiniteMasculineNominativeSingularForm ontolex:representation ?indefiniteMasculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePluralGenitiveForm .
    ?indefinitePluralGenitiveForm ontolex:representation ?indefinitePluralGenitive ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFemininePluralPausalForm .
    ?definiteFemininePluralPausalForm ontolex:representation ?definiteFemininePluralPausal ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeForm .
    ?masculineAccusativeForm ontolex:representation ?masculineAccusative ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructAccusativeSingularForm .
    ?masculineConstructAccusativeSingularForm ontolex:representation ?masculineConstructAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructPausalSingularForm .
    ?constructPausalSingularForm ontolex:representation ?constructPausalSingular ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineNominativeForm .
    ?definiteMasculineNominativeForm ontolex:representation ?definiteMasculineNominative ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineNominativeForm .
    ?feminineNominativeForm ontolex:representation ?feminineNominative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineAccusativeSingularForm .
    ?indefiniteMasculineAccusativeSingularForm ontolex:representation ?indefiniteMasculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePausalSingularForm .
    ?indefinitePausalSingularForm ontolex:representation ?indefinitePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructPluralNominativeForm .
    ?feminineConstructPluralNominativeForm ontolex:representation ?feminineConstructPluralNominative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualForm .
    ?dualForm ontolex:representation ?dual ;
      wikibase:grammaticalFeature wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralForm .
    ?femininePluralForm ontolex:representation ?femininePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFemininePluralGenitiveForm .
    ?indefiniteFemininePluralGenitiveForm ontolex:representation ?indefiniteFemininePluralGenitive ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructPluralAccusativeForm .
    ?constructPluralAccusativeForm ontolex:representation ?constructPluralAccusative ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFemininePausalSingularForm .
    ?definiteFemininePausalSingularForm ontolex:representation ?definiteFemininePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePluralAccusativeForm .
    ?indefinitePluralAccusativeForm ontolex:representation ?indefinitePluralAccusative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146786, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructGenitiveSingularForm .
    ?feminineConstructGenitiveSingularForm ontolex:representation ?feminineConstructGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePausalForm .
    ?masculinePausalForm ontolex:representation ?masculinePausal ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculinePluralNominativeForm .
    ?indefiniteMasculinePluralNominativeForm ontolex:representation ?indefiniteMasculinePluralNominative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDualForm .
    ?nominativeDualForm ontolex:representation ?nominativeDual ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteFeminineNominativeDualForm .
    ?indefiniteFeminineNominativeDualForm ontolex:representation ?indefiniteFeminineNominativeDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q1775415, wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?fiilMudariForm .
    ?fiilMudariForm ontolex:representation ?fiilMudari ;
      wikibase:grammaticalFeature wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineNominativeSingularForm .
    ?definiteMasculineNominativeSingularForm ontolex:representation ?definiteMasculineNominativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructGenitiveSingularForm .
    ?masculineConstructGenitiveSingularForm ontolex:representation ?masculineConstructGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineConstructAccusativeDualForm .
    ?masculineConstructAccusativeDualForm ontolex:representation ?masculineConstructAccusativeDual ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1641446, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculinePluralPausalForm .
    ?indefiniteMasculinePluralPausalForm ontolex:representation ?indefiniteMasculinePluralPausal ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePluralGenitiveForm .
    ?definitePluralGenitiveForm ontolex:representation ?definitePluralGenitive ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineAccusativeDualForm .
    ?indefiniteMasculineAccusativeDualForm ontolex:representation ?indefiniteMasculineAccusativeDual ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteMasculineGenitiveSingularForm .
    ?indefiniteMasculineGenitiveSingularForm ontolex:representation ?indefiniteMasculineGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q499327, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularForm .
    ?masculineSingularForm ontolex:representation ?masculineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructNominativeSingularForm .
    ?feminineConstructNominativeSingularForm ontolex:representation ?feminineConstructNominativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculinePluralForm .
    ?definiteMasculinePluralForm ontolex:representation ?definiteMasculinePlural ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?constructGenitiveSingularForm .
    ?constructGenitiveSingularForm ontolex:representation ?constructGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1641446, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteMasculineAccusativeSingularForm .
    ?definiteMasculineAccusativeSingularForm ontolex:representation ?definiteMasculineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q499327, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definitePausalSingularForm .
    ?definitePausalSingularForm ontolex:representation ?definitePausalSingular ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q117262361, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteNominativeForm .
    ?indefiniteNominativeForm ontolex:representation ?indefiniteNominative ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralPausalForm .
    ?femininePluralPausalForm ontolex:representation ?femininePluralPausal ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?definiteFemininePluralGenitiveForm .
    ?definiteFemininePluralGenitiveForm ontolex:representation ?definiteFemininePluralGenitive ;
      wikibase:grammaticalFeature wd:Q53997851, wd:Q1775415, wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineConstructSingularForm .
    ?feminineConstructSingularForm ontolex:representation ?feminineConstructSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1641446, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefinitePluralForm .
    ?indefinitePluralForm ontolex:representation ?indefinitePlural ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteFemininePausalForm .
    ?dualIndefiniteFemininePausalForm ontolex:representation ?dualIndefiniteFemininePausal ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q1775415, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteFeminineNominativeForm .
    ?pluralIndefiniteFeminineNominativeForm ontolex:representation ?pluralIndefiniteFeminineNominative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q1775415, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteFeminineGenitiveForm .
    ?pluralIndefiniteFeminineGenitiveForm ontolex:representation ?pluralIndefiniteFeminineGenitive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q1775415, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteFeminineNominativeForm .
    ?dualIndefiniteFeminineNominativeForm ontolex:representation ?dualIndefiniteFeminineNominative ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q1775415, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteFeminineGenitiveForm .
    ?dualIndefiniteFeminineGenitiveForm ontolex:representation ?dualIndefiniteFeminineGenitive ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q1775415, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteMasculineAccusativeForm .
    ?pluralIndefiniteMasculineAccusativeForm ontolex:representation ?pluralIndefiniteMasculineAccusative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q499327, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteMasculineAccusativeForm .
    ?dualIndefiniteMasculineAccusativeForm ontolex:representation ?dualIndefiniteMasculineAccusative ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q499327, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteMasculineNominativeForm .
    ?pluralIndefiniteMasculineNominativeForm ontolex:representation ?pluralIndefiniteMasculineNominative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q499327, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteFeminineAccusativeForm .
    ?singularIndefiniteFeminineAccusativeForm ontolex:representation ?singularIndefiniteFeminineAccusative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q1775415, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteMasculineNominativeForm .
    ?dualIndefiniteMasculineNominativeForm ontolex:representation ?dualIndefiniteMasculineNominative ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q499327, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteMasculineGenitiveForm .
    ?singularIndefiniteMasculineGenitiveForm ontolex:representation ?singularIndefiniteMasculineGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q499327, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteFemininePausalForm .
    ?singularIndefiniteFemininePausalForm ontolex:representation ?singularIndefiniteFemininePausal ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q1775415, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteFeminineNominativeForm .
    ?singularIndefiniteFeminineNominativeForm ontolex:representation ?singularIndefiniteFeminineNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q1775415, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteFeminineGenitiveForm .
    ?singularIndefiniteFeminineGenitiveForm ontolex:representation ?singularIndefiniteFeminineGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q1775415, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteMasculinePausalForm .
    ?pluralIndefiniteMasculinePausalForm ontolex:representation ?pluralIndefiniteMasculinePausal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q499327, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteMasculinePausalForm .
    ?dualIndefiniteMasculinePausalForm ontolex:representation ?dualIndefiniteMasculinePausal ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q499327, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteMasculineGenitiveForm .
    ?dualIndefiniteMasculineGenitiveForm ontolex:representation ?dualIndefiniteMasculineGenitive ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q499327, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteMasculineAccusativeForm .
    ?singularIndefiniteMasculineAccusativeForm ontolex:representation ?singularIndefiniteMasculineAccusative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q499327, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteMasculineNominativeForm .
    ?singularIndefiniteMasculineNominativeForm ontolex:representation ?singularIndefiniteMasculineNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q499327, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteFeminineAccusativeForm .
    ?pluralIndefiniteFeminineAccusativeForm ontolex:representation ?pluralIndefiniteFeminineAccusative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q1775415, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualIndefiniteFeminineAccusativeForm .
    ?dualIndefiniteFeminineAccusativeForm ontolex:representation ?dualIndefiniteFeminineAccusative ;
      wikibase:grammaticalFeature wd:Q110022, wd:Q53997857, wd:Q1775415, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteMasculineGenitiveForm .
    ?pluralIndefiniteMasculineGenitiveForm ontolex:representation ?pluralIndefiniteMasculineGenitive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q499327, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIndefiniteFemininePausalForm .
    ?pluralIndefiniteFemininePausalForm ontolex:representation ?pluralIndefiniteFemininePausal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q53997857, wd:Q1775415, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIndefiniteMasculinePausalForm .
    ?singularIndefiniteMasculinePausalForm ontolex:representation ?singularIndefiniteMasculinePausal ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997857, wd:Q499327, wd:Q117262361 .
  }
}
