# tool: scribe-data
# All Tamil (Q5885) pronouns (Q36224) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pronouns
  ?dativeSingular
  ?pluralDative
  ?nominativeSingular
  ?pluralNominative
  ?nominativePlural
  ?singularNominative
  ?dativePlural
  ?singularDative
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q5885 ;
      wikibase:lexicalCategory wd:Q36224 ;
      wikibase:lemma ?pronouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralDativeForm .
    ?pluralDativeForm ontolex:representation ?pluralDative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralNominativeForm .
    ?pluralNominativeForm ontolex:representation ?pluralNominative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralForm .
    ?nominativePluralForm ontolex:representation ?nominativePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeForm .
    ?singularDativeForm ontolex:representation ?singularDative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599 .
  }
}
