# tool: scribe-data
# All Danish (Q9035) pronouns (Q36224) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pronouns
  ?nonGenitiveNeuterSingular
  ?oblique
  ?nonGenitiveCommonSingular
  ?feminineGenitive
  ?nonGenitivePlural
  ?common
  ?neuter
  ?plural
  ?masculineGenitive
  ?genitiveCommonSingular
  ?nonGenitive
  ?nominative
  ?commonSingular
  ?neuterSingular
  ?neuterGenitiveSingular
  ?pluralGenitive
  ?genitive
  ?lastModified

WHERE {
  ?lexeme dct:language wd:Q9035 ;
      wikibase:lexicalCategory wd:Q36224 ;
      wikibase:lemma ?pronouns ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitiveNeuterSingularForm .
    ?nonGenitiveNeuterSingularForm ontolex:representation ?nonGenitiveNeuterSingular ;
      wikibase:grammaticalFeature wd:Q98946930, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueForm .
    ?obliqueForm ontolex:representation ?oblique ;
      wikibase:grammaticalFeature wd:Q1233197 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitiveCommonSingularForm .
    ?nonGenitiveCommonSingularForm ontolex:representation ?nonGenitiveCommonSingular ;
      wikibase:grammaticalFeature wd:Q98946930, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineGenitiveForm .
    ?feminineGenitiveForm ontolex:representation ?feminineGenitive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitivePluralForm .
    ?nonGenitivePluralForm ontolex:representation ?nonGenitivePlural ;
      wikibase:grammaticalFeature wd:Q98946930, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?commonForm .
    ?commonForm ontolex:representation ?common ;
      wikibase:grammaticalFeature wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterForm .
    ?neuterForm ontolex:representation ?neuter ;
      wikibase:grammaticalFeature wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineGenitiveForm .
    ?masculineGenitiveForm ontolex:representation ?masculineGenitive ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveCommonSingularForm .
    ?genitiveCommonSingularForm ontolex:representation ?genitiveCommonSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitiveForm .
    ?nonGenitiveForm ontolex:representation ?nonGenitive ;
      wikibase:grammaticalFeature wd:Q98946930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?commonSingularForm .
    ?commonSingularForm ontolex:representation ?commonSingular ;
      wikibase:grammaticalFeature wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterSingularForm .
    ?neuterSingularForm ontolex:representation ?neuterSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterGenitiveSingularForm .
    ?neuterGenitiveSingularForm ontolex:representation ?neuterGenitiveSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralGenitiveForm .
    ?pluralGenitiveForm ontolex:representation ?pluralGenitive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }
}
