name: Create Automated PR
on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rich requests tqdm
          pip install -e .

      - name: Run download_wd.py
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/src python src/scribe_data/check/download_wd.py | tee output.txt
          DOWNLOAD_PATH=$(grep "DOWNLOAD_PATH=" output.txt | cut -d'=' -f2)
          echo "Download path: ${DOWNLOAD_PATH}"
          if [ -n "${DOWNLOAD_PATH}" ]; then
            ls -la "$(dirname "${DOWNLOAD_PATH}")"
            echo "Running check_missing_forms.py..."
            PYTHONPATH=$PYTHONPATH:$(pwd)/src python src/scribe_data/check/check_missing_forms.py
          else
            echo "Download path not found, skipping check_missing_forms.py"
            exit 1
          fi

      # Debug steps to understand the state
      - name: Debug Info
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "List of changes:"
          git status

      # Make some changes (example)
      - name: Make changes
        run: |
          echo "# Test Change" >> README.md
          git config --global user.email "muhamadasif570@gmail.com"
          git config --global user.name "axif0"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automated PR from feature branch'
          body: |
            This PR was automatically created by a GitHub Action.

            Changes included in this PR:
            - Please review the changes and provide feedback
          base: master
          branch: automated-pr
          delete-branch: true
          draft: false
          commit-message: '[create-pull-request] automated change'
          committer: GitHub <noreply@github.com>
          author: axif0 <axif0@users.noreply.github.com>

      # Debug step to verify PR creation attempt
      - name: Check PR Creation
        run: |
          echo "Checking if PR was created..."
          gh pr list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
