name: Check and Update Missing Query Forms
on:
  schedule:
    # Runs at 00:00 UTC on the first day of every month.
    - cron: "0 0 1 * *"
  workflow_dispatch: # allow manual trigger

jobs:
  check-repository:
    runs-on: ubuntu-latest
    outputs:
      is_correct_repo: ${{ steps.check.outputs.is_correct_repo }}
    steps:
      - name: Check repository
        id: check
        run: |
          if [ "$GITHUB_REPOSITORY" = "axif0/test-scribe" ]; then
            echo "is_correct_repo=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_correct_repo=false" >> "$GITHUB_OUTPUT"
            echo "::warning::This workflow should only run in scribe-org/Scribe-Data repository."
          fi
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rich requests tqdm
          pip install -e .
      - name: Generate Missing Features Data
        run: |
          # Set up paths
          QUERY_DIR="$(pwd)/src/scribe_data/wikidata/language_data_extraction"

          echo "Query directory: ${QUERY_DIR}"

          # Generate the missing features data with all keys processing and automatic dump download
          PYTHONPATH=$PYTHONPATH:$(pwd)/src python src/scribe_data/check/check_missing_forms/check_missing_forms.py "${QUERY_DIR}" --download-dump --process-all-keys

      - name: Make changes
        run: |
          git add src/scribe_data/wikidata/language_data_extraction/**/*.sparql
          git config --global user.email "muhamadasif570@gmail.com"
          git config --global user.name "axif0"

      - name: check generated query forms
        working-directory: ./src/scribe_data/check
        run: |
          python check_query_forms.py

      - name: Post-run status
        if: failure()
        run: echo "Project SPARQL query forms check failed. Please fix the reported errors."

      - name: Generate PR Body
        id: pr-body
        run: |
          # Run the pr_body.py script with the missing features data
          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/pr_body.py missing_features.json)  || echo "No missing features/forms found.



          # Initialize PR body with delimiter
          {
            echo "body<<EOF"
            echo "$PR_BODY_CONTENT"
            echo "EOF"
          } >> $GITHUB_OUTPUT



      - name: Create Pull Request
        if: steps.pr-body.outputs.body != 'No missing features/forms found.'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automated PR: Updated Language Data Files'
          body: ${{ steps.pr-body.outputs.body }}
          base: master
          branch: automated-missing-forms-pr
          delete-branch: true
          draft: false
          commit-message: '[create-pull-request] automated change'
          committer: GitHub <noreply@github.com>
          author: axif0 <axif0@users.noreply.github.com>
