name: Check and Update Emoji Data
# on:
#   schedule:
#     - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
#   workflow_dispatch:  # Allow manual triggering
on:
    push:
      branches:
        - master

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo apt-get install jq

      - name: Download and check emoji data
        id: check-updates
        run: |
          # Create directories if they don't exist
          mkdir -p src/scribe_data/unicode/cldr-annotations-derived-full
          mkdir -p src/scribe_data/unicode/cldr-annotations-full
          
          CHANGES_EXIST=false
          
          # Get list of all language codes from package.json
          echo "Fetching language list..."
          LANG_LIST=$(curl -s https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-full/package.json | jq -r '.keywords[]')
          
          echo "Language list: $LANG_LIST"
          
          for lang in $LANG_LIST; do
            # Download latest data for each language
            mkdir -p "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang"
            mkdir -p "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang"
            
            curl -L "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-derived-full/annotationsDerived/$lang/annotations.json" -o "new_derived_$lang.json"
            curl -L "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-full/annotations/$lang/annotations.json" -o "new_full_$lang.json"
            
            # Check derived annotations
            if [ -f "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang/annotations.json" ]; then
              if ! cmp -s "new_derived_$lang.json" "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang/annotations.json"; then
                CHANGES_EXIST=true
              fi
            else
              CHANGES_EXIST=true
            fi
            
            # Check full annotations
            if [ -f "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang/annotations.json" ]; then
              if ! cmp -s "new_full_$lang.json" "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang/annotations.json"; then
                CHANGES_EXIST=true
              fi
            else
              CHANGES_EXIST=true
            fi
          done
          
          echo "changes_exist=${CHANGES_EXIST}" >> $GITHUB_OUTPUT

      - name: Update files if changed
        if: steps.check-updates.outputs.changes_exist == 'true'
        run: |
          # Get language list again for moving files
          LANG_LIST=$(curl -s https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-full/package.json | jq -r '.keywords[]')
          
          for lang in $LANG_LIST; do
            mkdir -p "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang"
            mkdir -p "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang"
            
            mv "new_derived_$lang.json" "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang/annotations.json"
            mv "new_full_$lang.json" "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang/annotations.json"
          done
          
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create Pull Request
        if: steps.check-updates.outputs.changes_exist == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore: Update emoji annotations data'
          body: |
            This PR updates the emoji annotations data from CLDR:
            - Updated cldr-annotations-derived-full data
            - Updated cldr-annotations-full data
            
            This is an automated PR created by the emoji data update workflow.
          branch: update-emoji-data
          delete-branch: true
          commit-message: 'chore: Update emoji annotations data'
          labels: |
            automated pr
            emoji-data
