name: Check and Update Emoji Data
# on:
#   schedule:
#     - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
#   workflow_dispatch:  # Allow manual triggering
on:
    push:
      branches:
        - master

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo apt-get install jq

      - name: Download and check emoji data
        id: check-updates
        run: |
          # Create directories if they don't exist
          mkdir -p src/scribe_data/unicode/cldr-annotations-derived-full
          mkdir -p src/scribe_data/unicode/cldr-annotations-full
          
          # Get list of languages from CLDR repository
          LANG_LIST=$(curl -s https://api.github.com/repos/unicode-org/cldr-json/contents/cldr-json/cldr-annotations-full/annotations | jq -r '.[].name')
          
          # Download and process for each language
          for lang in $LANG_LIST; do
            echo "Processing $lang..."
            
            # Create language directories
            mkdir -p "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang"
            mkdir -p "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang"
            
            # Download and move files
            mv "new_derived_$lang.json" "src/scribe_data/unicode/cldr-annotations-derived-full/annotationsDerived/$lang/annotations.json"
            mv "new_full_$lang.json" "src/scribe_data/unicode/cldr-annotations-full/annotations/$lang/annotations.json"
          done

      - name: Create Pull Request
        if: steps.check-updates.outputs.changes_exist == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore: Update emoji annotations data'
          body: |
            This PR updates the emoji annotations data from CLDR:
            - Updated cldr-annotations-derived-full data
            - Updated cldr-annotations-full data
            
            This is an automated PR created by the emoji data update workflow.
          branch: update-emoji-data
          delete-branch: true
          commit-message: 'chore: Update emoji annotations data'
          labels: |
            automated pr
            emoji-data
