# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?supine
  ?infinitivePresent
  ?ablativeFuturePluralParticiple
  ?ablativePerfectPluralParticiple
  ?masculineActiveFutureParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?supineForm .
    ?supineForm ontolex:representation ?supine ;
      wikibase:grammaticalFeature wd:Q548470 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePresentForm .
    ?infinitivePresentForm ontolex:representation ?infinitivePresent ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFuturePluralParticipleForm .
    ?ablativeFuturePluralParticipleForm ontolex:representation ?ablativeFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePerfectPluralParticipleForm .
    ?ablativePerfectPluralParticipleForm ontolex:representation ?ablativePerfectPluralParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q625420, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineActiveFutureParticipleForm .
    ?masculineActiveFutureParticipleForm ontolex:representation ?masculineActiveFutureParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q501405, wd:Q814722 .
  }
}
